### PR TITLE
Added Disarium Number Calculator

### LINKED ISSUE #512: [Feature] Adding Disarium Number Calculator
### Description

Disarium number

A number is said to be the Disarium number when the sum of its digit raised to the power of their respective positions is equal to the number itself.

For example, 175 is a Disarium number as follows

11 + 72 + 53 = 1 + 49 + 125 = 175
Some of the other examples of Disarium number are 89, 135, 518 etc.

### Screenshots

Screenshot 2024-01-29 235338

Style is just for demo

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️ #512 

Closes #512 

# Description👨‍💻 

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

DS

DN

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this

**Comment by AftabMankapure** [comment]
check it now

**Comment by AftabMankapure** [comment]
bro it possible to change label already completed PR
i want JWOC label instead of IWOC
for PR number 
#517 
#461 
#365 
#323 
#317

pls do it

**Comment by Rakesh9100** [comment]
Merged 🎉 @AftabMankapure

**Pull request merged**
