### PR TITLE
Added Sound Level Calculator

### LINKED ISSUE #1302: [Feature] Add Sound Level Calculator
### Description

Converts sound levels between different units (dB, SPL) and predicts sound attenuation over distance.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by 1911aditi**
# Fixes Issue🛠️

Closes #1302 

# Description👨‍💻

A sound level calculator involves designing a simple web interface where users can input sound levels in decibels (dB) and get the combined sound level as the output.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-24 000438

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these by making the new commits in this same PR @1911aditi 

1. Rename your folder to `Sound-Level-Calculator` and make the necessary changes.
2. Add a proper Readme file of your calculator as I can see it is empty.
3. Add your calculator part in the main index.html file to display it on the website.

**Comment by 1911aditi** [comment]
can you check now please? @Rakesh9100

**Comment by Rakesh9100** [comment]
Separate your CSS to style.css and script to script.js file, respectively.

And also, check the point 3 of previous comment and work accordingly @1911aditi

**Comment by 1911aditi** [comment]
can you check now please? @Rakesh9100

**Comment by Rakesh9100** [comment]
You have to add your calculator part in this [File](https://github.com/1911aditi/CalcDiverse/blob/main/index.html) to display it on the website @1911aditi

**Pull request merged**
