### PR TITLE
Added String To Integer Calculator

### LINKED ISSUE #1320: [Feature] Add String To Integer Calculator
### Description

The given input string is conveted into integer

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Fixes Issue🛠️

Closes #1320 

# Description👨‍💻

A simple web-based calculator that converts a string representation of a mathematical expression into its integer result.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

String-To-Integer-Calculator

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Attach some converted examples screenshots here @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> Attach some converted examples screenshots here @Saipradyumnagoud

yeah sure

**Comment by Saipradyumnagoud** [comment]
image


image

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Yes I have added You can review it now

**Comment by Rakesh9100** [comment]
What is this, you are solving mathematical expressions but it is String to Integer Calculator @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> What is this, you are solving mathematical expressions but it is String to Integer Calculator @Saipradyumnagoud

yes bro it is string expression

**Comment by Rakesh9100** [comment]
https://onlinestringtools.com/convert-string-to-decimal

Check this out, it is proper String to Integer Calculator where we write some string let's say CalcDiverse, and we get the integer/decimal form @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> https://onlinestringtools.com/convert-string-to-decimal
> 
> Check this out, it is proper String to Integer Calculator where we write some string let's say CalcDiverse, and we get the integer/decimal form @Saipradyumnagoud

oohh oky bro i will work it now i will modify the files withing 3 to 4 hrs
i will start working to convert proper string to integer

**Review by Saipradyumnagoud — COMMENTED** [review]
Updated the String to integer calculator

**Comment by Saipradyumnagoud** [comment]
example

image

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 now you can check i have changed the files

**Pull request merged**
