### PR TITLE
Implemented pagination on the website

### LINKED ISSUE #1445: [Feature] Implementation of pagination on the website
### Description

@Rakesh9100 
###  makes it easier for users to locate their calculator.

**Implementing pagination on your website not only improves its visual appeal but also significantly enhances user experience. By dividing content into manageable sections, users can easily navigate through the site without feeling overwhelmed by an excess of information on a single page. This organized structure helps users quickly find specific tools or features, such as a calculator, without getting lost in a sea of content.**

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pandeyji711**
@Rakesh9100 

# Fixes Issue 🛠️

Closes #1445 

# Description👨‍💻

I have implemented pagination on the homepage.
Made dedicated folder for pagination file, I have created pagination.css and pagination.js.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@pandeyji711 You UI is different from what you've specified in issue?

image

**Comment by pandeyji711** [comment]
> @pandeyji711 You UI is different from what you've specified in issue?
> 
> image

@Nihal4777 
currunt ui this matched with theam , and current one has additional feature  of go to page with input,
but that was not fit with theam

**Comment by Rakesh9100** [comment]
Please hold, as this issue was assigned to someone else before, you can take another issues for now @pandeyji711

**Comment by pandeyji711** [comment]
@Rakesh9100  why did you assign me??

**Comment by Rakesh9100** [comment]
I did not notice that and got assigned to you as well, let it be added and then you can make the modifications to it if you want @pandeyji711

**Comment by Rakesh9100** [comment]
I did not notice that and got assigned to you as well, let it be added, and then you can make the modifications to it if you want.

You can take these [up-for-grab](https://github.com/Rakesh9100/CalcDiverse/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grab+%E2%9C%8B%22) issues or create your own @pandeyji711

**Comment by pandeyji711** [comment]
@Rakesh9100 ok

**Comment by pandeyji711** [comment]
@Rakesh9100  please merge my pr

**Comment by Rakesh9100** [comment]
You can check that it is added, and you can do the enhancements if you want to the existing one @pandeyji711

**Comment by pandeyji711** [comment]
> You can check that it is added, and you can do the enhancements if you want to the existing one @pandeyji711

@Rakesh9100  my pagination theam is better in look and fit in website theam,
and it has input featue that directly redirect to prefered page

**Comment by Rakesh9100** [comment]
But you have shown good image in issue, but the implementation is simple, why is it so @pandeyji711

**Comment by pandeyji711** [comment]
> But you have shown good image in issue, but the implementation is simple, why is it so @pandeyji711

@Rakesh9100 sorry , I does't understand what you said

**Comment by Rakesh9100** [comment]
> @pandeyji711 You UI is different from what you've specified in issue?
> 
> image

About this? @pandeyji711

**Comment by pandeyji711** [comment]
> > @pandeyji711 You UI is different from what you've specified in issue?
> > image
> 
> About this? @pandeyji711

@Rakesh9100 
yes becouse that ui is not matching with the theam of website

**Pull request closed without merging**
