### PR TITLE
Fibonacci Calculator

### LINKED ISSUE #122: Add Fibonacci Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculating Fibonacci of any given number.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by ak4631**
# Fixes Issue🛠️
Closes #122 

# Description👨‍💻 

Calculating and Returning the Nth Fibonacci Number.

# Type of change📄

- Creating a Function to Calculate Fibonacci
- Handling Error to prevent load on website

# How this has been tested✅

# Checklist✅ 

- [] Dry Run the Code on Various Input.
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source Contributor

# Screenshots/GIF📷
fibo1
fibo2

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these: @ak4631

1. Mention the issue number this PR closes.
2. Add a `README.md` inside your calculator folder.
3. Add your calculator in main `index.html` file.

**Comment by ak4631** [comment]
@Rakesh9100 Done with the requirements.

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @ak4631

**Comment by ak4631** [comment]
Done @Rakesh9100

**Comment by Rakesh9100** [comment]
Good, Merged!! 🎉 @ak4631

**Pull request merged**
