### PR TITLE
Fixed the responsiveness of Rectangular to Polar Calculator

### LINKED ISSUE #384: [Bug] Rectangular Polar Calculator is not responsive
### What's the style idea?

We need to improve the overall style of the "Rectangular to Polar Calculator" and make it responsive for smaller screen sizes

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SaranshBangar**
# Fixes Issue🛠️

Closes #384 

# Description👨‍💻 

Completely refactored the CSS of the calculator to incorporate flexbox properties

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Runs on all the screen sizes and fixes the frontend accordingly

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Solves issue #384

**Comment by Rakesh9100** [comment]
Don't change the Ui, just make this UI responsive for every screen sizes @SaranshBangar

**Comment by Rakesh9100** [comment]
Don't change the UI, just make it responsive for every screen sizes @SaranshBangar

**Comment by SaranshBangar** [comment]
The new updates fixes issue #384 without changing the original UI

**Comment by Rakesh9100** [comment]
image

image

Make it properly responsive @SaranshBangar

**Comment by SaranshBangar** [comment]
The new updates fixes issue #384 without changing the original UI

**Comment by Rakesh9100** [comment]
image

Why background is getting reduced when reducing the screen size, do fix @SaranshBangar

**Pull request closed without merging**
