### PR TITLE
Feat: added triangle calculator

### LINKED ISSUE #70: Triangle Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The user can input any three values among the six values representing angles and sides in a triangle.

**Output:**
- Upon entering these values, the calculator will compute and output the remaining three values.
- The system will also provide the following details:
  - Type of triangle
  - Visual representation of the triangle
  - Area
  - Perimeter
  - Semiperimeter
  - Inradius
  - Circumradius
  - Height of the triangle from its three bases
  
  I am attaching the screenshots below, their UI is not that great. Styling can be improved too.

### Screenshots

Input:
image

Output:
image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Yatin12527**
# Fixes Issue🛠️

Closes #70 

# Description👨‍💻 

Added triangle calculator 

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅
locally

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls enhance the UI with some good color contrast and also add a Readme inside your folder @Yatin12527

**Comment by Yatin12527** [comment]
> Pls enhance the UI with some good color contrast and also add a Readme inside your folder @Yatin12527

If you merge it someone else can take the issue i personally found it very difficult to work with the js so i couldnot focus more on the ui and i apologise for that you can remove the branch if you want or you can merge it for someone else to make an issue and maybe fix it.

**Comment by Rakesh9100** [comment]
Why main `index.html` file is showing many changes done by you. You just have to include your calculator section @Yatin12527

**Comment by Yatin12527** [comment]
> Why main `index.html` file is showing many changes done by you. You just have to include your calculator section @Yatin12527

i just changed my part the conflicts are because few ppl added their branches before mine . I've checked the code and re ran it in my machine it shouldnot create any conflict u can try to merge it.

**Comment by Rakesh9100** [comment]
Add a Readme file inside your folder @Yatin12527 

And I dont need any change in main `index.html` file except your calculator section added @Yatin12527 Try to fix it as it is hampering previous changes

**Comment by Yatin12527** [comment]
> Add a Readme file inside your folder @Yatin12527
> 
> And I dont need any change in main `index.html` file except your calculator section added @Yatin12527 Try to fix it as it is hampering previous changes

Alright on it!!

**Comment by Yatin12527** [comment]
@Rakesh9100 i think it should be good to go now

**Comment by Rakesh9100** [comment]
Do resolve the conflicts @Yatin12527

**Comment by Rakesh9100** [comment]
Yes, main `index.html` file should be changes in this way only.

Do resolve the conflicts @Yatin12527

**Comment by Yatin12527** [comment]
@Rakesh9100 tried once again as the calculators keep adding it keeps conflicting so please merge my pr first then the prs that are made after my pr that way u can fix the conflicts.

**Comment by Rakesh9100** [comment]
Good job, Merged!! Congrats 🎉🎉 @Yatin12527

**Pull request merged**
