### PR TITLE
Footer links fixed

### LINKED ISSUE #252: [Bug] : Contributers section of footer not working
### Description

**Contributers option** in nevbar of **footer** is showing no response on clicking.
As shown in Screenshot.
kindly assign this issue to me under **IWOC24.**

### Screenshots

Screenshot 2024-01-14 171243

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️

Issue #252 

[Bug] : Contributers section of footer not working

Closes #252 

# Description👨‍💻 

The problem is solved for home page as well as contact page.

# How this has been tested✅

Tested by me on website. Problem solved!

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly check.

**Comment by Rakesh9100** [comment]
Provide a good PR title similar to the work you have done from the next time as I have edited it now @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
ok sir i will take care of it from next time.

**Comment by Rakesh9100** [comment]
Merged!! ✨ @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
thankyou sir😊

**Pull request merged**
