### PR TITLE
Added Standard Deviation Calculator

### LINKED ISSUE #1121: [Feature] Add Standard Deviation Calculator
### Description

It calculates the standard deviation, variance based on the data given.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #1121 

# Description👨‍💻

Added a calculator that computes standard deviation based on the input data.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
We already have Statistics Calculator to calculate Standard Deviation, then why do we need separate calculator @Yuvraj960

**Comment by Yuvraj960** [comment]
It's totally your wish now, that whether to add this calculator now or not. I didn't knew about the existence of standard deviation parameter in the statistics calculator.

**Comment by Rakesh9100** [comment]
Pls work on other issues, closing this @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 Can you recommend me any issues?

**Comment by Rakesh9100** [comment]
### We have many calculators. So you can create issues such as: @Yuvraj960 

1. There are many calculators which are not responsive, you can check and create issues for those one by one.

2. Most calculators, including the ones which you have added, don't handle NaN values correctly. If the user doesn't input values and clicks Calculate, there should be an alert or prompt to fill in the inputs first. Check and create issues to fix.

3. You can enhance the UI of calculators which are not that good or too simple.

**Comment by Rakesh9100** [comment]
### We have many calculators. So you can create issues such as: @Yuvraj960 

1. There are many calculators which are not responsive, you can check and create issues for those one by one.

2. Most calculators, including the ones which you have added, don't handle NaN values correctly. If the user doesn't input values and clicks Calculate, there should be an alert or prompt to fill in the inputs first. Check and create issues to fix.

3. You can enhance the UI of calculators which are not that good or too simple.

4. You can also check up-for-grab issues from [here](https://github.com/Rakesh9100/CalcDiverse/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grab+%E2%9C%8B%22) time to time, and some of them are up now.

**Pull request closed without merging**
