### PR TITLE
Added Equivalent Resistance Calculator

### LINKED ISSUE #327: [Feature] Equivalent Resistance Calculator
### Description

Equivalent Resistance Calculator for series and parallel resistance 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sakshamjain98**
# Fixes Issue🛠️

Closes #327 

# Description👨‍💻 

It consist of :

1. Series Configuration Equivalent resistance Calculation Property

2. Parallel Configuration Equivalent resistance Calculation Property

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Sakshamjain98** [comment]
Sir I have generated the pull request for both the issues #327 and #457

**Comment by Rakesh9100** [comment]
Keep the files of Resistance Calculator only in this PR, delete the QR Code files and create a new PR for QR issue @Sakshamjain98

**Comment by Rakesh9100** [comment]
No need to close this PR @Sakshamjain98 

Just create a new PR for QR Code Calculator!

**Comment by Sakshamjain98** [comment]
Ok sir

**Comment by Rakesh9100** [comment]
Seperate the css codes to `style.css`and js codes to `script.js` for quality code and clear understanding @Sakshamjain98

**Comment by Rakesh9100** [comment]
Merged 🎉 @Sakshamjain98

**Pull request merged**
