### PR TITLE
Added Dream Journal Calculator

### LINKED ISSUE #1390: [Feature] Add Dream Journal Calculator
### Description

this is quite an interesting calculator Analyzes dream entries based on keywords and emotions to generate insights or interpretations about recurring themes or patterns in dreams.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ananyag309**
# Fixes Issue🛠️

Closes #1390 

# Description👨‍💻

The Dream Journal Calculator is an intuitive web application designed to help users record, analyze, and gain insights into their dreams. By leveraging advanced text analysis and visualization techniques, it offers a comprehensive look at the themes, emotions, and sentiments present in dream entries. This tool is perfect for anyone interested in understanding their dreams better and uncovering hidden patterns or recurring themes.
Features - 
1- Dream Entry Recording - Allows users to input a title, date, detailed description, and emotions associated with their dreams.
2- Word Cloud Generation - Creates a visual representation of the most frequently occurring words in the dream description, highlighting key themes.
3- Recurring Words Analysis - Identifies and lists words that appear multiple times in the dream entry, providing insights into common themes.
4- Emotion Listing -Displays the emotions associated with the dream, as input by the user.
5- Sentiment Analysis - Analyzes the dream description to determine whether the overall sentiment is positive, negative, or neutral.
6- Sentiment Bar Visualization -Provides a visual bar chart showing the percentage of positive and negative words in the dream, complete with percentage labels for clarity.
7- Dream Categorization -Classifies the dream into categories (e.g., Adventure, Nightmare, Fantasy) based on specific keywords found in the description.
8 - Past Dream Storage and Display - Stores past dreams locally and displays them in a list format, allowing users to review and reflect on their previous entries.
9- Reset Functionality -Includes a reset button to clear the form and all results, making it easy to start a new analysis.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/145869907/2e7e283a-ccc7-45bd-a171-565bacc41ac8

@Rakesh9100 sir, please take a look.

### CODE REVIEW

**Comment by Nihal4777** [comment]
@ananyag309 Can you please fix the responsiveness issue,
image

**Comment by ananyag309** [comment]
@Nihal4777 sir please check and let me know if its working or need more changes

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed and can be merged.

**Comment by Rakesh9100** [comment]
After Analyzing a dream, if I refresh the page or open that web page again then the page should open newly, and no past dreams should be visible, pls fix @ananyag309

**Comment by ananyag309** [comment]
@Rakesh9100 sir I have removed the past dream section from the code. Please check and let me know if any further changes are required.

**Pull request merged**
