### PR TITLE
Added Cuban Prime Calculator

### LINKED ISSUE #595: [Feature] Add Cuban Prime Calculator
### Description

A cuban prime is a [prime number](https://en.wikipedia.org/wiki/Prime_number) that is also a solution to one of two different specific equations involving differences between third powers of two integers x and y.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️ #595 

Closes #595 

# Description👨‍💻 

Added cuban prime number calculator

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Cuban

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Rakesh9100** [comment]
1. Add 1-2 lines about Cuban Prime and its formula below the heading.

2. Show the solution process of the number which is Cuban when it is checked @AftabMankapure

**Comment by AftabMankapure** [comment]
check now i update it

**Comment by AftabMankapure** [comment]
@Rakesh9100  pls check this PR now

**Comment by Rakesh9100** [comment]
When we are finding the cuban prime numbers in a range, the result should only show all the prime numbers and not the solutions of all.

Solutions should only be shown when we are checking a number for cuban @AftabMankapure

**Comment by Rakesh9100** [comment]
When we are finding the cuban prime numbers in a range, the result should only show all the numbers and not the solutions of all.

Solutions should only be shown when we are checking a number for cuban @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  it is not possible to show solution for all number in range

**Comment by Rakesh9100** [comment]
Read the comment properly @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100 
pls check this now , now it ok as per required 

newCuban

**Comment by Rakesh9100** [comment]
Merged 🎉 @AftabMankapure

**Pull request merged**
