### PR TITLE
SGPA Calculator UI Enhanced

### PR DESCRIPTION
**Pull request by krishnagitcontri**
Fixes Issue🛠️
Closes :[UI Changes in SGPA Calculator](https://github.com/Rakesh9100/CalcDiverse/issues/61#top)
#61

Description👨‍💻
In this pull request, I addressed the following changes to enhance the SGPA Calculator's user interface:
- Added space between the previous CGPA and previous credits for improved readability.
- Changed the background to a neomorphic design to enhance the overall visual appeal.

Type of change📄
Added Space between the Previous cgpa nd previous credits and changed background to neomorphism

Checklist✅
[] My code follows the style guidelines of this project
[] I have performed a self-review of my own code
[] I have commented my code, particularly in hard-to-understand areas
[] I have added demonstration in the form of GIF/video file
[] I am an Open Source Contributor
Screenshots/GIF📷

sgpa changes
Now

### CODE REVIEW

**Comment by krishnagitcontri** [comment]
UI Changes in SGPA Calculator #61
Screenshot 2024-01-02 221841
Previous 
sgpa changes
Now

**Comment by krishnagitcontri** [comment]
@Rakesh9100 I have made the changes in SGPA with added Neomorphism in Background Please let me know me your comments and any FeedBack.

**Comment by Rakesh9100** [comment]
Pls use the proper PR template and edit the PR description @krishnagitcontri

**Comment by krishnagitcontri** [comment]
Fixes Issue🛠️
No negative inputs

Closes https://github.com/Rakesh9100/CalcDiverse/issues/133

Description👨‍💻
resolved negative input issue which makes the resultant bmi negative and height weight and bmi can't be negative

Type of change📄
[] Bug fix (non-breaking change which fixes an issue)
How this has been tested✅
Converted the input values to numbers using parseFloat.
Added checks using isNaN and ensured that the values are greater than zero for both height and weight.
If the values are not valid, display an alert, clear the input fields, and exit the function.

Checklist✅
[] My code follows the style guidelines of this project
[] I have performed a self-review of my own code
[] I have commented my code, particularly in hard-to-understand areas
[] I have added demonstration in the form of GIF/video file
[] I am an Open Source Contributor
Screenshots/GIF📷

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @krishnagitcontri

**Pull request merged**
