### PR TITLE
Implemented Multilingual support

### LINKED ISSUE #873: [Feature] Add multilingual support to the website
### Description

On exploring the CalcDiverse, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.

### Screenshots

The below image of the website represents that it is only available in English language
WhatsApp Image 2024-05-25 at 16 06 32_c5244dce

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anjankumarkamalapur**
# Fixes Issue🛠️

Fixes #873 

# Description👨‍💻 

Multilingual support is enabled.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

image

### CODE REVIEW

**Comment by Anjankumarkamalapur** [comment]
@Rakesh9100 Done with Implementing Multilingual support. Once check it out. Thank you.

**Comment by Rakesh9100** [comment]
Pls check your PR deploy preview, your changes are not visible! @Anjankumarkamalapur 

https://deploy-preview-984--calcdiverse.netlify.app/

**Comment by Anjankumarkamalapur** [comment]
can u pls check it now.

https://github.com/Rakesh9100/CalcDiverse/pull/1016

**Comment by Rakesh9100** [comment]
Your code is already added but still not visible, don't create any more PR now @Anjankumarkamalapur

**Pull request closed without merging**
