### PR TITLE
Added scroll progress indicator bar

### LINKED ISSUE #1695: [Feature] Add scroll progress indicator bar
### Description

On this website, the scroll-down progress bar is absent on home page while present on all the page

image

### Screenshots

i would like to add the below progress bar.

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Fixes Issue🛠️

Closes #1695 

# Description👨‍💻

A progress bar is a visual representation of the completion status of a task or process. It typically consists of a horizontal bar divided into segments, with each segment representing a portion of the total progress. The length of the filled portion of the bar corresponds to the completed percentage.

# Type of Change📄

- [X] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

https://github.com/user-attachments/assets/ddade299-1265-483b-a0d5-4c2da70f0569

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Nihal4777** [comment]
@Rakesh9100 PR looks good but issue is not assigned.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please merge this if u like it , if any changes pls do mention.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please merge this if u like it , if any changes pls do mention.

**Comment by Rakesh9100** [comment]
Please also include it on every other page such as About, Contributors, etc. @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the changes and merge it.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Rakesh9100** [comment]
The scroll to top button is distorted, pls fix @Anjaliavv51 
image

Also, progress bar is still not added in FAQ and Contact page, you can check the deploy preview or your local files and then make the proper commits @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR.

**Pull request closed without merging**
