### PR TITLE
Added Special Number-2 Calculator

### LINKED ISSUE #1282: [Feature] Add Special Number-2 Calculator
### Description

Addition of Special Number Calculator. This will show whether the input number is a special number or not.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shreya-paul-17**
# Fixes Issue🛠️

Closes #1282 

# Description👨‍💻

Special Number calculator added

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

ss-5

### CODE REVIEW

**Comment by Nihal4777** [comment]
@shreya-paul-17 Please add empty field validations.
image

**Comment by Rakesh9100** [comment]
Are you working @shreya-paul-17

**Comment by shreya-paul-17** [comment]
@Rakesh9100 another person has included a special number calculator but with a different logic. It is continuous conflicting with my files. How to resolve these?

**Comment by Rakesh9100** [comment]
You can rename your calculator folder to `Special-Number-2-Calculator` and make the necessary changes by making the new commits in this same PR @shreya-paul-17

**Comment by shreya-paul-17** [comment]
There were some issues that were still existing in the current branch. So I created a new branch. Thus I created a new PR #1659 . @Rakesh9100 please check that PR.

**Pull request closed without merging**
