### PR TITLE
Added Midpoint Calculator

### LINKED ISSUE #1171: [Feature] Add Midpoint Calculator
### Description

A midpoint calculator is a tool used to find the exact center point between two given points in a Cartesian coordinate system. The midpoint is useful in various mathematical contexts, such as geometry, algebra, and calculus.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Damini2004**
# Fixes Issue🛠️

Closes #1171 

# Description👨‍💻 

A web-based midpoint calculator where there are 4 input fields consist of x1, x2, y1, y2.
User have to fill this value in order to get mid-point.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested as per several inputs in order to get midpoint of the axis.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-06-07 021319

### CODE REVIEW

**Comment by Damini2004** [comment]
@Rakesh9100 Review the PR.

**Comment by Rakesh9100** [comment]
After Calculating, if I am refreshing the page let's say then also the previous calculated value is showing, pls fix @Damini2004

**Comment by Damini2004** [comment]
@Rakesh9100 Changes added.

**Comment by Rakesh9100** [comment]
Use any good background image and not blurry one, also handle NaN value when we click on Calculate without filling any value @Damini2004

**Comment by Damini2004** [comment]
Should i add required in order to fill any digit in order to avoid the NaN.

**Comment by Rakesh9100** [comment]
Yes, you can provide the alert to Fill every value to calculate the midpoint @Damini2004

**Comment by Damini2004** [comment]
@Rakesh9100 Added Changes

**Comment by Rakesh9100** [comment]
image

### Main content is out of the screen, reduce the top and bottom margin and align the content to center of the screen @Damini2004

**Comment by Damini2004** [comment]
Decrease margin more ??

**Comment by Rakesh9100** [comment]
Check the deploy preview and make the changes accordingly so that UI looks good and properly aligned @Damini2004

**Comment by Damini2004** [comment]
@Rakesh9100 Did the changes

**Pull request merged**
