### PR TITLE
Added Curve Fitting Calculator

### LINKED ISSUE #962: [Feature] Add Curve Fitting Calculator
### Description

Greetings @Rakesh9100,
I propose to create a calculator that aims to provide the best-fitting curve (straight line, quadratic, cubic, exponential, etc.) of a given set of points or coordinates using regression libraries and other functions.
Please assign this issue to me under Gssoc24. I look forward to working with you and contributing towards your organization.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by DivyaVijay1234**
# Fixes Issue🛠️

Closes #962

# Description👨‍💻 

This code implements a curve-fitting calculator in JavaScript. It allows users to input a set of 2-D coordinates and choose from various curve-fitting options, including linear, quadratic, cubic, and exponential curves. The calculator uses mathematical algorithms to determine the best-fitting curve based on the input points and displays the equation of the curve along with a graph. This tool can be useful for analysing data trends and predicting values based on given data points.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
During the testing phase, I rigorously evaluated the curve-fitting calculator by inputting data sets of various sizes and characteristics, covering linear, quadratic, cubic, and exponential curve types. By analyzing the calculated equations against the provided points, I ensured that the calculator accurately determined the best-fitting curve for each dataset. Additionally, I verified the user interface's functionality to guarantee seamless interaction, allowing users to input data, select curve types, and obtain precise curve-fitting results. Through these comprehensive tests, I confirmed the calculator's robustness and reliability across diverse curve-fitting scenarios.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-06-04 233800
Screenshot 2024-06-04 234211

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your calculator in main `index.html` file to display on the website by making a new commit in this same PR @DivyaVijay1234

**Comment by DivyaVijay1234** [comment]
@Rakesh9100 
Just a quick question. Should I be merging this with the main branch before adding it to the index.htm l file? Or should the link of the code contain the link from my forked repository?

**Comment by DivyaVijay1234** [comment]
@Rakesh9100 
I had previously added my calculator in a separate branch. Do I need to merge it with the main branch before being able to add it to the main website?

**Comment by Rakesh9100** [comment]
No, you don't have to merge anything. You just have to add your calculator part in main `index.html` file in the branch Curve-Fitting-Calculator and then commit it @DivyaVijay1234

**Pull request merged**
