### PR TITLE
Added AP and GP Calculator

### LINKED ISSUE #224: Addition of AP and GP Calculator
### Description

It will allow user to calculate the sum of terms, given the first term, common difference, and number of terms in the given Arithmetic Progression(AP) or Geometric Progression(GP).

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Dhairya1Gupta**
# Fixes Issue🛠️

Closes #224 

# Description👨‍💻 

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

1. Calculates nth Term and sum of n Terms present in an Arithmetic Sequence.
2. Calculates nth Term and sum of n Terms present in an Geometric Sequence.

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these:

1. Rename your folder to `Arithmetic-Progression-Calculator` and `Geometric-Progression-Calculator` respectively and then make your changes in main `index.html` wherever required.
2. Add a Readme.md file to both your folders.
3. Resolve the conflicts @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
Pls work on these:

1. Rename your folder to `Arithmetic-Progression-Calculator` and `Geometric-Progression-Calculator` respectively and then make your changes in main `index.html` wherever required.
2. Add a Readme.md file to both your folders.
3. Mention the issue number this PR closes.
4. Resolve the conflicts @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
Pls add screenshots of the calculator to both the Readme respectively and also to the PR description @Dhairya1Gupta 

Mention the issue number this PR closes!

**Comment by Dhairya1Gupta** [comment]
OK done! Please review changes and merge PR @Rakesh9100

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @Dhairya1Gupta

**Pull request merged**
