### PR TITLE
Added Centroid Of A Triangle Calculator

### LINKED ISSUE #1488: [Feature] Add Centroid Of A Triangle Calculator
### Description

This calculator aims to find centroid of a triangle 

# Importance of centroid
1. Centroid divides each median in a 2:1 ratio.
2. Centroid is the center of mass or balance point of the triangle.
3. The centroid is the intersection point of the three lines that divide the triangle into three equal areas.

# Used in:
1. Mechanics:
2. Geometry
3. Engineering

### Screenshots

# Note:
Here A,B,C are the three vertices of a triangle
Point G  is the centroid of that triangle

Screenshot 2024-06-28 164857

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SumithThota**
# Fixes Issue🛠️

Closes #1488 

# Description👨‍💻

Triangle Centroid Calculator added successfully.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-07-06 174059

### CODE REVIEW

**Comment by Nihal4777** [comment]
@SumithThota Can you make it little responsive for mobile devices.
image

**Comment by SumithThota** [comment]
@Nihal4777 ok sure

**Comment by SumithThota** [comment]
@Nihal4777 @Rakesh9100 I have updated the work by making the website more resoponsive for mobile devices
once check it and add appropriate labels to it
# Check this video for more info: 
https://github.com/Rakesh9100/CalcDiverse/assets/108344062/ddb3c153-b394-4d8f-af3b-96b197864c14

**Comment by Rakesh9100** [comment]
Rename your calculator folder to `Centroid-Of-A-Triangle-Calculator` and make the necessary changes by making the new commits in this same PR @SumithThota

**Comment by SumithThota** [comment]
@Rakesh9100 Yes I renamed the calculator to ```Centroid-Of-A-Triangle-Calculator```  Once check it 


Screenshot 2024-07-11 163909

**Comment by Rakesh9100** [comment]
I told to rename your folder and then make changes to necessary files @SumithThota

**Comment by Rakesh9100** [comment]
### Why these extra codes are present unnecessarily, it seems you have just copied the full code from anywhere @SumithThota 

image

**Comment by SumithThota** [comment]
@Rakesh9100 I have Updated the code and one more thing is 
I kept those code becoz to know the id and class names easily over in the file(Script.js) anyhow i removed those in these commit

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can be merged.

**Comment by Rakesh9100** [comment]
Can you check the [Deploy preview](https://deploy-preview-1548--calcdiverse.netlify.app/calculators/centroid-of-a-triangle-calculator/) once as output diagram is not showing properly @SumithThota

**Comment by SumithThota** [comment]
Is is okay @Rakesh9100 
image

**Comment by SumithThota** [comment]
@Rakesh9100 please let me know why you have still not merged this PR

**Pull request merged**
