### PR TITLE
Added Z-Score Calculator

### LINKED ISSUE #1538: [Feature]  Z test Calculator
### Description

Z-test calculator is a tool that helps you perform a one-sample Z-test on the population's mean. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
# Fixes Issue🛠️

Closes #1538 

# Description👨‍💻

A Z-score calculator is a versatile tool designed to compute the Z-score for a given data point, enabling quick and precise analysis of its relative position within a dataset.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-07-16 231654

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Khushi-Pushkar** [comment]
> Reference in

Hey @Nihal4777 sir , Could you please contact the project admin to merge this issue? It's been pending for 2 week now.

**Comment by Nihal4777** [comment]
Hii @Khushi-Pushkar, Thank you so much for your contribution.
We really apologize for the delay caused. Don't worry your PR will get reviewed very soon.

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 sir please merge asap

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 please merge asap

**Pull request merged**
