### PR TITLE
Added character count field in Contact page

### LINKED ISSUE #1704: [Feature] Add character count field in Contact page
### Description

Hello PA,
In Contact Us page at Message Field I will add text like saying minimum character count should be 50 and also a bar which counts the characters when user enters a character so that user will be comfortable in reaching the minimum criteria . I think it will be good rather that pop-up message.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Vaishnavigunti2801**
# Fixes Issue🛠️
 

Closes #1704 

# Description👨‍💻

I added a new feature, In Contact Us page when the user enters a message then the characters will be counted. When the characters are less than 50 the message will be red and when the number of characters are greater than are equal to 50 the message color change to green.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### Before:
image

### After:
image
image
image

### CODE REVIEW

**Comment by Vaishnavigunti2801** [comment]
@Rakesh9100 
Please check my work.
Thank You.

**Comment by Nihal4777** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
We already have the alert saying `Your message must be at least 50 characters long.`, why do we need this extra count feature @Vaishnavigunti2801

**Comment by Rakesh9100** [comment]
We already have the alert saying `Your message must be at least 50 characters long.`, why do we need this extra count feature @Vaishnavigunti2801

**Comment by Vaishnavigunti2801** [comment]
@Rakesh9100 
By adding a feature like counting message makes user easily understand the characters limit reached or not . If it is not there user always have to check whether the message is 50 characters long or not by clicking on submit button. I added a color feature to the message count in which if the count is less than 50 it is marked with red otherwise green which makes user comfortable to check the limit.

**Pull request merged**
