### PR TITLE
NaN handling in currency converter calculator

### PR DESCRIPTION
**Pull request by SaranshBangar**
# Fixes Issue🛠️

Closes #31 

# Description👨‍💻 

I have addeda small "if" statement which checks if the user input is valid or not, if it is not valid, then it prompts the user to correct the input

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

The updated code works on all screen sizes, moreover it works on all the datatypes

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Edit the PR title and give similar to the work you have done @SaranshBangar

**Comment by Rakesh9100** [comment]
You should not give this long PR title from next time @SaranshBangar I am editing this time

**Comment by SaranshBangar** [comment]
Sorry sir, I will take care of it in the future

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to this repo under SWOC S4 🎉 @SaranshBangar

**Comment by SaranshBangar** [comment]
Thank you sir

**Pull request merged**
