### PR TITLE
Added Fractal Generator Calculator

### LINKED ISSUE #1484: [Feature] Add Fractal Generator Calculator
### Description

A Fractal Generator Calculator is a tool that allows users to create and visualize complex geometric patterns known as fractals. Here’s a brief overview of its input and output:

Input:

Fractal Type: Selects the type of fractal to generate (e.g., Mandelbrot set, Julia set).
Parameters: Adjusts parameters specific to the selected fractal type (e.g., scaling factor, rotation angle).
Resolution: Sets the resolution or detail level of the fractal image.

Output:

Fractal Image: Generates a visual representation of the selected fractal.
Interactive Exploration: Allows users to zoom in/out and navigate through different parts of the fractal for detailed exploration.
Color Palette: Optionally, applies color schemes to enhance visual appeal and distinguish different elements of the fractal.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ananyag309**
# Fixes Issue🛠️

Closes #1484 

# Description👨‍💻

Added fractal generator calculator, it is a web-based calculator that allows users to create and visualize complex geometric patterns known as fractals. This tool supports different types of fractals, including the Mandelbrot Set and the Julia Set. Users can customize various parameters, set the resolution, and choose different color palettes to generate beautiful and intricate fractal images.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

fractral

https://github.com/user-attachments/assets/2a084dc8-dd45-4e02-ae99-4776d5a5f770

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Is there any difference in the outputs of both the sets as I can't see any @ananyag309

**Comment by ananyag309** [comment]
@Rakesh9100 I have separated formula for both sets so that it doesn't happen
fractal 1
fractal 2

**Comment by ananyag309** [comment]
Uploading WhatsApp Video 2024-07-13 at 12.42.16_59ca09b3 (1).mp4…

**Comment by ananyag309** [comment]
https://github.com/user-attachments/assets/dd0d7435-60a0-487f-a23f-bfca5c417e04

**Pull request merged**
