### PR TITLE
Mass conversion calculator

### LINKED ISSUE #22: I want to add Mass Converter in the calculator App
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  I want to add mass converter basically converts that kilo to gram ,miligram etc. please assign this issue to me

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by kumar007ambi**
# Fixes Issue🛠️

Closes #22 

# Description👨‍💻 
I have added mass conversion calculator in main calulator

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [✔] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [✔] My code follows the style guidelines of this project
- [✔] I have performed a self-review of my own code
- [✔] I have commented my code, particularly in hard-to-understand areas
- [✔] I have added demonstration in the form of GIF/video file
- [✔] I am an Open Source Contributor

# Screenshots/GIF📷
Weight Converter

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add a `README.md` in your folder and also add your calculator section in main `index.html` file @kumar007ambi

**Comment by kumar007ambi** [comment]
@Rakesh9100 how can i add the screenshot image in the readme,md file

**Comment by Rakesh9100** [comment]
Just copy your image and paster in your README file or drag and drop the image to your README. Also attach screenshots to this PR @kumar007ambi

**Comment by Rakesh9100** [comment]
Just copy your image and paste in your README file or drag and drop the image to your README. Also attach screenshots to this PR @kumar007ambi

**Comment by Rakesh9100** [comment]
Good, merged!! Congrats on getting your PR merged to the repo under SWOC S4 🎉 @kumar007ambi

**Pull request merged**
