### PR TITLE
Fixed Issue #107 and Issue #108

### LINKED ISSUE #107: Enhancing heading (Calcdiverse) for making website mobile responsive
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The h1 ("CalcDiverse") is exceeding the main container and making it unresponsive in mobile devices. The padding and font size is exceeding the inner div and is exceeding width beyond the main container, which is leading in design flaw and making is unresponsive for mobile devices

### Screenshots

Cd_mob

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by pb0126**
# Fixes Issue🛠️

Closes #107 & #108

# Description👨‍💻 

Issue #107 
The mail heading "Calcdiverse" font was exceeding the main container making it unresponsive on mobile screen. I have made the changes in overall padding and font size to make it mobile responsive. In addition to that I have updated the media queries as well, so that it doesn't conflict with the real code.

Issue #108 

The "2D Shapes Calculator" card on the mobile screen overlapped the "Explore Calculator" Button. I have made fixes by reducing the padding around the cards div and paragraph div and also added margin to the container in the media screen so that it works normally on all the screens and maintains the responsiveness of the website
# Type of change📄

# How this has been tested✅

I have checked the website after fixes via Chrome developer tools making various checks with all types of screens available. The fixes pass every screen parameter and maintain responsiveness.

# Checklist✅ 

- [x]  My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have added demonstration in the form of GIF/video file

- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Before: 

Issue #107 
Cd_mob

Issue#108
cd_mob_overlap

After changes:-

Issue #107
image

Issue#108
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @pb0126

**Comment by Rakesh9100** [comment]
image

Pls reduce the font size of this @pb0126

**Comment by pb0126** [comment]
> image
> 
> Pls reduce the font size of this @pb0126

Can you please specify the screen size I need to reduce the font size or for every screen?

**Comment by Rakesh9100** [comment]
Only landing page has that text that is below the logo and nowhere else @pb0126

**Comment by pb0126** [comment]
> Only landing page has that text that is below the logo and nowhere else @pb0126

The changes has been made and committed to the repo, please check the code and merge the pull request.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @pb0126

**Pull request merged**
