### PR TITLE
Added Prayer Time Calculator

### LINKED ISSUE #1185: [Feature] Add Prayer Time Calculator
### Description

 a simple location based prayer time calculator that tells the exact time of prayer including sunset and sunrise 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by samarsajad**
# Fixes Issue🛠️

Closes #1185 

# Description👨‍💻

A simple prayer time calculator that uses user's location to calculate the prayer timing.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Rakesh9100

**Comment by samarsajad** [comment]
Can you please review my pull request so that i can work on other issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls add your calculator folder inside `Calculators` folder and make the necessary changes by making the new commits in this same PR @samarsajad

**Comment by Rakesh9100** [comment]
image

### Why location is undefined, and do this application use our location or uses the inputs given by the user @samarsajad

**Comment by samarsajad** [comment]
It uses the person's location. I couldn't solve the location undefined part. It takes user's input as well but also uses location @Rakesh9100

**Comment by Rakesh9100** [comment]
Either it will use our input or the location that the user allows to the browser, so see to this and also try to fix the undefined part @samarsajad

**Comment by samarsajad** [comment]
The API I used had a parameter for city & Country. So I put those. But it also asks for the location when we use it. Can you please help me figure out what I am missing in this cause I tried so hard to figure out this undefined location part & didn't succeed @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay, I will look over that bug afterward whenever I am free @samarsajad

**Pull request merged**
