### PR TITLE
Added Eye Power Calculator

### LINKED ISSUE #1423: [Feature] Add Eye Power Calculator
### Description

I will create a eye power calculator in which right eye power and left eye power are inputted from user and total eye power is calculated.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SHANMUGAPRIYA-1**
# Fixes Issue🛠️

Closes #1423 

# Description👨‍💻

An Eye Power Calculator is a valuable tool for anyone needing to determine the strength of their prescription lenses. By inputting the diopter values from their lens prescription, users can quickly and accurately calculate the eye power required for their corrective lenses. This tool is especially useful for verifying prescription accuracy before purchasing glasses or contact lenses, ensuring that the lenses will provide the correct vision correction. Additionally, it helps individuals understand the extent of their vision correction needs, promoting better eye health awareness. The Eye Power Calculator offers a user-friendly and efficient solution, making it accessible for anyone to use at any time, whether at home or on the go. Its simplicity and accuracy make it an essential resource for both optometrists and individuals who wear corrective lenses, providing a convenient and reliable method to determine the necessary lens power for optimal vision.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-30 180403

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You are just adding the power and showing. Instead, add two dropdowns and put some required power values from which user can choose and then based on that, you can show which lens power would be required for both the eyes @SHANMUGAPRIYA-1

**Comment by Rakesh9100** [comment]
Are you working or Should I close this PR @SHANMUGAPRIYA-1

**Comment by SHANMUGAPRIYA-1** [comment]
Yes, I am working.

**Comment by SHANMUGAPRIYA-1** [comment]
Sir i had made changes to this project

**Pull request merged**
