### PR TITLE
Added Luminous Flux Calculator 

### LINKED ISSUE #1624: [Feature] Add Luminous Flux Calculator
### Description

A Luminous Flux Calculator calculates the total visible light emitted by a source, measured in lumens (lm). This is useful for understanding the brightness of light sources, such as LEDs, bulbs, or any other lighting fixtures. The calculation takes into account the luminous efficacy of the light source and the power consumed.

### Screenshots

image
image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by TBorundia**
# Fixes Issue🛠️

Closes #1624 

# Description👨‍💻

Added Luminous Flux Calculator that matches the theme of the website as well as calculator.
Made it responsive too.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

https://github.com/user-attachments/assets/38e42960-d9aa-4ae5-95c7-0f7a01d62a90

image

### CODE REVIEW

**Comment by TBorundia** [comment]
@Rakesh9100  @Nihal4777  Sir,
Please review this PR as soon as possible as GSSoC'24 contribution is closing soon.
Thank you!

**Comment by Rakesh9100** [comment]
image

### Please ensure that no other file changes appear in this PR. Fix this issue without closing the PR @TBorundia

**Comment by TBorundia** [comment]
@Rakesh9100 Sir, 
I have made the changes , Now please review this PR.

**Comment by TBorundia** [comment]
@Rakesh9100 ,
I have made the changes , Please review this PR.

**Comment by Nihal4777** [comment]
@TBorundia Don't worry. Coding period has been extended for 10 days.

**Pull request closed without merging**
