### PR TITLE
Added Unique Prime Number Calculator

### LINKED ISSUE #1095: [Feature] Add Unique Prime Number Calculator
### Description

A "unique prime" is a prime number that remains prime when any single digit is removed from it. 
I can add an unique prime number calculator 
1. It can tell if a number is an unique prime number or not
2. It can print all the unique prime numbers in a given range

### Screenshots

_No response_

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by bharat-c27**
# Fixes Issue🛠️

Closes #1095 

# Description👨‍💻

The Unique Prime Number Calculator is a web-based tool designed to identify and work with unique prime numbers. A unique prime number is a prime number that remains prime even after removing any single digit from it.

**Features** :

Prime Check: Enter a number to determine if it is a unique prime. The calculator checks if the number is prime and if all resulting numbers from removing any single digit are also prime.

Range Finder: Input a range of numbers to find all unique prime numbers within that range. The tool will display all unique prime numbers that satisfy the conditions within the specified range.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-07-09 230841

### CODE REVIEW

**Comment by Nihal4777** [comment]
@bharat-c27  Please add empty field validations.
image

**Comment by bharat-c27** [comment]
Sure @Nihal4777, I will add the validation.

**Comment by bharat-c27** [comment]
Hello @Nihal4777, I have added the validation for both, finding unqiue number and for finding range also.
I am done with the validation, can you please review and assign me the labels 

Thank you!!!

**Comment by Rakesh9100** [comment]
### Pls work on these @bharat-c27 

#### 1. Add 1-2 lines proven explanation below the text, for example `23 is a unique prime number.` of why and how a number is a unique number and same for non-unique number.
#### 2. If I find the unique numbers in range 1 to 10000000, then the page is not fully scrollable.

**Comment by bharat-c27** [comment]
Sure @Rakesh9100 I will work on the layout.

But for issue 1 : if the number is 12345678 then if I try to explain why the number is unique prime or not. Then the UI will look messy, because it will require me to explain every digit

**Comment by Rakesh9100** [comment]
Make the UI responsive for the small screens @bharat-c27

**Comment by bharat-c27** [comment]
@Rakesh9100 can you please provide a photo or a video, for which screen size the calculator is not responsive ?

In the below video the UI is looking responsive

https://github.com/user-attachments/assets/1ee35fb0-6b58-4f5c-ae74-01a9cd557b47

**Comment by Rakesh9100** [comment]
Pls check for the screen size less than 450px @bharat-c27

**Comment by bharat-c27** [comment]
@Rakesh9100 now the calculator is responsive for screen size less than 450px .

**Comment by bharat-c27** [comment]
> @Rakesh9100 now the calculator is responsive for screen size less than 450px .
> 
> If there are no further modification can you assign me the issue #1317, I am done with the coding part. Only I have to raise the PR.

@Rakesh9100, can you please assign me the issue

**Pull request merged**
