### PR TITLE
Implemented search result suggestion

### LINKED ISSUE #875: [Feature] Implement search result suggestion
### Description

- In this project `Enter Calculator Name` search box calculator name give that has been suggest the `calculator` names.
- Example :  

### Screenshots

[Screencast from 2024-05-12 08-10-53.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/efcadc0b-8489-40f7-b35b-94ed18c7b182)

- please assign me .
- I will ready for work..

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Fixes Issue🛠️

Closes #875 

# Description👨‍💻

- Implemented for the search by the user for available calculators.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

[Screencast from 2024-06-04 18-18-13.webm](https://github.com/Rakesh9100/CalcDiverse/assets/121082414/26c68f6b-408d-4c28-9676-aac6fd6190a9)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Let's suppose I am searching base, then out of suggestions if I click the first result or any result then it should collapse and that calculator should only show @sivaprasath2004

**Comment by sivaprasath2004** [comment]
@Rakesh9100 , If we will search for the `s` available calculators, if we will suggest for the calculator name easy to user for selecting. 
Example for the `s` result can be `30+` calculator can be availble, we will not use the suggestion availble calculator name user can be  find to scroll the page it is time wasting for the user,  what do you to want calculates then  `Calculator name` easy to use it.
This is can be futuristic implementations...

**Comment by Rakesh9100** [comment]
If I am searching graph, why these many suggestions are coming, even though graph word is not included in many of the suggestions @sivaprasath2004 

image

**Comment by sivaprasath2004** [comment]
In this suggestion working was `.inclues` method so the `Graph` include the name can be suggest please check for the all name include the `graph` word . @Rakesh9100

**Comment by Rakesh9100** [comment]
Just show the specific results so that `gra` shows all the gra included results and `graph` includes only the graph containing names @sivaprasath2004

**Comment by sivaprasath2004** [comment]
Hello @Rakesh9100, i will fixed it.. :rocket:

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-06-15 19-47-02.webm](https://github.com/Rakesh9100/CalcDiverse/assets/121082414/1fdbd9b1-fd54-402f-a9fc-6c30cc0932d0)

**Pull request merged**
