### PR TITLE
Added Date and Time Calculator

### LINKED ISSUE #453: [Feature] Date and Time Calculator
### Description

This tool will enable users to effortlessly calculate past or future dates and times. With a clean interface, dynamic heading updates, and responsive design, users can input a numerical value and select a time period to obtain accurate and formatted results. The output includes detailed information such as weekday, year, month, day, hour, minute, and second, providing a user-friendly experience for various date and time calculations.

### Screenshots

image
image
image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Description👨‍💻 

This Date & Time Calculator is a simple online tool that effortlessly calculates the difference in years, months, weeks, days, hours, minutes, and seconds from the current date and time.

# Fixes Issue🛠️

- Closes #453 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have done Alpha, Beta & Unit Testing

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image
image
image

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100  This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the "JWOC" and "Difficulty" labels to this pull request.

**Comment by Rakesh9100** [comment]
Pls fix the issue we are getting in my project `Click-The-Edible-Game` after your PR of drag and drop was merged, so fix it ASAP and then this PR will be reviewed!! @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Sure! I'll Fix it.

**Comment by antilneeraj** [comment]
@Rakesh9100 do I have to create another issue for that or I can directly contribute by pushing a new PR ?

**Comment by Rakesh9100** [comment]
You should create a new issue always and then PR to resolve that issue @antilneeraj

**Comment by Rakesh9100** [comment]
Good one, Merged ✨ @antilneeraj

**Pull request merged**
