### PR TITLE
Fixed Contact form Validation

### LINKED ISSUE #366: [Bug] Contact form Validation issue
### Description

Validation issue in Contact form while sending message. When we enter numbers in place of username it is accepting.

### Describe the change you think might work

we can restrict this by typing valid user name (characters ) in username field.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by student-aditipaliwal**
# Fixes Issue🛠️

Closes #366 

# Description👨‍💻 

when a user enters numbers in name field the it was getting accepted, but After form validation It only accepts the characters. If numbers are entered, An Alert is popped up saying Numbers are not allowed!

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

We ran this code on our editor & reviewed it twice, it's working fine.

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷

#Before

Screenshot (1)

#After
Screenshot (2)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls follow the PR template and edit the PR description accordingly @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
Okay! @Rakesh9100

**Comment by student-aditipaliwal** [comment]
Done! @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls mention issue number this PR closes in PR description not the PR number @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
issue no : 413

**Comment by student-aditipaliwal** [comment]
sorry the issue no . is : 366 contact form validation

**Comment by Rakesh9100** [comment]
Why is it still submitting the form after clicking the OK of the alert box @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
ok i will correct it and bring it to you tomorrow

**Comment by Rakesh9100** [comment]
> Why is it still submitting the form after clicking the OK of the alert box @student-aditipaliwal

Have you corrected this, complete it by today else you will be unassigned @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
Yes, it's done. and I have again make a pull request for it

**Comment by Rakesh9100** [comment]
> Yes, it's done. and I have again make a pull request for it

Where is your PR @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
sir I have created new pr for that on yesterday or on 25with the updated
codes please check

**Comment by Rakesh9100** [comment]
No PR of yours is visible, can you specify the PR number @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
sir actually i have created a new commit for that as name update
contact.html

**Pull request closed without merging**
