### PR TITLE
Added Blood Pressure Calculator

### LINKED ISSUE #1239: [Feature] Add Blood Pressure Calculator
### Description

This project is a simple Blood Pressure (BP) Calculator implemented using HTML, CSS, and JavaScript. The calculator allows users to input their systolic and diastolic blood pressure readings, and it provides an interpretation of those readings based on standard blood pressure categories.
Label it as gssoc and level 3

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Fixes Issue🛠️

Closes  #1239 

# Description👨‍💻 

Added Blood Pressure Calculator where the user can Know their blood pressure.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/143107589/1df88acd-de4b-46c5-b849-c25c6c2c7acc

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
please label the issue as  gssoc level 3

**Comment by Rakesh9100** [comment]
Please do not create a PR until you have been assigned to an issue @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 the issue was created by me

**Comment by Saipradyumnagoud** [comment]
> Please do not create a PR until you have been assigned to an issue @Saipradyumnagoud

can you please assign me now i dont repeat it next time

**Comment by Rakesh9100** [comment]
Work on these @Saipradyumnagoud 

1. Rename your folder to `Blood-Pressure-Calculator` and make the changes accordingly and push the commits in this same PR.
2. Add the Readme file of your calculator in your folder.
3. Enhance the UI as well.

**Comment by Saipradyumnagoud** [comment]
> Work on these @Saipradyumnagoud
> 
> 1. Rename your folder to `Blood-Pressure-Calculator` and make the changes accordingly and push the commits in this same PR.
> 2. Add the Readme file of your calculator in your folder.
> 3. Enhance the UI as well.

Made the changes

**Pull request merged**
