### PR TITLE
Added Basic Physics Calculator

### LINKED ISSUE #1081: [Feature] Add Basic Physics Calculator
### Description

Hello Project Admin @Rakesh9100,
Adding Basic Physics Calculator to CalcDiverse, enables users to calculate basic physics quantities like speed, acceleration, velocity, force, power, pressure, etc. It can be provided with functionality where there is a side navbar for navigating what kind of operation should take place with the appropriate parameter. Based on this information, the calculator will provide an estimated answer for the operation chosen.

I've already worked with CalcDiverse and imposed a calculator before and I want to contribute further to this amazing repository.

@Rakesh9100 Can you assign me this project, I would like to work on this Calculator.
Also, this calculator can be a one-stop solution for calculating basic physical quantities easily. So, this is a very helpful calculator.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by kamalesh-og**
# Fixes Issue🛠️

Closes #1081 

# Description👨‍💻 

This pull request introduces the Basic Physics Calculator to enhance the CalcDiverse repository. This calculator includes functionalities to compute various basic physics quantities:

- Speed Calculation: Calculates speed given distance and time inputs.
- Acceleration Calculation: Computes acceleration based on initial and final velocities and time.
- Force Calculation: Determines force using mass and acceleration inputs.
- Pressure Calculation: Calculates pressure from area and force inputs.
- Work Calculation: Computes work based on force and distance inputs.
- Power Calculation: Determines power using energy and time inputs.
- Kinetic Energy Calculation: Computes kinetic energy using mass and velocity inputs.

Each calculator section is styled with a clean card interface for user inputs and results, ensuring clarity and ease of use. The design maintains consistency with the existing CalcDiverse website layout.

No additional dependencies are required for this change.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### From the Main Website:
image

### Before Calculation.
image

### After Clicking Calculate,
image

### Before Calculation.
image

### After Clicking Calculate,
image

### CODE REVIEW

**Comment by kamalesh-og** [comment]
Hello Project Admin,
I've updated the new feature that was assigned to me, Can you merge my PR into yours @Rakesh9100
Also please add Levels to the Issue because then only the project will be considered for my points.
Sorry for the delay, I had some academic works
Thank you

**Comment by Nihal4777** [comment]
Hello @kamalesh-og, Navbar is not responsive.
image

**Comment by kamalesh-og** [comment]
Hi sir @Nihal4777,
I've never mentioned that the navbar would be responsive tho, though this would be a non-responsive website actually.

**Comment by kamalesh-og** [comment]
Hi @Nihal4777,
I've added responsiveness now inspired by my previous projects (Burger Menu)
Is it alright now?
image
image

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can be merged.

**Pull request merged**
