### PR TITLE
Added Sunlight Hours Calculator

### LINKED ISSUE #1038: [Feature] Add Sunlight Hours Calculator
### Description

This tool will help users estimate the number of sunlight hours in a day based on their location and the date.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
# Fixes Issue🛠️

Closes #1038 

# Description👨‍💻

This tool will help users estimate the number of sunlight hours in a day based on their location and the date.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly review and merge
If any changes are required kindly tell

**Comment by Rakesh9100** [comment]
Pls work on these @Aditi22Bansal 

1. Rename your folder to `Sunlight-Hours-Calculator` and make the necessary changes by making the commits in this same PR.
2. Also, add your calculator part in the main `index.html` file to display it on the website.

**Comment by Rakesh9100** [comment]
Are you working @Aditi22Bansal

**Comment by Aditi22Bansal** [comment]
Yes @Rakesh9100

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Any other changes required?

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly check now

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly review and merge

**Comment by Rakesh9100** [comment]
image

1. Delete the first folder.
2. Include script.js in the second folder.
3. Add your calculator part in this [File](https://github.com/Aditi22Bansal/CalcDiverse/blob/main/index.html) @Aditi22Bansal

**Pull request merged**
