### PR TITLE
Added Sunrise and Sunset Calculator

### LINKED ISSUE #372: [Feature] Adding Sunrise and Sunset Calculator
### Description

Create a Sunrise and Sunset Calculator that enables users to determine the approximate times of sunrise and sunset based on specified longitude and latitude coordinates.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Fixes Issue🛠️

- Fixes #372

# Description👨‍💻 

The Sunrise & Sunset Calculator is a simple yet powerful tool that allows users to determine the precise times of sunrise and sunset based on geographical coordinates. By providing the latitude and longitude values of a specific location, this calculator delivers accurate information regarding when the sun will rise and set at that particular point on the Earth's surface.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have done Alpha, Beta & Unit Testing

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100 This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the "JWOC" and "Difficulty" labels to this pull request.

Thank you for the opportunity to contribute to the project!

**Comment by Rakesh9100** [comment]
Pls add your calculator screenshot in the Readme file @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Done! 👍🏼

**Comment by Rakesh9100** [comment]
Good job, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Thankyou for the opportunity to contribute

**Pull request merged**
