### PR TITLE
Added Calorie Burnt Calculator

### LINKED ISSUE #352: [Feature] Adding Calorie Burnt Calculator
### Description

It is used to check how fit are you and helps to define the calories burned for the day

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivam101203**
# Fixes Issue🛠️
#352

Closes #352

# Description👨‍💻 
It is a calculator which is used to get calories burnt on particular amount of exercise.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
new2

### CODE REVIEW

**Comment by shivam101203** [comment]
#352  have been resolved sir.

**Comment by Rakesh9100** [comment]
Rename your folder to `Calorie-Burnt-Calculator` and make the necessary changes.

Take a reference of how other calculators Readme are present and edit your readme in the same way @shivam101203

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
Sir please help me i couldn't know how
Can I update folder name without closing pr

**Comment by shivam101203** [comment]
done sir #352

**Comment by Rakesh9100** [comment]
Pls keep your folder name as told, B in burnt should be capital @shivam101203

**Comment by Rakesh9100** [comment]
Resolve the conflicts @shivam101203

**Comment by shivam101203** [comment]
sir everything is done as you have said please merge the pr

**Comment by Rakesh9100** [comment]
Good job, Glad that you learned to merge conflicts, rename folder and everything without closing the PR!!

Merged ✨ @shivam101203

**Comment by shivam101203** [comment]
Sit it is because of you efforts thanks to you

**Pull request merged**
