### PR TITLE
Added Buoyancy Calculator

### LINKED ISSUE #1782: [Feature] Add Buoyancy Calculator
### Description

I want to add Buoyancy Calculator

Calculates the buoyant force on an object submerged in a fluid

@Rakesh9100, assign me this issue under GSSOC

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sreevidya-16**
# Fixes Issue🛠️

Closes #1782 

# Description👨‍💻

Added Buoyancy Calculator

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

image

### CODE REVIEW

**Comment by sreevidya-16** [comment]
@Rakesh9100 view this PR

**Comment by Nihal4777** [comment]
@sreevidya-16   Add your calc in main index.html file of the project in alphabetical order.

**Comment by Nihal4777** [comment]
Also name your project folder as `Buoyancy-Calculator`

**Comment by sreevidya-16** [comment]
Updated PR
@Rakesh9100 view this PR

**Comment by sreevidya-16** [comment]
@Rakesh9100 view this PR

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Pull request merged**
