### PR TITLE
Added Fraction Calculator

### LINKED ISSUE #1360: [Feature] Add Fraction Calculator
### Description

Hello Project Admin @Rakesh9100,

Adding an Operational Fraction Calculator to CalcDiverse will enable users to perform basic arithmetic operations (addition, subtraction, division, multiplication) on fractions. The calculator will allow users to click on the "+" button to select different operators and then click on "=" to get the result. This tool will provide a straightforward way to handle fraction calculations, making it an invaluable addition to the CalcDiverse project.

I've previously contributed to CalcDiverse by implementing other calculators and would love to further enhance this amazing repository with the addition of the Fraction Calculator. This is a simple yet handy calculator for this repo.

@Rakesh9100 Can you assign me this project? I am eager to work on this calculator and make fraction calculations easy and accessible for all users.

### Screenshots

image
Here I just used HTML code, should add CSS for better UI, and should add JS for the functionality of the respective inputs given.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by kamalesh-og**
# Fixes Issue🛠️

Closes #1360 

# Description👨‍💻 

This pull request introduces the Fraction Calculator to enhance the CalcDiverse repository. This calculator allows users to perform basic arithmetic operations on fractions, including addition, subtraction, multiplication, and division. Users can input numerators and denominators for two fractions, select an operation, and compute the resulting fraction. The calculator automatically simplifies the resulting fraction to its lowest terms for clarity, ease of use, and making it efficient.

The Fraction Calculator features a user-friendly interface with input fields for numerators and denominators, an operation selector dropdown, and output fields displaying the simplified result. The design ensures intuitive interaction and maintains consistency with the existing CalcDiverse website layout.

No additional dependencies are required for this change.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### From the Main Page,
image

### Sample Output 1,
image

### Sample Output 2,
image

### Sample Output 3,
image

### Sample Output 4,
image

### CODE REVIEW

**Comment by kamalesh-og** [comment]
Hello Project Admin,
I've updated the new feature that was assigned to me, Can you merge my PR into yours @Rakesh9100
Also please add Levels to the Issue because then only the project will be considered for my points.
Sorry for the delay, I had some academic works
Thank you

**Comment by Nihal4777** [comment]
@kamalesh-og Please fix the conflicts after taking latest pull.

**Comment by kamalesh-og** [comment]
Hi @Nihal4777, i did synced the fork before doing PR always
okay ill do now anyways, one min

**Comment by kamalesh-og** [comment]
Hi @Nihal4777, Can you check now please

**Comment by kamalesh-og** [comment]
can you check now @Nihal4777 
ive removed some unwanted commits, i added by mistake i guess
my bad

**Pull request merged**
