### PR TITLE
Fixed the working of some buttons in Basic Calculator

### LINKED ISSUE #242: [Bug] : Fix the working of some buttons in Basic Calculator
### Description

**Problems:**
1) buttons like **(√, ^, sin, cos )** not working because **closing brackets are missing.** Because of which it is showing **error**.
2) All buttons are not arranged properly.
3) It is **not responsive** as shown in screenshot.

**Sollution:**
1) I will add bracket buttons **[  '('   ,   ')'  ]** so that we can complete our input and use the feature of  **(√, ^, sin, cos )** and it will not show error.
2) I will work on css to **arrange buttons** and make **website resposnsive** so that it look beautifull.

Kindly assign this issue to me under IWOC2024

### Screenshots

Screenshot 2024-01-13 234836
Screenshot 2024-01-14 000127
Screenshot 2024-01-13 234724
Screenshot 2024-01-13 234746

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
Closes #242 

# Type of change📄

1) buttons like (√, ^, sin, cos ) not working because closing brackets are missing. Because of which it is showing error.✅
2) All buttons are not arranged properly.✅
3) It is not responsive as shown in screenshot.✅

# How this has been tested✅
 I had run all the changes on website all is working well👍.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration
- [] I am an Open Source Contributor
- 
# Screenshots📷
calculatoar

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
sir, kindly check now.

**Comment by Rakesh9100** [comment]
Pls mention the issue number this PR closes @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
issue #242

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly guide,
Is every thing ok?

**Comment by Rakesh9100** [comment]
Good, Merged!! ✨ @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
thankyou sir 😊

**Pull request merged**
