### PR TITLE
capacitance calculator added

### LINKED ISSUE #1711: Capacitance Calculator is missing which is a good one for physics students
### Description

It should also be there in the website

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhinavKRN**
# Fixes Issue🛠️

Closes #1711 

# Description👨‍💻

I have developed a capacitance calculator using HTML, CSS, and JavaScript. This tool allows users to calculate capacitance based on provided input values.

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [ ] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image
image
image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@AbhinavKRN Please add your calculator in main index.html of project in alphabetical order.

**Comment by AbhinavKRN** [comment]
@Nihal4777 only html file? or css and js file too?

**Comment by AbhinavKRN** [comment]
@Nihal4777  done!

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed.

**Comment by Rakesh9100** [comment]
You are not assigned to this issue @AbhinavKRN

**Pull request closed without merging**
