### PR TITLE
Added Garden Planning Calculator

### LINKED ISSUE #1539: [Feature] Add Garden Planning Calculator
### Description

Create a garden planning website with a calculator-like interface where users can accurately calculate the maximum number of plants that can fit based on garden dimensions and plant spacing. Include a cost calculation feature to determine the financial implications of planting, showing potential profit or loss.

### Screenshots

image

This is the website i have made so far for the calculator i still have to improve the ui and the mathematics behind the calculator but this is how it is going to work 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
# Fixes Issue🛠️

Closes #1539 

# Description👨‍💻

I have added the garden planning website.

This Garden Planning Calculator helps users efficiently plan their garden by calculating the number of plants that can fit based on garden dimensions and plant spacing. It also determines the total cost, the remaining budget, the unused garden space, and the additional funds needed to fill the remaining space. The intuitive interface ensures easy input and clear results, aiding in effective garden budgeting and space management.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please review my pull request

**Comment by Rakesh9100** [comment]
### Please align all the boxes and text vertically straight, as this is not looking good.
image

### Also, make the UI responsive for smaller screens @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 hi i made the changes you requested and also i have made the page responsive 
image

image

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please review this pull request i made the changes requested

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 hi sir i made the changes you had requested please review and merge this pull request

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 sir its been a week since i made the changes you requested please review my pull request and merge it so i can work on another issue

**Comment by sanjay-kv** [comment]
@Rakesh9100 invite me to the repo there is lot of spams happening. need to sort it out before event closes.
+ this issue let the contributor know whats happening. its okay if you don't intend to merge. i can add extra points to him from gssoc side.

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 yes  please as this is my first pull request in this repo and its been a week since i made this pull request

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please check this pr

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 hi its been 2 weeks since i made the changes please review and merge this pull request as only 1 week is left for gssoc to get over

**Comment by sanjay-kv** [comment]
@aditya-bhaumik dont worry i will launch a google form for this.

**Comment by aditya-bhaumik** [comment]
@sanjay-kv thank you

**Pull request merged**
