### PR TITLE
Added Twin Prime Number Calculator

### LINKED ISSUE #989: [Feature] Add Twin Prime Number Calculator
### Description

The Twin Prime Number Calculator identifies pairs of prime numbers that have a difference of 2, known as twin primes. It checks each number up to a specified limit to determine if it and the number two greater are both prime. By iterating through numbers and verifying their primality, the calculator compiles a list of all such twin prime pairs within the given rang

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
# Fixes Issue🛠️

Fixes #989 

# Description👨‍💻 

i add a calculator that identifies pairs of prime numbers that are exactly 2 units apart. It takes a limit or range as input, checks for prime numbers within that range, and then finds pairs with a difference of 2. The calculator efficiently displays these twin prime pairs, making it easy to explore these special numbers.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested it in my local device and it  is fully working.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image_2024-06-01_210753079

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@Rakesh9100  please  give some reply

**Comment by Rakesh9100** [comment]
Enter 100 and click Show Primes, then scroll to see all the results. It is not showing properly, pls fix @Pujan-sarkar

**Comment by Pujan-sarkar** [comment]
Okay sir

**Comment by Pujan-sarkar** [comment]
@Rakesh9100 please check now I have solved the problem .

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @Pujan-sarkar

**Pull request merged**
