### PR TITLE
Add more shapes to the 2d Calculators & Enhance UI

### LINKED ISSUE #185: Add more shapes to the 2d Calculators & Enhance UI.
### Description

The present 2d Calculator has only 5 shapes .

This issue add more shapes and finds their values such as Perimeter & Area .

This issue also enhances the UI of the 2d Calculator.

The improvements before and after can be seen below :

### Screenshots

**Before :** 
image

**After making Improvements :** 

image

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by CodeByRajeev**
Closes  #185  Add more shapes to the 2d Calculators & Enhance UI.

**# Description👨‍💻** 

This issue adds more shapes to the present 2D Shape Calculator : 
- Adds more shapes
- Adds a new function if a negative value is entered.
- Asks different parameters for different shapes Eg: Circle, Rectangle, Rhombus.
- Enhances The whole UI of the Calculator.

**# Checklist✅** 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

**# Screenshots/GIF📷**

The changes before and after making improvements can be seen in the below attached screenshots : 

**Before :** 

image

image

**After making Improvements :** 

image

image

image

image

**If a negative value is entered :** 

image

### CODE REVIEW

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir, Please go through the PR and if everything is good enough , kindly do merge the PR.

**Comment by Rakesh9100** [comment]
Upon landing on the calculator page, only the "Select a shape" dropdown and "Calculate" button should be visible. The input boxes for length, width, and other parameters should become visible only when the user selects a specific shape from the dropdown menu @CodeByRajeev

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir, the changes you have asked for is made and here is the screenshot after making the changes.

image
image


Please do check it.

**Comment by Rakesh9100** [comment]
Appreciated! Merged!! 🥳 @CodeByRajeev Keep Contributing!!

**Pull request merged**
