### PR TITLE
Added reset button in 2D Distance Calculator

### LINKED ISSUE #764: Reset Option in Calculators
### Description

There is no reset option available in the calculators. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Kashishgarg248**
# Fixes Issue🛠️

Closes #764 

# Description👨‍💻 

Added Reset Button in 2-D Distance Calculator.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When we try to Reset after filling the inputs, it is not clearing the values. Pls do fix @Kashishgarg248

**Comment by 07Khushi** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/110482385/c4c5538d-fbbf-4033-8632-eb4ac46c292b

Sir, at my end the reset option is working .Can you please check ?

**Comment by Kashishgarg248** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/153218193/6ed0f518-7ee0-4ea3-ad7e-28c91037450c

Sir, at my end the reset option is working smoothly . Can you please check again.

**Comment by Rakesh9100** [comment]
Fill the values and then reset before clicking the Calculate Distance button @Kashishgarg248

**Comment by Kashishgarg248** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/153218193/3be6c7c8-a397-4fd2-809f-014787e12e70

Reset Option is working sir

**Comment by Kashishgarg248** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/153218193/23b60bd8-92b9-4700-8498-409b82b210ef

Reset Option is Working sir

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @Kashishgarg248

**Comment by Kashishgarg248** [comment]
Thank you sir

**Pull request merged**
