### PR TITLE
Displayed No results found message

### LINKED ISSUE #816: [Bug] Display No results found message
### Description

If the user is searching a calculator and it is not found in the predefined calculators in websites it should display the message "no results found". By customizing the html and css code i will solve this issue.

### Screenshots

image
Here time complexity calculator is not found. But it is not displaying any message.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

@Rakesh9100

### PR DESCRIPTION
**Pull request by Janani-m17**
# Fixes Issue🛠️

Closes #816 

# Description👨‍💻 

If the user searches the calculator that is not available in the calcdiverse It should display No Results Found.

# Type of change📄

Added changes in index.html

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Yes I have tested the application.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

@Rakesh9100

### CODE REVIEW

**Comment by Janani-m17** [comment]
image
@Rakesh9100 Kindly Check now

**Comment by Rakesh9100** [comment]
I am checking but not text is not coming @Janani-m17

**Comment by Rakesh9100** [comment]
Merged 🙌 @Janani-m17

**Comment by Janani-m17** [comment]
@Rakesh9100 Thank you sir

**Pull request merged**
