### PR TITLE
Improved the text color in Contact form

### LINKED ISSUE #718: [Style] Improve the text color in Contact form
@Rakesh9100 
### What's the style idea?

We need to improve
image

we can create something like this 
image

i'm GSSOC'24 Contributor

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by dhruv8433**
# Fixes Issue🛠️

Closes #718 

# Description👨‍💻 

I redesign and update contact form css to look good and suit with theme.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Rakesh9100 

please check this and merge it

**Comment by dhruv8433** [comment]
@Rakesh9100 

please response
i completed contact form 

please merge it and add `level` label

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @dhruv8433

**Comment by dhruv8433** [comment]
@Rakesh9100 
Thank you :)

**Pull request merged**
