### PR TITLE
Added hover effect to the pagination buttons

### LINKED ISSUE #1796: [Style] Add hover effect to the pagination buttons
### What's the style idea?

I'll add hover effect on "previous" and "next" buttons.
Screenshot 2024-08-05 002417

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by TaeMochi12**
# Fixes Issue🛠️
Closes #1796

# Description👨‍💻
I've added hover effect on the pagination buttons i.e. 'Previous' and 'Next' matching the UI.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)
- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷
Screenshot 2024-08-09 182159
Screenshot 2024-08-09 182351

### CODE REVIEW

**Comment by TaeMochi12** [comment]
@Rakesh9100 I've added the hover effect, kindly review the PR.

**Comment by TaeMochi12** [comment]
@Rakesh9100 Please review the PR.

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed  & can be merged.

**Comment by TaeMochi12** [comment]
@sharmi4590 Please merge the PR.

**Comment by sharmi4590** [comment]
> @sharmi4590 Please merge the PR.

@TaeMochi12 I am not the PA

**Pull request merged**
