### PR TITLE
Added Atomic Mass Calculator

### LINKED ISSUE #1063: [Feature] Add Atomic Mass Calculator
### Description

The Atomic Mass Calculator is a tool designed to calculate the total atomic mass of a chemical compound based on the input of its constituent elements and their respective counts. 
Users can input the chemical formula of the compound, and the calculator will determine its atomic mass by summing the masses of the individual atoms present.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by bristiHalder**
# Fixes Issue🛠️

Closes #1063 

# Description👨‍💻

- Implemented an Atomic Mass Calculator that calculates the atomic mass of a given chemical formula.
- Updated HTML structure for a better user experience.
- Improved CSS styling to give the web application a more modern appearance.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these and make the changes by making commits in this same PR @bristiHalder 

1. Add a Readme file of your calculator in your folder.
2. Add your calculator part in the main `index.html` file to display it on the website.
3. Attach the screenshot of your work here in the PR template above.

**Comment by Rakesh9100** [comment]
We already have Molecular Weight Calculator and your calculator is also doing the same @bristiHalder

**Comment by bristiHalder** [comment]
It would have been helpful if you mentioned your existing calculator during the initial issue raised, as it could have provided context or clarified similarities sooner.

**Comment by Rakesh9100** [comment]
I can understand but I missed that. Contributors also must check the website, repository, and existing issues thoroughly before creating any issue @bristiHalder

**Pull request closed without merging**
