### PR TITLE
Added Amortization Calculator

### LINKED ISSUE #928: [Feature] Add Amortization Calculator
### Description

 financial tool used to determine the repayment schedule of a loan, typically a mortgage or car loan. It calculates the periodic payments and the distribution of those payments between principal and interest over the life of the loan.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yashgabani845**
# Fixes Issue🛠️

Closes #928 

# Description👨‍💻 

I have added amortization which calculate financial details of loan and give amortization schedule.
 
I have tried to not make any mistake which I had done in my previous PR, still if I missed anything, give changes.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

- I have tested it in different browser.
- With many edge cases value.
- Invalid values.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/127788321/7091d8a9-423c-44e4-ae81-5771c7503589

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@Rakesh9100 
added amortization calculator 
please review it

**Comment by Yashgabani845** [comment]
@Rakesh9100 if you are going to merge it then please assign next issue that i have raised
#1094

**Comment by Yashgabani845** [comment]
@Rakesh9100 please look over it

**Comment by Rakesh9100** [comment]
Add your calculator in main `index.html` file to display it on the website @Yashgabani845

**Comment by Yashgabani845** [comment]
@Rakesh9100 done it , please check it 
Screenshot (359)

**Comment by Yashgabani845** [comment]
@Rakesh9100 i would request you to assign me this next issue #1094

**Pull request merged**
