### PR TITLE
Added Complex Seismographic Impact Calculator

### LINKED ISSUE #1667: [Feature] Add Complex Seismographic Impact Calculator
### Description

Assessing the potential impact of an earthquake is vital for preparedness and response efforts. At present, there is no unified tool that combines earthquake magnitude, distance from the epicenter, local population density, and building types to deliver a comprehensive estimate of ground shaking intensity, damage levels, and affected population.

A tool that determines the potential effects of an earthquake using user-provided data like earthquake magnitude, distance from the epicenter, local population density, and optionally, building types. The results should encompass:

Ground Acceleration
Mercalli Intensity 
damage levels
affected population

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sravyasaka**
# Fixes Issue🛠️

Closes #1667 

# Description👨‍💻

Added complex seismographic calculator

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
Hi @Sravyasaka, Actually you have to add your calculator in main index.html file.

**Comment by Sravyasaka** [comment]
> Hi @Sravyasaka, Actually you have to add your calculator in main index.html file.

@Nihal4777 , Done

**Comment by Rakesh9100** [comment]
Add a README.md file of your calculator @Sravyasaka

**Comment by Rakesh9100** [comment]
Pls add a README.md file of your calculator and attach the screenshot of your work in the PR description @Sravyasaka

**Comment by Sravyasaka** [comment]
> Pls add a README.md file of your calculator and attach the screenshot of your work in the PR description @Sravyasaka

@Rakesh9100 , Done. Please review

**Pull request merged**
