### PR TITLE
Added Conductivity and Resistivity Calculator

### LINKED ISSUE #331: [Feature] Conductivity and Resistivity Calculator
### Description

this project requires a conductivity and resistivity calculator

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sakshamjain98**
# Fixes Issue🛠️

Closes #331 

# Description👨‍💻 

IT CALCULATES THE RESISTIVITY AND CONDUCTIVITY BY TAKING LENGTH , AREA AND RESISTANCE AS INPUT

# Type of change📄

A new calculator is added

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Sakshamjain98** [comment]
Sir I have done with this issue please check it out......

**Comment by Rakesh9100** [comment]
Rename your folder to `Conductivity-And-Resistivity-Calculator` and make the necessary changes.

Include your calculator in main `index.html` file at the end in the correct way @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Sir Done the work please check

**Comment by Rakesh9100** [comment]
Merged 🎉 @Sakshamjain98

**Pull request merged**
