### PR TITLE
Added Kinetic And Potential Energy Calculator

### LINKED ISSUE #1219: [Feature] Add Kinetic And Potential Energy Calculator
### Description

This calculator helps us to calculate the kinetic energy using the formula  K.E. = 1/2 * m * (v^2)
and potenial energy P.E. = m * a * h
where m= mass
a=acceleration
v=velocity
I want add this calculator

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anshika14528**
# Fixes Issue🛠️

Closes #1219 

# Description👨‍💻

Added Kinetic And Potential Energy Calculator which helps us to calculate the kinetic and potential energy.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-29 at 7 00 23 PM

Screenshot 2024-06-29 at 7 00 31 PM

Screenshot 2024-06-29 at 7 00 43 PM

Screenshot 2024-06-29 at 7 00 58 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls provide Clear and Reset buttons below Calculate button @Anshika14528 

Also, use some good background image that is not blurry, you can use any good HD image!!

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, i have made the required changes please review it now.
Screenshot 2024-07-02 at 11 12 22 AM

**Comment by Rakesh9100** [comment]
image

Center the result or validation text here!

And, when let's say after calculating KE, we are switching to calculate PE, the result and all the values should be cleared automatically and same for the vice-versa @Anshika14528

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, I have made the required changes is it good now please review it.
Screenshot 2024-07-02 at 2 33 30 PM

**Comment by Rakesh9100** [comment]
Pls don't make any extra changes or any formatting changes in this main [index.html](https://github.com/Anshika14528/CalcDiverse/blob/kin/index.html) file, just add your calculator part alphabetically @Anshika14528

**Comment by Anshika14528** [comment]
@Rakesh9100 sir , i have made the required changes please review it .

**Comment by Rakesh9100** [comment]
[Check](https://github.com/Rakesh9100/CalcDiverse/pull/1505/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) this @Anshika14528

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, i am not able to do it. Like I am now copying the original index.html file and pasting and committing it without formatting then also it appears like this.

**Comment by Anshika14528** [comment]
If I am trying to  view the raw file then it is appearing correct.

**Comment by Rakesh9100** [comment]
No need to create a new PR. You should learn to resolve the issues, and this is why Open Source is made.

It is because you are copying the content of that file from the original repo of my account, which has some new commits and files which are not present on your forked repo branch. Pull and merge the latest changes on your branch and make the commit in this same PR @Anshika14528

**Comment by Rakesh9100** [comment]
Or you can directly delete those extra lines visible and make the commit @Anshika14528

**Comment by Rakesh9100** [comment]
Or you can directly delete those extra lines visible in that file and make the commit @Anshika14528

**Comment by Anshika14528** [comment]
I have updated the branch and then I am trying to copy paste but its not working I will try as you are saying.

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, I have done it Please review it now .

**Pull request merged**
