### PR TITLE
Improved the background in 3D Distance Calculator

### LINKED ISSUE #1726: [Style] Improve the background in 3D Distance Calculator
### What's the style idea?

We need to improve the background of calculators in caldiverse.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [x] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Unnati-Gupta24**
# Fixes Issue🛠️

Closes #1726 

# Description👨‍💻

Background do not have any styling changed, the background styling added with a working wave animation.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Unnati-Gupta24 Please mention the issue you are working on.

**Comment by Unnati-Gupta24** [comment]
Many calculators in CalDiverse do not have an appropriate background some have repeated images while some do not have a background at all. so i decided to add an animated wave background in the calculator page

**Comment by Unnati-Gupta24** [comment]
the screenshot i added is after adding the background because the original calculator have a repeated image as a background

**Comment by Unnati-Gupta24** [comment]
> @Unnati-Gupta24 Please mention the issue you are working on.

Many calculators in CalDiverse do not have an appropriate background some have repeated images while some do not have a background at all. so i decided to add an animated wave background in the calculator page
the screenshot i added is after adding the background because the original calculator have a repeated image as a background @Nihal4777

**Comment by Rakesh9100** [comment]
Are you assigned to any issue or have you opened an issue before creating a PR @Unnati-Gupta24

**Comment by Unnati-Gupta24** [comment]
I apologize I actually created a PR before posting the issue.
I created an issue now #1726 .

**Pull request merged**
