### PR TITLE
Added Rectangular to polar calculator

### LINKED ISSUE #197: [Feature] :Rectangular to polar form calculator
### Description

This calculator will take values in rectangular form and convert them into polar form. These calculations are very important for students who are studying electrical or electronics engineering and any engineering that has network problems.

### Screenshots

Interface will vaguely look like this
image

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

### LINKED ISSUE #198: [Feature] : Basic Calculator
### Description

Calcdiverse has various calculators except the main basic calculator that can perform some complex tasks. I'd like to add that.

### Screenshots

This is how it will look altho the css will be improved:-
image

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Yatin12527**
# Fixes Issue🛠️

Closes  #197 

# Description👨‍💻 
**Rectangular to polar convertor**
converts rectangular form into polar form 

# Type of change📄
Feature updated

# How this has been tested✅

locally

# Screenshots/GIF📷

Untitled

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Hey @Yatin12527 

1. Pls open 2 different PRs as two different major issues are opened.
2. Keep the `Rectangular to polar calculator` in this PR only and delete all other files and make the commit.
3. Create another PR for `basic calculator`.

**Comment by Rakesh9100** [comment]
Why `Simple-Intrest-Calculator` files are added. Delete and fix @Yatin12527 

Name your folder as `Rectangular-To-Polar-Calculator` and make necessary changes in main `index.html` as well @Yatin12527

**Comment by Yatin12527** [comment]
> Why `Simple-Intrest-Calculator` files are added. Delete and fix @Yatin12527
> 
> Name your folder as `Rectangular-To-Polar-Calculator` and make necessary changes in main `index.html` as well @Yatin12527

I added si calculator aswell so i fixed few things in it dw about it as for the index file let me see what's the issue

**Comment by Rakesh9100** [comment]
Do remove SI calc as it is already present @Yatin12527

**Comment by Yatin12527** [comment]
@Rakesh9100 check now

**Comment by Rakesh9100** [comment]
> Why `Simple-Intrest-Calculator` files are added. Delete and fix @Yatin12527
> 
> Name your folder as `Rectangular-To-Polar-Calculator` and make necessary changes in main `index.html` as well after renaming the folder @Yatin12527

Work on the second change @Yatin12527

**Comment by Yatin12527** [comment]
> > Why `Simple-Intrest-Calculator` files are added. Delete and fix @Yatin12527
> > Name your folder as `Rectangular-To-Polar-Calculator` and make necessary changes in main `index.html` as well after renaming the folder @Yatin12527
> 
> Work on the second change @Yatin12527

renamed the folder

**Comment by Rakesh9100** [comment]
Merged!! 🎉 @Yatin12527

**Pull request merged**
