### PR TITLE
 Added Narcissistic Number Calculator

### LINKED ISSUE #1164: [Feature] Add Narcissistic Number Calculator
### Description

The calculator tells that whether the entered number is a narcissistic number or not

Eg : 371 = 3³ +7³ +1³

@Rakesh9100 I would like to work on this under GSSoC

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
# Fixes Issue🛠️

Closes #1164 

# Description👨‍💻

1. Created index.html
2. Created style.css
3. Created script.js
4. Added hovering effects
5. Added Stylish background and good text effects
6. Added the Narcissistic Number Calculator to the main web page
7. Added README documentation

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@SuhainaFathimaM Please add Empty field validations. 
Also, it would be great if you could provide brief description of narcissistic number.
image

**Comment by Rakesh9100** [comment]
Are you working on the changes asked @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 yes, I am working on it

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Made the changes.. 
image

**Comment by Rakesh9100** [comment]
image

Below `371 is a Narcissistic number.` text, add 1-2 lines proven explanation why it is a Narcissistic Number and same for the one which is not @SuhainaFathimaM

**Comment by Rakesh9100** [comment]
Make your commits by today EOD @SuhainaFathimaM

**Comment by Rakesh9100** [comment]
Any update or should I close this @SuhainaFathimaM

**Pull request merged**
