### PR TITLE
Added Heat Capacity Calculator

### LINKED ISSUE #1710: [Feature] Add Heat Capacity Calculator
### Description

It should also be there in the website

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Utsavladia**
# Fixes Issue🛠️

Closes #1710 

# Description👨‍💻

Added heat capacity calculator

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image
image

### CODE REVIEW

**Comment by Utsavladia** [comment]
@Rakesh9100 Kindly review this PR GSSOC is getting ended

**Comment by Utsavladia** [comment]
@Rakesh9100 
Kindly merge this PR before closing of GSSOC 🙂

**Comment by Nihal4777** [comment]
@Utsavladia Please add your calculator in main index.html file of project.

**Comment by Utsavladia** [comment]
@Nihal4777 
Added into index.html ✅
image

**Comment by Utsavladia** [comment]
@Nihal4777 
Kindly mrege this PR before GSSOC ends 😌

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Pull request merged**
