### PR TITLE
Added the scroll to top button in Contributors page

### LINKED ISSUE #755: [Feature] Add the scroll to top button in Contributors page
### Description

Add the scroll to top button in Contributors page for better UI.

### Screenshots

Screenshot (234)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Scrapper700**
# Fixes Issue🛠️ 

Closes #755 

# Description👨‍💻 

Scroll to top button added in Contributors page.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (263)

### CODE REVIEW

**Comment by Scrapper700** [comment]
@Rakesh9100 Done.Kindly review

**Comment by Rakesh9100** [comment]
Why are you changing the PR template, pls don't do from the next time and fill every details properly!

**Comment by Rakesh9100** [comment]
Why are you changing the PR template, pls don't do from the next time and fill every detail properly!

Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @Scrapper700

**Comment by Rakesh9100** [comment]
Why are you changing the PR template, pls don't do from the next time and fill every detail properly!

Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @Scrapper700

**Comment by Scrapper700** [comment]
@Rakesh9100 I did not know that by changing this template anything would've happened..Will keep this thing in my mind next time

**Pull request merged**
