### PR TITLE
Added Clothing Size Calculator

### LINKED ISSUE #293: [Feature] International Clothing Size Calculator
### Description

I want to add a new calculator, that inter-converts international clothing size of different countries, and also provides the accurate measure for each of the sizes in metrics. Please assign me this issue under IWOC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #293

# Description👨‍💻 

Added the International clothing size calculator

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my local machine, looks and works as intended.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-01-16 at 3 12 53 PM
Screenshot 2024-01-16 at 3 14 53 PM

### CODE REVIEW

**Comment by SoumyadevSaha** [comment]
Is there any issue with the PR ? @Rakesh9100 ?

**Comment by Rakesh9100** [comment]
Reviewing this PR only @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
oh I see ... please do let me know if there are any buga

**Comment by SoumyadevSaha** [comment]
What shall I do next regarding this ?? @Rakesh9100 ? shall I inlude the limits for a region in my alerts ?

**Comment by Rakesh9100** [comment]
No need to create new PR!! pls do wait, will update you @SoumyadevSaha

**Comment by Rakesh9100** [comment]
You can do one thing that modify the alert for every countries and make it like "Please enter a size that is available in the selected region, the size varies from <lowest> to <highest> for this region" and also provide this reference link in these alert boxes @SoumyadevSaha

**Comment by Rakesh9100** [comment]
No need to create a new PR!!

You can do one thing that modify the alert for every countries and make it like "Please enter a size that is available in the selected region, the size varies from <lowest> to <highest> for this region" and also provide this reference link in these alert boxes @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> No need to create a new PR!!
> 
> You can do one thing that modify the alert for every countries and make it like "Please enter a size that is available in the selected region, the size varies from to for this region" and also provide this reference link in these alert boxes @SoumyadevSaha

okay, on it

**Pull request merged**
