### PR TITLE
Fixed multiple operators in Basic Calculator

### LINKED ISSUE #685: [Bug] Fix multiple operators in Basic Calculator
### Description

basicCalc
Multiple operators
Please assign me to fix this issue
(Under GSSOC'24 contributions)

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by tanu-agarwal0101**
# Fixes Issue🛠️ 

Closes #685 

# Description👨‍💻 

Multiple operators issue fixed.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅
Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### Before
image

### Now
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
The issue is solved from the UI part, but when we enter input from keyboard, the issue is not fixed. Pls see to this @tanu-agarwal0101 

Make the new commits in this same PR, don't create a new PR!!

**Comment by tanu-agarwal0101** [comment]
Ok sir

**Comment by tanu-agarwal0101** [comment]
@Rakesh9100 please check now

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @tanu-agarwal0101

**Pull request merged**
