### PR TITLE
Added Cost Of Living Calculator

### LINKED ISSUE #1682: [Feature] Add Cost Of Living Calculator
### Description

Implement a Cost of Living Calculator that allows users to compare the cost of living between two cities or locations. The calculator should take into account various factors such as housing, food, transportation, and other living expenses to provide a comprehensive comparison.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by abhay-sen**
# Fixes Issue🛠️

Closes #1682 

# Description👨‍💻

Added the cost of living calculator that compares the current salary in the current city with respect to another city

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@abhay-sen Please add validations. 
Also default value of both dropdowns should be select city1 & 2 respectively.
image

**Comment by abhay-sen** [comment]
Okay sir working on it asap

**Comment by abhay-sen** [comment]
@Nihal4777 sir could you please check 
i have made the changes you requested
Screenshot 2024-07-29 003845
Screenshot 2024-07-29 003853
Screenshot 2024-07-29 003903

**Comment by abhay-sen** [comment]
Respective mentors @Nihal4777 @Rakesh9100 please review and merge this pr as gssoc would not count this pr if merged after 31st July 11:59 pm
It's my humble request sir to review and merge this pr asap!.

**Comment by Rakesh9100** [comment]
image

Have you kept your data in this JSON file or what is present, as it has approx 3 lakh lines of code @abhay-sen

**Comment by abhay-sen** [comment]
> image
> 
> Have you kept your data in this JSON file or what is present, as it has approx 3 lakh lines of code @abhay-sen 

Yes sir the data is in the json file as the api which was required to call was paid

**Pull request merged**
