### PR TITLE
Added voice command Search bar

### LINKED ISSUE #443: [Feature] Add voice command Feature to search Bar
### Description

I will Add **voice command** Feature to search Bar to **search calculators** based on voice input.

Kindly assign this issue to me under **IWOC2024.**

### Screenshots

Screenshot 2024-01-23 175029

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️
#443 [Feature] Add voice command Feature to search Bar.

Closes #443

# Description👨‍💻 

Added **voice command feature** to search bar to **search calculators on voice input**.
This Feature is fully **functional** as shown in **video.**

For this I used Web speech API to take voice input.
I had also added styling to buttons which matches with UI of website.
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

This has been tested by me by running the website, no error found!!

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/149922307/0a7a3758-3987-435b-931d-22124a516c58

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly check.

**Comment by Rakesh9100** [comment]
Resolve the conflicts @Prince-kushwaha-2004

**Comment by Rakesh9100** [comment]
image

Make it responsive for smaller screens @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Screenshot 2024-01-26 121254

**Comment by Rakesh9100** [comment]
Merged 🎉 @Prince-kushwaha-2004

**Pull request merged**
