### PR TITLE
Shivamm verma time calculator

### LINKED ISSUE #80: [SWOC24] Time Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- Enter Time in any format (hours, minutes, seconds), this will show other two formats of time.
- better UI by adding shadows, and background.

### Screenshots

*screenshot*

ss1

*screen recording* 

https://github.com/Rakesh9100/CalcDiverse/assets/98605616/b44638ec-ecbe-42ff-a8d7-99153b1db151

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by shivamm-verma**
# Fixes Issue🛠️ Closes #80 

Closes #

# Description👨‍💻 

This Calculator Calculates the Hours, Minutes and Seconds for any entered Time.

# Type of change📄

- [] New feature (Calculator Addition)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of video file. (in the Created Issue)
- [] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshots and recordings are mentioned on the Created Issue itself.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @shivamm-verma

**Comment by shivamm-verma** [comment]
Resolved Conflicts #80

**Comment by Rakesh9100** [comment]
Pls fix this. It is not appearing properly @shivamm-verma 

image

**Comment by shivamm-verma** [comment]
sorry. give me some time

**Pull request closed without merging**
