### PR TITLE
Added ASCII Value Calculator

### LINKED ISSUE #657: [Feature] Add ASCII Value Calculator
### Description

ASCII numbers prove to be really helpful in programming. This calculator would by a good addition to the website and people can come here and get the ASCII number of their desired characters.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by umangpatel8123**
# Fixes Issue🛠️

Closes #657 

# Description👨‍💻 

Created an ASCII value calculator which gives ASCII value of any character.

# How this has been tested✅

I tested it for different special characters like '$' '@' and ' / ' and its giving the correct output.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-05-27 at 9 45 30 AM
Screenshot 2024-05-27 at 9 45 52 AM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls rename your folder name to `ASCII-Value-Calculator` and also add a Readme file for your calculator in your folder @umangpatel8123

**Comment by umangpatel8123** [comment]
Okay

**Comment by umangpatel8123** [comment]
I have changed the name of folder kindly check it

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @umangpatel8123

**Pull request merged**
