### PR TITLE
Added the favicon to each calculator's page

### LINKED ISSUE #786: [Feature] Add the favicon to each calculator's page
### Description

Favicon is not there in all the calculators , It is only there in the home page 
@Rakesh9100 assign this issue to me I will make it in all the pages

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Meetjain1**
# Fixes Issue🛠️
closes #786 

Closes #

# Description👨‍💻 
solved favicon bug

# Type of change📄

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You have to add favicon to each calculator page but you didn't @Meetjain1

**Comment by Meetjain1** [comment]
@Rakesh9100 we have to add favicon.ico file in our root directory for this 

Or we have to paste the html code to all the pages of our calculators index.html page.

**Comment by Meetjain1** [comment]
> If we go with the first option that is to add in root directory, it is only applicable for the main page. Let's suppose I am opening 2D Distance Calculator, then favicon is not attached to that web page @Meetjain1

That's why I checked on stackoverflow etc
It should work on all pages while in root directory because it catches the favivon from their don't know why it is not working , that's why I add using java script dynamically but that too is not working I think

So, I think we have to add in all the pages .

**Comment by Rakesh9100** [comment]
Yes, the first option was great, but it is not working. You can explore using ChatGPT or Bard as well if there is any method else `favicon.png` is already present in `assets/images` using, which can be added to all the calculators manually @Meetjain1

**Comment by Meetjain1** [comment]
> Yes, the first option was great, but it is not working. You can explore using ChatGPT or Bard as well if there is any method else `favicon.png` is already present in `assets/images` using, which can be added to all the calculators manually @Meetjain1

Okk @Rakesh9100 will explore more on this or else we will manually add on each html page.

**Comment by Rakesh9100** [comment]
Any update @Meetjain1

**Comment by Meetjain1** [comment]
> Any update @Meetjain1

I will give you a final update by end of today.

**Comment by Meetjain1** [comment]
@Rakesh9100 hello, 
have a look on pr #1176 its working fine now .
will close this pr check it once . Thanks

**Comment by Rakesh9100** [comment]
There was no need to make new PR, you could make any changes in this only @Meetjain1

**Pull request closed without merging**
