### PR TITLE
Added GDP Calculator

### LINKED ISSUE #1117: [Feature] Add GDP Calculator
### Description

Gross domestic product is defined by the Organisation for Economic Co-operation and Development (OECD) as "an aggregate measure of production equal to the sum of the gross values added of all resident and institutional units engaged in production (plus any taxes, and minus any subsidies, on products not included in the value of their outputs." More simply, it can be defined as a monetary measure of the market value of final goods produced over a period of time, typically quarterly or yearly, that is often used to determine the economic performance of a region or country. Generally, growth of more than two percent indicates significant prosperous activity in the economy. On the other hand, two consecutive three-month periods of contraction may indicate that an economy is in recession.

Implementing a GDP calculator which uses Expenditure approach which takes parameters : 

* Personal Consumption
* Gross Investment
* Government Consumption
* Exports
* Imports

GDP =  personal consumption + gross investment + government consumption + net exports of goods and services

### Screenshots

Proposed protoype (UI will be improved)

gdp

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AnandK-pm**
# Fixes Issue🛠️

Closes #1117 

# Description👨‍💻 
* Added GDP calculator which uses the Expenditure approach for calculating GDP.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Deployed and tested using Vercel.
# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-06-10 200235

### CODE REVIEW

**Comment by AnandK-pm** [comment]
Video Preview
gdpcalc-gif

**Comment by Rakesh9100** [comment]
Pls rename your folder to `GDP-Calculator`, and make the changes accordingly by making the new commits in this same PR!

Also add README.md file for the calculator in your folder.

Do the changes in this same PR, don't close this!! @AnandK-pm

**Comment by Rakesh9100** [comment]
Rename your folder correctly, C should be capital @AnandK-pm

**Comment by AnandK-pm** [comment]
Can you please check now ??

**Pull request merged**
