### PR TITLE
Added dark mode to Contact page

### LINKED ISSUE #1894: [Style] Add dark mode to Contact page
### What's the style idea?

We need to improve

## Description
The Contact page currently does not support dark mode, which impacts user experience for those who prefer a dark interface or are using the website in low-light environments. Adding dark mode will improve accessibility and align with modern UI standards.

## Expected Outcome
- A toggle option to switch between light and dark modes on the Contact page.
- Proper color adjustments for:
  - Background.
  - Text content. 
- Ensure all elements remain readable and visually appealing in dark mode.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by isid555**
# Fixes Issue🛠️

Closes #1894 

# Description👨‍💻

This PR introduces dark mode support to the Contact page, improving user experience for those who prefer a dark interface or use the website in low-light environments. It includes a toggle option to switch between light and dark modes and ensures proper color adjustments for all elements.

# Type of Change📄

 
- [X] Style (non-breaking change which improves website style or formatting)
 

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

##In light mode
image
## In dark mode
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
No major change is seen, you can improve more by changing the color of Contact Us heading and Message Count text color as it is not visible properly when theme is changed @isid555

**Comment by isid555** [comment]
Yep I have mistakenly made CONTACT page update in the prev commit.....
Fine ...Ill make suitable Changes @Rakesh9100

**Comment by Rakesh9100** [comment]
Any update @isid555

**Comment by isid555** [comment]
I have made the required changes , Kindly review it @Rakesh9100

**Pull request merged**
