### PR TITLE
Made Bill Split Calculator responsive

### LINKED ISSUE #808: [Style] Make Bill Split Calculator responsive
### What would you like to share?

IMG_20240523_234848

### Additional information

In Split bill calculator, the background box is very small and the letters are getting out of it. So, I request you to assign me this issue. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Kashishgarg248**
# Fixes Issue🛠️

Closes #808 

# Description👨‍💻 

Made the Bill Split Calculator responsive.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls mention the issue number for which you have created this PR and also attach the screenshot of your work @Kashishgarg248

**Comment by Kashishgarg248** [comment]
Issue Number is #808 
photo

**Comment by Kashishgarg248** [comment]
Issue Number is #808 
WhatsApp Image 2024-06-01 at 22 21 01_f3864f9d
Screenshot (145)

**Comment by Rakesh9100** [comment]
Why have you changed the CSS for large devices, use media queries and fix the responsiveness only for small devices properly @Kashishgarg248

**Pull request merged**
