### PR TITLE
Added Remainder Calculator

### LINKED ISSUE #440: [Feature] Addition of a Remainder Calculator
### Description

I want to contribute to this project through JWOC'24 by adding a remainder calculator

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️
Closes #440 

# Description👨‍💻 

Added the all New Remainder Calculator which takes user input of dividend and divisor & gives the output as Remainder and Quotient. This Calculator will able to handle the NaN condition also by alerting the user

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

- [] Various Calculations done on it
- [] NaN condition Handled
- [] Division by Zero returns Infinity
- [] 0 / 0 Division also Handled
# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-02-03 194806

### CODE REVIEW

**Comment by Yuvraj960** [comment]
@Rakesh9100 , If any changes needed please just mention those, I will change them as fast as possible.

**Comment by Rakesh9100** [comment]
Pls add your calculator section in main `index.html` file @Yuvraj960

**Comment by Rakesh9100** [comment]
Pls add your calculator section in main `index.html` file and add a Readme of your calculator in your folder @Yuvraj960

**Comment by Rakesh9100** [comment]
Merged 🎉 @Yuvraj960

**Pull request merged**
