### PR TITLE
Added Light mode for the website

### LINKED ISSUE #515: [Feature] Add dark mode functionality to the website
### Description

Implementing dark mode functionality in the website will ease the user's switch between the modes and enhance the user experience. I am a SWOC'24 Mentor raising this issue for contributors.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #515 

# Description👨‍💻 

Added the changes needed for introducing the light mode for the website. Introduced the toggle switch in the navbar

# Type of change📄

- [X] New feature (Light mode for the website)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these:

1. Just make your changes and no indentation or any other changes in `index.html` file or any of the files.

2. Use some good animation or better theme toggling button.

3. 
image
Update the colors in the light theme of this text.

4. 
image
Modify the text colors as it is conflicting with the white background and not visible properly!!

@Yuvraj960

**Comment by Rakesh9100** [comment]
Any update on this PR @Yuvraj960

**Comment by Yuvraj960** [comment]
Work going on @Rakesh9100 , actually time gone for choosing the perfect colors for the font, found that. Now implementing on whole website. And for the animation of the toggle, I am looking for a JS file which will do this work for us. Will attach the screenshots tomorrow showing the progress of the Light mode in the PR

**Comment by Rakesh9100** [comment]
Okay, carry on @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, please view the changes. 
I have modified the code in accordance with changes stated by you above.

**Comment by Rakesh9100** [comment]
The animation which is added is lagging as you can also check the [deploy preview](https://deploy-preview-588--calcdiverse.netlify.app/).

Pls implement a good toggling button as mentioned before.

image
First mentioned change is not fixed as still unnecessary indentation changes are shown, if you are unable to then you can leave it and I will fix it. @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, first of all very sorry for the indentation issue. I didn't know how to resolve it. 
And secondly my animation is not lagging as I have checked in the deploy preview also:

https://github.com/Rakesh9100/CalcDiverse/assets/146326636/8c2064ec-ab49-4a5b-8aa0-33153379c68a

And can you please elaborate me, that what do you meant by the "good toggling button"? I am still stuck in this.

**Comment by Rakesh9100** [comment]
Okay, leave the indentation part. I will see it.

Animation change is lagging sometimes not every time.

Change the toggling button means implement some buttons like for examples:
1. Check this sun and moon toggling design [here](https://codepen.io/Umer_Farooq/pen/eYJgKGN).
2. You can check [this](https://medium.com/@anushka.war21/create-a-theme-toggle-button-in-html-4a2fc1fc9a2a).
3. Check different toggling design effects [here](https://dribbble.com/tags/toggle-button).

You can go with any one of these or any similar kind of button instead of using a simple toggle button. Hope this clears your doubt!! @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, I have made the new switch button, kindly check its implementation. I hope with the most recent commit I have done in the button, you like this type of presentation now.

**Comment by Rakesh9100** [comment]
1. Remove the animation of the website when changing the theme. I am not talking about the button, but the animation. Theme should change immediate when button is clicked.
2. Reduce the size of the button slightly.
3. This button should be present in every page navbars such as Contributors, FAQ, and Contact.
4. Once we change the theme let's say in home page, it should change the theme for the entirely website for every pages.

@Yuvraj960

**Comment by Yuvraj960** [comment]
Ok @Rakesh9100 , I understand all changes you need in the website, as there are many changes to be done in the website, It will take time, but I ensure you, I will give my best.

Kindly assign me one of my another issues in this project, as I have to work on them also along with this issue in progress.

**Comment by Rakesh9100** [comment]
Sure @Yuvraj960

**Comment by Rakesh9100** [comment]
Are you working @Yuvraj960

**Comment by Yuvraj960** [comment]
Yes @Rakesh9100 I am working, due to my weekend exam,  I didn't replied

**Comment by Yuvraj960** [comment]
@Rakesh9100, I need some help in this issue. Actually I am unable to understand the structure of the website. 
I have implemented the first 2 changes you demanded. 
But while adding the button to all the navbars, I am encountering an unknown issue. 
The issue is that navbar size is not fixed, it varies on different pages. I came to know about this issue when I added the dark-light switch button in all the navbars. The margins and paddings are not uniform through all website navbars.
While I was fixing the size of my button, the rest navbar button just left shift to an arbitrary place.

Can you please to some Favour for me.
Can you please open a separate issue for matching the light mode for the whole website,
And I merge the PR for the topic under Home-Page_Dark-Light_Theme-Design?

I am saying this only because I am unable to understand the file structure of the website, that which element of the website is contributing in which way to the pages of the website.

I can design the light mode for all the pages and write the code for them also, only problem is with linking of those pages, that I am currently confused in, how to do it.

**Comment by Yuvraj960** [comment]
@Rakesh9100 , please address me regarding this issue.

**Pull request closed without merging**
