### PR TITLE
Added Intelligence Calculator

### LINKED ISSUE #311: [Feature] Adding Intelligence Calculator
### Description

It is a calculator which tells how smart are you and gave the ip(Intelligency points )to user.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivam101203**
# Fixes Issue🛠️
#311 

Closes #311

# Description👨‍💻 
It is an intelligence finding calculator which is used to find the human intelligence with the help of IQ points .
These points describe the human intelligency between 0 to 150 and make accurate assumption of it.
# Type of change📄
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot from 2024-01-17 01-21-25

### CODE REVIEW

**Comment by shivam101203** [comment]
#311 done sir please merge it

**Comment by Rakesh9100** [comment]
Fill the PR description properly including Description section, Issue number closed, attach screenshot @shivam101203

**Comment by shivam101203** [comment]
please check and merge it

**Comment by shivam101203** [comment]
now

**Comment by Rakesh9100** [comment]
Add screenshot of your calculator to the PR description @shivam101203

**Comment by shivam101203** [comment]
please merge it now

**Comment by shivam101203** [comment]
done

**Comment by shivam101203** [comment]
sir i have done all works please merge it

**Comment by Rakesh9100** [comment]
Add a Readme for your calculator inside your folder without closing this PR @shivam101203

**Comment by shivam101203** [comment]
sir it is not possible please help

**Comment by Rakesh9100** [comment]
Okay hold on @shivam101203

**Comment by shivam101203** [comment]
Sir it is necessary to add a readme file

**Comment by shivam101203** [comment]
Thanks sir for help

**Comment by Rakesh9100** [comment]
> Sir it is necessary to add a readme file

Yes, from next time if you are contributing to this repo for adding any new calculator, then add Readme.md file as well @shivam101203

**Comment by shivam101203** [comment]
Okk sir I will keep in mind from next time

**Comment by shivam101203** [comment]
Please merge it

**Comment by Rakesh9100** [comment]
Suggestion:- Learn how to resolve conflicts and edit the files without closing a Pull Request!!

Merged!! Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @shivam101203

**Pull request merged**
