### PR TITLE
Added additional functionalities in the basic calculator for the point .

### LINKED ISSUE #634: [Feature] Add point functionality to Basic Calculator
### Description

If the innerText of the result field is blank and the user clicks . then result's innerText should be displayed as 0. 
Please assign me this task under GSSoC'24. 

### Screenshots

Before this feature the result innerText is this 
image

After adding the feature if point is at the zero index  0 will be displayed before . (point) so the resultant innerText of the result will become **0.** 
image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivangi-singhjha**
# Fixes Issue🛠️

Closes #634

# Description👨‍💻 

Added additional functionalities in the basic calculator for the point "."

# Type of change📄
- [] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot1
Screenshot2
Screenshot3

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Why have you added a new folder, you have to make changes in the existing one and fix the issue @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
Sir so we have to make changes in the existing Basic-Calculator folder??

**Comment by shivangi-singhjha** [comment]
image

Sir but here its written to add your code in the newly created folder.
Sir I am getting confused. Kindly help sir🙏

**Comment by shivangi-singhjha** [comment]
Sir @Rakesh9100 are the changes needed to be done in the existing Basic-Calculator Folder??

**Comment by Rakesh9100** [comment]
If you are adding a new calculator which is not present in the repository or website, then you have to create a new folder and follow the process.

But if an issue is raised to fix any changes to the existing calculator, then you have to make the changes to the same calculator folder files!
Hope this clears your confusion @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
Ok Sir, Thank You!
I will correct the problem and generate a new PR

**Comment by shivangi-singhjha** [comment]
Sir I have created a new PR #820
Kindly look into it 🙏

**Pull request closed without merging**
