### PR TITLE
UI appearance of every calculator

### LINKED ISSUE #369: [Style] UI appearance of every calculator
### What's the style idea?

We need to improve the user interface of the appearance of the each calculator. You can check it out.

https://github.com/Rakesh9100/CalcDiverse/assets/117648930/b9ea1e41-f1f2-4c77-9fe4-471f349fb1a6

Hey @Rakesh9100 , I hope this will catch you fine, let me know if any improvement is required, or I am ready to commit.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Shantanu-Meta**
# Fixes Issue🛠️

Closes #369 

# Description👨‍💻 
Updated as per the requirement of admin

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
update

### CODE REVIEW

**Comment by Shantanu-Meta** [comment]
Hey @Rakesh9100 , as per your demand, i have made changes and resolved the UI based issues, now it looks fine.
Hope this sounds good ?

**Comment by Rakesh9100** [comment]
image

Scroll to Top button is hidden being overlapped. Pls do fix.
And also do some change in source code GitHub logo with some animations and hover effect to it!! @Shantanu-Meta

**Comment by Shantanu-Meta** [comment]
Yah, I have fixed that, Now check it once.

**Comment by Rakesh9100** [comment]
[Contributors](https://deploy-preview-436--calcdiverse.netlify.app/assets/contributors/contributor) page is showing errors with overflowing, pls do fix @Shantanu-Meta

**Comment by Shantanu-Meta** [comment]
Done @Rakesh9100

**Comment by Shantanu-Meta** [comment]
Hey @Rakesh9100 , can u check it ?

**Comment by Rakesh9100** [comment]
Nice work, Appreciated!! ✨

Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Shantanu-Meta

**Comment by Rakesh9100** [comment]
Nice work, Appreciated!! ✨

Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Shantanu-Meta

**Pull request merged**
