### PR TITLE
Added Image Resolution Calculator

### LINKED ISSUE #1307: [Feature] Add Image Resolution Calculator
### Description

We need to implement an Image Resolution Calculator tool that computes the resolution of an image based on its dimensions and vice versa. This tool will be helpful for users who need to determine the resolution of an image for printing or digital display purposes.

Alternative Solutions or Features Considered:

Aspect Ratio Calculation: We can add an option to calculate the aspect ratio of an image based on its dimensions.
Unit Conversion: In addition to pixels, we can allow users to input dimensions in other units such as centimeters or inches, and provide the resolution in square meters or square feet accordingly.
Advanced Options: We can explore adding advanced options such as DPI (dots per inch) calculation or support for different color spaces.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
# Fixes Issue🛠️

Closes #1307 

# Description👨‍💻

Implemented an Image Resolution Calculator tool that computes the resolution of an image based on its dimensions (width and height in pixels) and DPI (dots per inch). This tool will help users determine the resolution of an image for printing or digital display purposes.

Key features include:
- Calculation of image resolution in megapixels.
- User input fields for width, height, and DPI.
- Display of the calculated resolution in megapixels.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your calculator part in the main `index.html` file to display it on the website by making the new commits in this same PR @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
> Pls add your calculator part in the main `index.html` file to display it on the website by making the new commits in this same PR @thevijayshankersharma

I didn't get. Can you elaborate ?

**Comment by Rakesh9100** [comment]
You have to add your calculator part in this [File](https://github.com/thevijayshankersharma/CalcDiverse/blob/Image-Resolution-Calculator/index.html) @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
@Rakesh9100 Done.

**Pull request merged**
