### PR TITLE
 Added Gravitational Force Calculator

### LINKED ISSUE #982: [Feature] Add Gravitational Force Calculator
### Description

It will be a calculator which will calculates the gravitational force between two masses  if the distance between the masses is given.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anshika14528**
# Fixes Issue🛠️

Closes #982

# Description👨‍💻 

Added a Gravitational Force Calculator which calculates the gravitational force between two body if masses of the body and the distance between them is given.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-06-01 at 5 50 08 PM

### CODE REVIEW

**Comment by Anshika14528** [comment]
@Rakesh9100 Sir, Please review it and please assign me my next issue.

**Comment by Rakesh9100** [comment]
Pls add your calculator folder inside the Calculators folder and not in the root directory, make the new commits in this same PR @Anshika14528

**Comment by Rakesh9100** [comment]
image

Why the text is coming like this for large screens that is laptop, pls fix and background also should fit the full screen properly @Anshika14528

**Comment by Anshika14528** [comment]
Screenshot 2024-06-02 at 1 34 19 AM
I have made the changes please review it 
Sorry for the inconvenience

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @Anshika14528

**Comment by Anshika14528** [comment]
Thankyou so much @Rakesh9100 sir 
please assign me issue #987

**Pull request merged**
