### PR TITLE
Added 3D Surface Plotter Calculator

### LINKED ISSUE #1245: [Feature]  3D Surface Plotter
### Description

@Rakesh9100 

 3D Surface Plotter
### Outputs: 3D plot of the surface, key points of interest (e.g., maxima, minima).
Screenshot 2024-06-07 003549

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pandeyji711**
# Fixes Issue🛠️

Closes #1245 

# Description👨‍💻

- Added : Plot 3D surfaces for given functions.
- Inputs: Function definition in two variables (x, y).
- Outputs: 3D plot of the surface, key points of interest (e.g., maxima, minima).

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these by making the new commits in this same PR @pandeyji711 

1. Rename your folder to `3D-Surface-Plotter-Calculator` and make the necessary changes.
2. Rename `app.js` to `script.js`.
3. Add a README.md file of your calculator in your folder.

**Comment by pandeyji711** [comment]
@Rakesh9100 ok

**Comment by pandeyji711** [comment]
> Pls work on these by making the new commits in this same PR @pandeyji711
> 
> 1. Rename your folder to `3D-Surface-Plotter-Calculator` and make the necessary changes.
> 2. Rename `app.js` to `script.js`.
> 3. Add a README.md file of your calculator in your folder.

@Rakesh9100  
### I have done all necessary changes.

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Pull request merged**
