### PR TITLE
Added Baye's Theorem Calculator

### LINKED ISSUE #342: [Feature] Adding Baye's Theorem Calculator
### Description

This calculator allows users to input the probability of A (P(A)), the probability of B given A (P(B|A)), and the probability of not A (P(~A)). It then calculates and displays the probability of A given B (P(A|B)).

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #342 

# Description👨‍💻 
he Bayesian Theorem Calculator is a web application designed to calculate the probability of an event A given that event B has occurred. Users can input the probability of A (P(A)), the probability of B given A (P(B|A)), and the probability of not A (P(~A)). The calculator then computes and displays the probability of A given B (P(A|B)).

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by AbhineshJha** [comment]
Forgot to add screenshot , so just added.!! 
have a review @Rakesh9100

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @AbhineshJha

**Comment by AbhineshJha** [comment]
done @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged 🎉 @AbhineshJha

**Comment by AbhineshJha** [comment]
ok @Rakesh9100

**Pull request merged**
