### PR TITLE
Added an About Us Page

### LINKED ISSUE #488: [Feature] Add About Us Page
### Description

while going across the website ,I saw that the "About Us" page was missing . So I would like to add it into the navigation bar rather than the content which is written on the homepage which makes it look ugly.

### Screenshots

Screenshot (822)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Soumya6Tiwari**
# Fixes Issue🛠️

Closes #488 

# Description👨‍💻 

While going across the website, I noticed that the About Us page was missing. So
 I decided to add an About Us page into the website.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (885)
Screenshot (884)

### CODE REVIEW

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100 Kindly update the status of my PR

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  kindly review my PR

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  sir kindly update the status of the PR ,and let me know if it is ok or not . It has already been more than 3 days for the pull request.

**Comment by Rakesh9100** [comment]
Pls work on these changes:

1. About Page looks so clumsy and congested, pls enhance and design the UI.
2. Include the navbar and footer sane as homepage.
3. Don't delete the paragraph of the main page.

@Soumya6Tiwari

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  ok I shall make the amendments

**Comment by Rakesh9100** [comment]
Status of your changes @Soumya6Tiwari

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  you can reassign it to someone else

**Pull request closed without merging**
