### PR TITLE
Added Net Worth Calculator

### LINKED ISSUE #559: [Feature] Add Net Worth Calculator
### Description

Input the Financial Assets of the user along with his/her liabilities to calculate it's NetWorth. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by surendar-05**
# Fixes Issue🛠️
 Closes #559  

# Description👨‍💻 

This project aims to develop a user-friendly net worth calculator tool. A net worth metric is a crucial indicator of your overall financial health, and this calculator will empower users to track and understand their financial standing easily.

# Type of change📄

I added one feature called Net Worth Calculator

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on all the values within range

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
output

### CODE REVIEW

**Comment by surendar-05** [comment]
Issue Number #559

**Comment by surendar-05** [comment]
I am contributed under GSSOC'24

**Comment by Rakesh9100** [comment]
Pls add the Readme file of your calculator and also update your calculator in main `index.html` file to display on the website @surendar-05

**Comment by surendar-05** [comment]
I added main index.html file

**Comment by surendar-05** [comment]
I added ReadMe file for this project

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @surendar-05

**Comment by surendar-05** [comment]
Thanks bro!!

**Pull request merged**
