### PR TITLE
Made CGPA Percentage Calculator responsive

### LINKED ISSUE #838: [Style] Make CGPA Percentage Calculator responsive
### Description

 CGPA To percentage calculator is not responsive so In mobile view it is not clearly visible

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by agastya3636**
# Fixes Issue🛠️

Closes #838 

# Description👨‍💻 

Make CGPA Percentage Calculator responsive by making changes in css.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

image

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls fill all the details in the PR template properly for every PR such as Description👨‍💻, How this has been tested✅ @agastya3636

**Comment by agastya3636** [comment]
@Rakesh9100 what I have to write in that please explain

**Comment by Rakesh9100** [comment]
Description👨‍💻 is still empty, make the habit of filling all the details properly @agastya3636

**Comment by agastya3636** [comment]
@Rakesh9100 Sorry for that from next time I will do properly

**Comment by agastya3636** [comment]
@Rakesh9100 please review it

**Pull request merged**
