### PR TITLE
Added Cricket Calculator

### LINKED ISSUE #437: Adding Cricket Calculator
### Description

I want to add a cricket calculator in which it calculates following :
1.Batsman Strike Rate
2.Bowlers Economy Rate
3.Required Run Rate
4.Projected Score
5.Target

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by GarvVirmani**
# Fixes Issue🛠️
#437 

Closes #437 

# Description👨‍💻 
Cricket Related Terms Calculator.

# Type of change📄

- [✅] New feature (non-breaking change which adds functionality)

# How this has been tested✅
By calculating manually and was correct in edge cases also.

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷

IMG_20240124_153524
<br>
IMG_20240124_153539
<br>
IMG_20240124_153558

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Handle the NaN values by displaying alert when clicked on `Calculate` without entering any value @GarvVirmani

**Comment by GarvVirmani** [comment]
@Rakesh9100 Resolved NaN by an Alert.

**Comment by GarvVirmani** [comment]
@Rakesh9100 Done 👍

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @GarvVirmani

**Comment by GarvVirmani** [comment]
@Rakesh9100 Thanks 🙏

**Pull request merged**
