### PR TITLE
Enhanced social media icons with dynamic glow effect

### LINKED ISSUE #673: [Style] Enhance social media icons with dynamic glow effect
### Description

Adding a feature like a social media logo popup with glowing effects in different colors could enhance user engagement and interactivity on your platform. 
Right now it looks good right now but I can be enhanced with some tweaks by adding Dynamic Glow Effect , Hover Animation.
Screenshot 2024-05-11 155441
Screenshot 2024-05-11 155450

### Screenshots

https://github.com/Rakesh9100/CalcDiverse/assets/132978008/94cffa00-ffc0-4939-9d5b-026f7fd6d2be

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ankitsinghbisht8**
# Fixes Issue🛠️

Closes #673 

# Description👨‍💻 

Integrated a feature where social media logos pop up with glowing effects in various colors could significantly amplify user engagement and interaction within your platform.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I've thoroughly tested the changes across different web browsers, including Chrome, Microsoft Edge, and Firefox, ensuring compatibility and smooth functionality. Additionally, I've verified the responsiveness of the feature, confirming that it adapts well across various devices and screen sizes.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-05-24 130645
Screenshot 2024-05-24 130652
Screenshot 2024-05-24 130657

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Add this same effect in every page such as About, Contributors, etc. @ankitsinghbisht8

**Comment by Rakesh9100** [comment]
Are you working @ankitsinghbisht8

**Comment by ankitsinghbisht8** [comment]
Yeah, I'm on it

**Review by ankitsinghbisht8 — COMMENTED** [review]
made changes in the social links in the footer section in all the pages including main page, contact page, about page, contributor page, faq page

**Review by ankitsinghbisht8 — COMMENTED** [review]
.

**Comment by Rakesh9100** [comment]
Reduce the gap between the icons, and also make the hover transition smooth @ankitsinghbisht8

**Comment by Rakesh9100** [comment]
Are you working or not @ankitsinghbisht8

**Comment by ankitsinghbisht8** [comment]
yes I'm on it. I have my semester exams so that's what there are some time constraints.
I'll fix it asap

**Review by ankitsinghbisht8 — COMMENTED** [review]
Reduced the gap between the icons, and also made the hover transition smooth

**Comment by Rakesh9100** [comment]
Pls pull the latest changes once to your branch to avoid the conflict @ankitsinghbisht8

**Comment by Nihal4777** [comment]
@Rakesh9100 This can be merged. Labels need to be added.

**Pull request merged**
