### PR TITLE
Added Perfect Number Calculator

### LINKED ISSUE #771: [Feature] Add Perfect Number Calculator
### Description

@Rakesh9100 Currently the website doesn't have a perfect number calculator 
a perfect number is the number whose divisors (except itself) add up to itself.
 For example,. 28 is a perfect number. Its proper divisors are {1, 2, 4, 7, 14} and 1 +2 +4 +7 +14 = 28
i can add this calculator to the website.
Kindly assign me this issue under GSSOC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vedanshipathak**
# Fixes Issue🛠️

Closes #771 

# Description👨‍💻 

A perfect number calculator checks if the number is perfect or not.
A perfect number is a positive integer that is equal to the sum of its positive proper divisors, that is, divisors excluding the number itself. For instance, 6 has proper divisors 1, 2 and 3, and 1 + 2 + 3 = 6, so 6 is a perfect number.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-05-24 133449

### CODE REVIEW

**Comment by vedanshipathak** [comment]
@Rakesh9100 should i add it on the website itself?

**Comment by Rakesh9100** [comment]
Yes, you can display below the text `It is a perfect number!` @vedanshipathak

**Comment by vedanshipathak** [comment]
Now it displays how it is a perfect number and how it is not
Screenshot 2024-05-25 220243
Screenshot 2024-05-25 220253

**Comment by Rakesh9100** [comment]
Good, Merged 🎉 @vedanshipathak

**Pull request merged**
