### PR TITLE
Added Root Mean Square Calculator

### LINKED ISSUE #1328: [Feature] Add Root Mean Square Calculator
### Description

This calculator will allow users to input a set of numbers and compute the Root Mean Square (RMS) value.

### Screenshots

image

I will style it afterwards. This is the working model

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Praneeth-2602**
# Fixes Issue🛠️

Closes #1328 

# Description👨‍💻

Added the Root Mean Square calculator that calculated the RMS value of a given set of numbers. I adopted a neumorphism style.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Praneeth-2602** [comment]
@Rakesh9100 Done sir!!

**Comment by Rakesh9100** [comment]
Why have you closed that PR, I told you to make the changes in that same PR @Praneeth-2602

**Comment by Praneeth-2602** [comment]
I didn't close that... There were merge conflicts.

**Comment by Rakesh9100** [comment]
You should learn to resolve those conflicts and not directly close the PR. Also in this, you have not kept the calculator folder name as mentioned in the comment in the previous PR @Praneeth-2602

**Comment by Praneeth-2602** [comment]
sorry i will try not to repeat this again! I will learn to solve the merge conflicts

**Comment by Rakesh9100** [comment]
Add a `README.md` file of your calculator in your folder @Praneeth-2602

**Pull request merged**
