### PR TITLE
Added the Exponet calculator

### PR DESCRIPTION
**Pull request by Parmesh119**
Issue no #174  

# Description👨‍💻 

Exponent Calculator: Which takes two numbers X and Y and then calculate X<sup>Y</sup>.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

First I have tested it on my PC and It will work correctly on my PC.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
exponent

### CODE REVIEW

**Comment by Parmesh119** [comment]
@Rakesh9100, I have added the exponent calculator. Please Check it out and If It is fine then please merge to the main branch.

**Comment by Rakesh9100** [comment]
Pls keep your folder name as `Exponent-Calculator` by using hyphen.

Handle NaN value in the calculator as now when clicking on Calculate without entering any number, it is showing one which should not @Parmesh119

**Comment by Parmesh119** [comment]
@Rakesh9100 Now please check it.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Parmesh119

**Comment by Parmesh119** [comment]
@Rakesh9100, I also need your help regarding GSoC.
Can we talk on LinkedIn or on Twitter?

**Pull request merged**
