### PR TITLE
Added Finance Calculator

### LINKED ISSUE #1785: [Feature] Add Finance Calculator
#### Description

We aim to add a financial calculator to our CalciDiverse app. This feature will allow users to perform key financial calculations, including:

- **Loan Payment Calculator**: Calculate monthly payments based on loan amount, interest rate, and term.
- **Future Value Calculator**: Estimate the future value of investments with given interest rates and compounding periods.
- **Present Value Calculator**: Determine the present worth of future sums.
- **Mortgage Payment Calculator**: Compute monthly mortgage payments, including principal and interest.

#### Requirements

- Implement calculations using JavaScript.
- Design a responsive HTML interface for user input and output.
- Ensure input validation and error handling.

#### Tasks

1. Develop the UI for input and output.
2. Write JavaScript functions for calculations.
3. Integrate calculations with the UI.
4. Test for responsiveness and accuracy.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by priyashuu**
# Fixes Issue🛠️

Closes #1785 

# Description👨‍💻

This Finance Calculator is a comprehensive web tool designed to assist users with crucial financial calculations. It offers two main functionalities: calculating the future value of an investment and determining the monthly payments for a loan. The calculator provides an intuitive user experience, allowing users to input their principal amounts, interest rates, and investment or loan terms to obtain precise results.

With its clean design and easy-to-use interface, built using HTML, CSS, and JavaScript, this calculator simplifies complex financial assessments. It's ideal for anyone looking to plan their investments, manage loans, or make informed financial decisions.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

finaceCalci

### CODE REVIEW

**Comment by priyashuu** [comment]
@Rakesh9100  Sir, Could you please review the code and let me know if any changes are needed? Once reviewed, kindly merge the changes.

Thank you!

**Comment by priyashuu** [comment]
@Rakesh9100 Sir, Could you please review the code and let me know if any changes are needed? Once reviewed, kindly merge the changes.

Thank you!

**Comment by priyashuu** [comment]
@Rakesh9100 Sir, Could you please review the code and let me know if any changes are needed? Once reviewed, kindly merge the changes.

**Comment by Nihal4777** [comment]
@priyashuu Please Correct your URL in main index file.
image

 Also add some empty field validations.
image

**Comment by priyashuu** [comment]
@Rakesh9100 is it okay sir ?
Screenshot 2024-08-10 141508

**Comment by priyashuu** [comment]
Hi @Rakesh9100 

As a GGSOC contributor, I want to ensure that my pull request is reviewed and merged before the deadline, after 7 PM, no PRs will be counted . I understand you are busy, but if you could review the changes, let me know if any adjustments are needed, and merge the PR, I would greatly appreciate it. Your assistance would be immensely helpful to me.

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed  & can be merged.

**Comment by priyashuu** [comment]
@Rakesh9100 Thank you so much sir🫡

**Comment by priyashuu** [comment]
@Rakesh9100 Please assign level 3 as the level for a new calculator is always given that label in that repo.

**Comment by priyashuu** [comment]
@Rakesh9100 please merge it ....🥹🙏

**Comment by Nihal4777** [comment]
> @Rakesh9100 please merge it ....🥹🙏
Don't worry. We are on way of merging PRs.

**Pull request merged**
