### PR TITLE
Added Beta Function Calculator

### LINKED ISSUE #1173: Beta Gamma Calculator
### Description

For solving sums of multivariate calculus, many college students including myself have to go through the hassle of inputting the beta function in expanded form in our scientific calculators. Instead of that if we make a beta function calculator that takes 2 inputs and gives direct result of Beta(a,b) and Gamma(a,b) our task can become simpler!

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by snigudkar**
# Fixes Issue🛠️

Closes #1173 

# Description👨‍💻

For solving sums of multivariate calculus, many college students including myself have to go through the hassle of inputting the beta function in expanded form in our scientific calculators. Instead of that if we make a beta function calculator that takes 2 inputs and gives direct result of Beta(a,b) our task can become simpler! The calculator uses gamma function (which is an inbuilt function of math.js) to calculate the value of ß(m,n).

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/146969559/54aeb1e8-631d-4a68-9782-266f650f226d

### CODE REVIEW

**Comment by Nihal4777** [comment]
@snigudkar Add empty field validations. Also check if you could make it responsive.
image

**Comment by snigudkar** [comment]
Why does everything look wrong on your end? I tried it using chrome and edge both browser and it looks correct on my device. Also i did not understand what you mean by "making it responsive". Everything is responsive. I have showed the demo in the video.

**Comment by snigudkar** [comment]
okay i will look into that

**Comment by Rakesh9100** [comment]
Are you working on the mentioned comment @snigudkar

**Comment by Rakesh9100** [comment]
Are you working on the mentioned comment and mention the issue number for this PR @snigudkar

**Comment by snigudkar** [comment]
Working on it. Please give me some more time. Also how can I test my code for a mobile's aspect ratio?

**Comment by Rakesh9100** [comment]
You can check your calculator in this [Deploy Preview](https://deploy-preview-1535--calcdiverse.netlify.app/) and test the responsiveness, make new commits and again this Deploy preview will change according to the new changes @snigudkar

**Comment by snigudkar** [comment]
okay I will work on it

**Pull request merged**
