### PR TITLE
Added Cyclomatic Complexity Calculator

### LINKED ISSUE #1222: [Feature] Add Cyclomatic Complexity Calculator
### Description

It calculates the Cyclomatic Complexity of the code, a metric used to measure the structural complexity of software by counting the number of linearly independent paths through the code's control flow graph.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vimore03**
# Fixes Issue🛠️

Closes #1222 

# Description👨‍💻

The cyclomatic complexity calculator uses three different methods to calculate the cyclomatic complexity.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### Method 1:
image

### Method 2:
image

### Method 3:
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Please add your calculator part in `calculators.json` file by making the new commits in this same PR @vimore03

**Comment by vimore03** [comment]
Hi sir, I have updated the calculators.json file as per your instructions.
Kindly review the changes

**Comment by Rakesh9100** [comment]
### Make the calculator fully responsive for every screen @vimore03 

image

**Comment by vimore03** [comment]
Hi sir, i have made the necessary to make the code responsive. Kindly
review it

**Pull request merged**
