### PR TITLE
Enhanced Explore Calculators button

### LINKED ISSUE #894: [Style] Enhance Explore Calculators button
### What's the style idea?

Adding a glowing button effect to the button is a great way to enhance the user experience on the website. It can improve the button's visibility, especially for users with certain visual impairments, and add a touch of interactivity that can make the process feel more engaging.
I'd like to propose adding a subtle glowing button effect to the Explore Calculators button. This could be implemented with pure CSS and would involve adding a hover effect that creates a glowing animation around the button when a user hovers their mouse over it.
I think this would be a great way to [ e.g. improve the button's visibility, make the login process more engaging] and I'm confident that I can implement this change using my skills in CSS. I've been working on similar effects recently, and I'm confident I can deliver a high-quality solution.

Here's are some samples of the button:
Screenshot (6891)
Screenshot (6892)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sakshi261203**
# Fixes Issue🛠️

Closes #894 

# Description👨‍💻 

This change adds a glowing button effect to the "Explore Calculators" button on the CalcDiverse website. The glowing effect is implemented using pure CSS and is triggered when the user hovers over the button. This enhancement aims to improve the button's visibility and make the user experience more engaging and interactive.
1. Added CSS styles to create a glowing effect for the "Explore Calculators" button.
2. Included a hover effect that animates the glow around the button.
3. Ensured the glow animation runs smoothly with a keyframe animation.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

To ensure the glowing button effect works correctly, the following tests were conducted:
1. Opened the CalcDiverse website in multiple browsers (Chrome, Firefox, Edge) to verify the appearance of the glowing effect.
2. Confirmed that the button displays the glow animation smoothly when hovered over

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (6917)

Screenshot (6914)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
### Why it went down the screen, pls fix @sakshi261203 
image

**Comment by sakshi261203** [comment]
Ok Sir
Do I need to create new pull request again?

**Comment by Rakesh9100** [comment]
Are you working or not, if not I will close the PR and issue @sakshi261203

**Comment by sakshi261203** [comment]
Yes I am working on it , I will complete the task by tomorrow. ...

**Comment by sakshi261203** [comment]
I had pushed new changes and make commits....
Is there anything that left?

**Pull request merged**
