### PR TITLE
Added Complex Number Calculator

### LINKED ISSUE #497: [Feature] Adding Complex Number Calculator
### Description

I would like to add a complex number calculator which Handles complex numbers and their operations, such as addition, subtraction, multiplication, and division, and provides both rectangular and polar forms of the result.
If u like this idea, then please assign me this under JWOC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Aashi19234**
# Fixes Issue🛠️

Closes #497 

# Description👨‍💻 
I have added a complex number calculator which performs operations on complex numbers.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I have run the program in my local system and performed every operations and it works fine.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/140010647/0577db55-06d7-4917-99bf-434f1ed0402c

### CODE REVIEW

**Comment by Aashi19234** [comment]
@Rakesh9100 I have made the desired changes as you asked, and i had to issue a new PR because of some issues with previous PR. Please review my PR.

**Comment by Rakesh9100** [comment]
Hey @Aashi19234 Why are you closing the PRs again and again, you can make the suggested changes in the same opened PR only!!

**Comment by Aashi19234** [comment]
Sorry @Rakesh9100 , previous PR was showing some issues in my system, thats why i had to open a new PR.

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Aashi19234

**Pull request merged**
