### PR TITLE
Added Running Pace Calculator

### LINKED ISSUE #840: [Feature] Add Running Pace Calculator
### Description

The Running Pace Calculator can estimate the pace for a variety of activities, including running, walking, and biking. The calculator can also be used to estimate the time taken or distance traveled with a given pace and time or distance.

The Calculator will take in **Time in HH:MM:SS** and **Distance** in desired units _(Kilometers, Miles, Meters, Yards)_, including some predefined units like _Marathon, Half-Marathon etc._, and calculate the Running Pace.

The same calculator can be again used to calculate time and distance using Pace and Distance & Pace and Time, if provided, respectively.

Please assign me this Issue under the Label of **GSSoC '24 and add label 'level 1'/'level 2'/'level 3' according to your discretion**. I will use HTML, CSS and JavaScript to implement it. Thank you!

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by priyavratamohan**
# Fixes Issue🛠️

Closes #840 

# Description👨‍💻 

The Running Pace Calculator can estimate the pace for a variety of activities, including running, walking, and biking. The calculator can also be used to estimate the time taken or distance traveled with a given pace and time or distance.

The Calculator will take in Time in HH:MM:SS and Distance in desired units (Kilometers, Miles, Meters, Yards), including some predefined units like Marathon, Half-Marathon etc., and calculate the Running Pace.

The same calculator can be again used to calculate time and distance using Pace and Distance & Pace and Time, if provided, respectively.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

This code has been tested to be responsive, and tested by adding different kinds of out-of-range values to it, and then rectified accordingly.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

screenshot1
screenshot2

### CODE REVIEW

**Comment by priyavratamohan** [comment]
Can you please add the necessary labels, like - the Label of GSSoC '24 and label 'level 1'/'level 2'/'level 3' according to your discretion before merging? Thank you!

**Comment by priyavratamohan** [comment]
Can you please add the necessary labels, like - the Label of GSSoC '24 and label 'level 1'/'level 2'/'level 3' according to your discretion before merging? Thank you!

**Comment by Rakesh9100** [comment]
### Why unnecessary scrollbars images are there in the UI, pls do fix @priyavratamohan 

image
image
image

**Comment by Rakesh9100** [comment]
And also attack some screenshots of your calculations @priyavratamohan

**Comment by priyavratamohan** [comment]
I fixed the unnecessary scroll bars, and here's the screenshots of calculations - 

_Pace Calculation_
rpcpace

_Time Calculation_
rpctime

_Distance Calculation_
rpcspeed

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @priyavratamohan

**Pull request merged**
