### PR TITLE
Added Net Salary Calculator

### LINKED ISSUE #312: [Feature] Adding Net Salary Calculator
### Description

Users can input salary details, bonuses, benefits, and deductions, receiving real-time updates on their CTC and also their salary structure.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pranjal12-web**
# Fixes Issue🛠️

Closes #312 

# Description👨‍💻 
Added a Net Salary calculator which calculates net salary from the entered CTC value

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
tested locally on my machine

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

#Screenshot :
Screenshot

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Add a screenshot in the your Readme file as well as PR description.

Also, Rename your folder to Net-Salary-Calculator and make the necessary changes @pranjal12-web

**Comment by Rakesh9100** [comment]
Add a screenshot in your Readme file as well as PR description.

Also, Rename your folder to `Net-Salary-Calculator` and make the necessary changes @pranjal12-web

**Comment by pranjal12-web** [comment]
@Rakesh9100 Kindly check

**Comment by Rakesh9100** [comment]
Merged 🎉 @pranjal12-web

**Pull request merged**
