### PR TITLE
Added Infix Prefix Postfix Calculator

### LINKED ISSUE #375: [Feature] Adding Infix Prefix Postfix Calculator
### Description

I would like to add a infix expression to postfix expression converter feature to this project. Please assign me under JWOC'24 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by thesri**
# Fixes Issue🛠️

Closes #375 

# Description👨‍💻 
Created infix to postfix, postfix to infix, infix to prefix, .... convertor 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

i have run the project and verifed it in my own computer

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
WhatsApp Image 2024-01-27 at 14 55 56_72fb6b01

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Add some conversion examples screenshots @thesri

**Comment by thesri** [comment]
> Add some conversion examples screenshots @thesri

image
image
image
image
image
image
i have attached examples for each conversion please check

**Comment by Rakesh9100** [comment]
Add a Readme file of your calculator in your folder @thesri

**Comment by thesri** [comment]
Please Check @Rakesh9100 added the readme file

**Comment by Rakesh9100** [comment]
Merged 🎉 @thesri

**Pull request merged**
