### PR TITLE
Added 404 error page

### LINKED ISSUE #1459: [Feature] Add 404 error page
### Description

When unknown URL is visited, 404 error page is missing for better user interaction -

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by PratikMane0112**
# Fixes Issue🛠️

Closes #1459 

# Description👨‍💻

Added 404.html page & .htaccess to render it when random path requested.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### Desktop view -
Screenshot 2024-07-07 001538

### Mobile view -
Screenshot 2024-07-07 001553

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Rakesh9100** [comment]
Provide some good GIF or animation in the place of logo @PratikMane0112

**Comment by PratikMane0112** [comment]
> Provide some good GIF or animation in the place of logo @PratikMane0112

@Rakesh9100 Done

**Comment by PratikMane0112** [comment]
@Rakesh9100 plz review PR.

**Pull request merged**
