### PR TITLE
Added Niven Number Calculator

### LINKED ISSUE #969: [Feature] Add Niven Number Calculator
### Description

A number that is divisible by the sum of its digits is called a niven number.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Nayanika1402**
# Fixes Issue🛠️

Closes #969 

# Description👨‍💻 

This calculator checks whether the given number is niven or not.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

The functionality of the calculator is tested with various examples.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-06-01 203757

### CODE REVIEW

**Comment by Nayanika1402** [comment]
@Rakesh9100 I have closed the previous PR and made a fresh one.Kindly review it.

**Comment by Rakesh9100** [comment]
Let's say 81 is a niven number, so pls show the solution as well below the text `81 is a Niven number` that how it is Niven @Nayanika1402

**Comment by Nayanika1402** [comment]
@Rakesh9100 I have done the requested changes.Kindly review it.

**Comment by Rakesh9100** [comment]
Merged 🎉 @Nayanika1402

**Pull request merged**
