### PR TITLE
Added quadratic calculator

### LINKED ISSUE #109: Adding quadratic equations root calcuator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a calculator that calculates the roots of a quadratic equation.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by saurav2208**
# Fixes Issue🛠️

Closes #109 

# Description👨‍💻 

Added a quadratic calculator that calculates the roots of a quadratic equation
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# This has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/125905089/0dac0e60-5e70-4ef0-ae56-fc71ce0d126d

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @saurav2208

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts and add a `README` file in your calculator folder @saurav2208

**Comment by saurav2208** [comment]
> Pls resolve the conflicts and add a `README` file in your calculator folder @saurav2208

I have done all the required changes

**Comment by Rakesh9100** [comment]
Add some good background the the entire screen and enhance UI @saurav2208

**Comment by Rakesh9100** [comment]
@saurav2208 Are you working

**Comment by saurav2208** [comment]
> @saurav2208 Are you working

Yes yes I am working on it. Will be done by tomorrow.

**Comment by saurav2208** [comment]
@Rakesh9100 I have improved the UI of the page.
Screenshot quadratic-1
Screenshot quadratic-2

**Comment by Rakesh9100** [comment]
Good, Merged!! ✨ @saurav2208

**Pull request merged**
