### PR TITLE
Added hover effect on inputs in Basic Calculator

### LINKED ISSUE #633: [Style] Add hover effect on inputs in Basic Calculator
### What's the style idea?

**Description**
On mouseover the border color of the inputs will be changed.
Please assign me this task under GSSoC'24 Contributor.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivangi-singhjha**
# Fixes Issue🛠️

Closes #633

# Description👨‍💻 

Add border effect on inputs in Basic Calculator

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

### CODE REVIEW

**Comment by shivangi-singhjha** [comment]
Sir On clicking using keyboard or UI the border is added  and on hovering also the border is added.

**Comment by Rakesh9100** [comment]
Looks good, Merged 🎉🥳 @shivangi-singhjha

**Comment by Rakesh9100** [comment]
Looks good, Merged 🎉🥳 @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
> Looks good, Merged 🎉🥳 @shivangi-singhjha

Thank You, so much Sir.

**Pull request merged**
