### PR TITLE
Added Armstrong Number Calculator

### LINKED ISSUE #268: [Feature] Add an Armstrong Number Calcultor for n-digit numbers
### Description

I would like to add a Armstrong Number Calculator which would input the number of digits 'n' from the user and calculates the Armstrong Number(s) for n-digit numbers. The proposed calculator would be created using HTML, CSS, and Javascript and will be added to the website as per the given guidelines.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by zul132**
# Fixes Issue🛠️

Closes #268 

# Description👨‍💻 
I've added a new Armstrong Number Calulcator which computes all the Armstrong numbers within a range specified by the Number of digits n. The tech stack used for building the calculator is HTML, CSS and Javascript. The program uses an Iterative approach for checking whether a given number in the range is an Armstrong number or not and displays the number if True. Also, in order to improve the calculator performance, an optimization has been implemented which reduces the search space by considering the maximum possible sum of powers for each number. 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested the calculator by giving various values of n and successfully generated the Armstrong numbers in each case. But I noticed that for larger digits (>8), the time complexity for computing the Armstrong numbers becomes very huge. To improve this, I included an optimization in my iterative program to reduce the search space based on the number of digits. However, keep in mind that finding Armstrong numbers for very large values of n can still be computationally expensive, leading to a delay for larger inputs.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
screenshot1

screenshot2

### CODE REVIEW

**Comment by zul132** [comment]
@Rakesh9100 Kindly merge my PR under JWOC.

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @zul132

**Comment by Rakesh9100** [comment]
Resolve the conflicts again pls as some more PRs are merged @zul132

**Comment by zul132** [comment]
@Rakesh9100 I have resolved the issues just now. Please merge my PR now

**Comment by Rakesh9100** [comment]
Work on these:

image

1. When no number is entered, it should give alert to Enter a valid number.

2. When I am entering 8, 9, 10 or higher number, the page is becoming unresponsive @zul132

**Comment by zul132** [comment]
@Rakesh9100 
PR_cacl2

PR_cacl1

1. I have implemented form validation to check whether a Valid number is being entered and to alert the user in case no number is given.
2. The page is becoming unresponsive due to the huge overhead of computing Armnstrong number for larger digits...I've tried to resolve it using many optimization techniques(memoization,pagination/chunking) but I am unable find a suitable algorithm which works for higher values of n. 
Therefore, I have modified the form validation to only allow the user to enter numbers between 1 and 7. This way the page won't become unresponsive when the users enters 8, 9, 10 or higher number

**Comment by Rakesh9100** [comment]
Okay, no issues. I will see it!!

Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @zul132

**Comment by zul132** [comment]
Thank you for your feedback and guidance 🙏🎉

**Pull request merged**
