### PR TITLE
Added Savings Goal Calculator

### LINKED ISSUE #677: [Feature] Add Savings Goal Calculator
### Description

This calculator assists users in determining how much they need to save regularly to reach a specific financial goal within a desired timeframe.

### Features:

- Goal setting
- Saving frequency, etc

@Rakesh9100 Can I please work on this addition under GSSoC'24. It would be great for me to work on this.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by diyaaa19**
# Fixes Issue🛠️

Closes #677

# Description👨‍💻 

Savings Goal calculator made successfully.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Is your calculator different from the one that we have [Savings Calculator](https://calcdiverse.netlify.app/calculators/savings-calculator/), I don't think so @diyaaa19

**Comment by diyaaa19** [comment]
My calculator would tell how much savings we can make for specific number
of years. Specifically tells about savings in particular no. of years, the
existing calculator calculates interest, investment as well accumulated
over time. so they are slightly  different but work on the same principle.

**Comment by diyaaa19** [comment]
I'd be happy to make another calculator for something else, if this doesn't
work out.

**Comment by Rakesh9100** [comment]
Pls work on new issues or you can take another up-for-grab issues if this also works on same principle, closing this PR @diyaaa19

**Pull request closed without merging**
