### PR TITLE
Added Heat Transfer Calculator

### LINKED ISSUE #1657: [Feature] Add Heat Transfer Calculator
### Description

The Heat Transfer Calculator estimates the rate of heat transfer through various materials based on input parameters such as material type, thickness, temperature difference, and surface area. This tool is essential for engineers, architects, and students to design efficient thermal systems and understand heat transfer phenomena in different applications.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Shuvra-Da-CodER**
# Fixes Issue🛠️

Closes #1657 

# Description👨‍💻

I have added a heat transfer calculator, which estimates the rate of heat transfer through various materials based on input parameters such as thermal conductivity, thickness, temperature difference, and surface area. This tool is essential for engineers, architects, and students to design efficient thermal systems and understand heat transfer phenomena in different applications.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-12-08 231656

### CODE REVIEW

**Comment by Shuvra-Da-CodER** [comment]
@Rakesh9100 Please check I've raised a PR

**Comment by Rakesh9100** [comment]
Please mention the issue number this PR closes @Shuvra-Da-CodER

**Comment by Shuvra-Da-CodER** [comment]
@Rakesh9100 Check I've updated....

**Comment by Rakesh9100** [comment]
Add your calculator in the main `index.html` file to display on the website, make the new commit in this same PR @Shuvra-Da-CodER

**Comment by Shuvra-Da-CodER** [comment]
@Rakesh9100 Check I've updated

**Pull request merged**
