### PR TITLE
Added Freelance Rate Calculator

### LINKED ISSUE #1158: [Feature] Add Freelance Rate Calculator
### Description

Freelance Rate Calculator: To calculate hourly or project rates for freelancers.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by mahek0620**
# Fixes Issue🛠️

Closes #1158 

# Description👨‍💻

The Freelance Rate Calculator is a tool that helps freelancers determine their optimal hourly or project-based rates based on various factors like desired annual income, billable hours per week, and vacation weeks per year.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Attach the screenshots of your work @mahek0620

**Comment by mahek0620** [comment]
@Rakesh9100 here's the screenshot 
image

**Comment by Rakesh9100** [comment]
Work on these @mahek0620 

1. Enhance the box UI.
2. Handle the NaN value that is showing 0 or NaN when not filled in any inputs.
3. Add your calculator part in the main `index.html` to display it on the website!!

**Comment by mahek0620** [comment]
Screenshot 2024-06-17 180054

The code has been modified

**Comment by mahek0620** [comment]
@Rakesh9100 kindly review the updated files

**Pull request merged**
