### PR TITLE
Added Critical Point Calculator

### LINKED ISSUE #1610: [Feature] Add Critical Point Calculator
### Description

Creating a critical point calculator for ideal gases involves calculating the critical temperature, critical pressure, and critical volume based on the Van der Waals equation of state.

The critical point of an ideal gas is a set of specific thermodynamic conditions where the distinction between the gas and liquid phases disappears. At this point:

- Critical Temperature (Tc): This is the highest temperature at which the gas can be liquefied by applying pressure. Above this temperature, no amount of pressure can cause condensation into a liquid phase.

- Critical Pressure (Pc): The critical pressure is the pressure required to liquefy the gas at its critical temperature. Below this pressure, the gas cannot be liquefied by any means.

- Critical Volume (Vc): This is the molar volume of the gas at the critical point, where the densities of the gas and liquid phases become equal.

### Screenshots

https://github.com/user-attachments/assets/c5993674-6b8e-4f29-8cda-4cbe5f6971fa

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
# Fixes Issue🛠️

Closes #1610 

# Description👨‍💻

Added the critical point calculator with following features , 
Creating a critical point calculator for ideal gases involves calculating the critical temperature, critical pressure, and critical volume based on the Van der Waals equation of state.

The critical point of an ideal gas is a set of specific thermodynamic conditions where the distinction between the gas and liquid phases disappears. At this point:

Critical Temperature (Tc): This is the highest temperature at which the gas can be liquefied by applying pressure. Above this temperature, no amount of pressure can cause condensation into a liquid phase.

Critical Pressure (Pc): The critical pressure is the pressure required to liquefy the gas at its critical temperature. Below this pressure, the gas cannot be liquefied by any means.

Critical Volume (Vc): This is the molar volume of the gas at the critical point, where the densities of the gas and liquid phases become equal.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

https://github.com/user-attachments/assets/fe0c018d-285b-4c9a-b65f-e1ad18dcec43

### CODE REVIEW

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 Please review my PR and merge it

**Comment by Nihal4777** [comment]
@Maana-Ajmera  Add your calc in main index.html file of the project in alphabetical order.

**Comment by Nihal4777** [comment]
Also please add appropriate conditions for 0 values.
image

**Comment by Maana-Ajmera** [comment]
@Nihal4777 and @Rakesh9100 done the required things

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed  & can be merged.

**Pull request merged**
