### PR TITLE
Added cross product functionality in Vector Calculator

### LINKED ISSUE #1255: [Feature] Add cross product functionality in Vector Calculator
### Description

Will add cross product functionality to your existing Calculator. Add will need to add three-dimensional vectors input.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by divyansh-2005**
# Fixes Issue🛠️

Closes #1255 

# Description👨‍💻

Added cross product functionality in Vector Calculator.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@divyansh-2005 Make the page responsive too.
image

**Comment by divyansh-2005** [comment]
Done

**Comment by Nihal4777** [comment]
@divyansh-2005  Still, alignment is not proper. Also add your calculator in main index.html file.
image

**Comment by divyansh-2005** [comment]
@Nihal4777, I think you are viewing old commit please view new commit.

**Pull request merged**
