### PR TITLE
Enhanced the UI of Temperature Calculator

### LINKED ISSUE #1550: [Style] Enhance the UI of Temperature Calculator
### What's the style idea?

We need to improve the UI ⏬ 

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vansh-codes**
# Fixes Issue🛠️

Closes #1550 

# Description👨‍💻

- Enhanced the UI in terms of both UI and UX
- Changed logic:
     - when selected `celsius`, disabled the `celsius` in the convert from menu and this applies to all menus
     - when submitted once, is user selects any other radio option, the result is dynamically updated, user doesnt need to press submit again
     - added debouncing to minimize the function call for dynamic updates of selection

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### BEFORE
image

### AFTER
image

https://github.com/user-attachments/assets/c2122b36-5bd8-4197-9aa7-b6cd4841cd59

### CODE REVIEW

**Comment by Rakesh9100** [comment]
`The result should be displayed above the submit button with a message like '100 degree celcius is 212 Fahreneits'`

You have mentioned this change to be done in the issue, but it is not done @vansh-codes

**Comment by vansh-codes** [comment]
@Rakesh9100 Did the required changes. Please review. Heres a screenshot for reference: 
image

**Comment by vansh-codes** [comment]
@Rakesh9100 Please review, I have made the mentioned changes

**Comment by vansh-codes** [comment]
@Rakesh9100 Please merge this PR so that I can create PR's for other issues assigned to me

**Pull request merged**
