### PR TITLE
[Feature] Adding QR Code Calculator #457

### LINKED ISSUE #457: [Feature] Adding QR Code Calculator
### Description

i want to add a calculator that calculates the qr code for any text

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️

Closes #457 

# Description👨‍💻 

Added new feature QR code 
# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
QR-CD

### CODE REVIEW

**Comment by AftabMankapure** [comment]
PL check this

**Comment by Rakesh9100** [comment]
Update the screenshot entering the correct name of CalcDiverse @AftabMankapure

**Comment by Rakesh9100** [comment]
Update the screenshot in Readme as well as PR description entering the correct spelling of CalcDiverse @AftabMankapure

**Comment by AftabMankapure** [comment]
QR-CD

**Comment by SohanRC** [comment]
@AftabMankapure Heyyy !! This is my exact project in which I have already submitted a PR in FunFusion !! Why are copying others project in submitting a PR for yourself ??

@Rakesh9100 Please look into this matter !!

**Comment by Rakesh9100** [comment]
Why are you copying the code from one repository and pasting in another repo just for the points. If you are unable to solve issue by your own approach, then just don't ask for assigning an issue to you. Open Source is for learning and contributing rather than engaging in practices resembling plagiarism.

If found indulging in such activity again, you will be terminated from the open source program and will not be allowed to participate further!! @AftabMankapure

**Comment by Rakesh9100** [comment]
Why are you copying the code from one repository and pasting in another repo just for the points. If you are unable to solve issue by your own approach, then just don't ask for assigning an issue to you. Open Source is for learning and contributing rather than engaging in practices resembling plagiarism.

If found indulging in such activity again, you will be terminated from the open source program and will not be allowed to participate further!! @AftabMankapure

**Pull request closed without merging**
