### PR TITLE
Added pagination to the website

### PR DESCRIPTION
**Pull request by Varsani2520**
# Fixes Issue🛠️

Closes #
#1127 
# Description👨‍💻

i added pagination in home screen ,per page 10 project card display 

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [x] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [x] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Rakesh9100 ,now please merged it

**Comment by Varsani2520** [comment]
@Rakesh9100 ,give the response and also merged it with level label

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it with level label

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it with level label 

alos give the response

**Comment by Varsani2520** [comment]
@Rakesh9100 please merged it

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it

**Comment by Varsani2520** [comment]
i Kindly requested you

**Comment by Rakesh9100** [comment]
Can I know why have you closed your previous PR, and why the logic part is written in HTML file and not in JS file @Varsani2520

**Comment by Varsani2520** [comment]
@Rakesh9100 ,i re clone the Repo so previous Pr are closed

**Comment by Rakesh9100** [comment]
Seperate your logic from index.html file and keep in script.js file and then make the new commits in this same PR, don't close this @Varsani2520

**Comment by Varsani2520** [comment]
ok @Rakesh9100

**Comment by Varsani2520** [comment]
@Rakesh9100 now check it

**Comment by Varsani2520** [comment]
@Rakesh9100 pleased merged it

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it

**Comment by Rakesh9100** [comment]
When we search something, it shows the calculator which has that search word either in title of the calculator or the description, but it is removed after your changes, and now it fetches that search only from the titles. Pls fix @Varsani2520

**Pull request merged**
