### PR TITLE
Fixed currency converter issue (solves #31)

### PR DESCRIPTION
**Pull request by SaranshBangar**
# Fixes Issue🛠️

Closes #31 

# Description👨‍💻 

I have added a small "if" statement that checks if the user input is valid or not, if it is not valid, the code shows an error to the user

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have ran multiple tests including alphabets, decimals, symbols and the code passes every test case

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Have you created this PR and respective issue under SWOC? @SaranshBangar

**Comment by SaranshBangar** [comment]
Yes sir @Rakesh9100

**Comment by Rakesh9100** [comment]
SWOC starts from 1st Jan, 2024! So pls do wait!!
And yes, create your PR only after you are assigned the issue @SaranshBangar

**Comment by SaranshBangar** [comment]
The above issue is solved in PR #43

**Pull request closed without merging**
