### PR TITLE
Fixed the API request on fetching contributors

### LINKED ISSUE #996: [Bug] Fix the API request on fetching contributors
### Description

@Rakesh9100 While fetching contributor api is not working , it rate limit is exceeded, 
**I can fix it , please assign this to me** Mark gssoc24

### Screenshots

Screenshot 2024-05-31 100113

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pandeyji711**
# Fixes Issue🛠️

Closes #996 

# Description👨‍💻 

Now API limited increased to 5000 pr hr.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Tested on my local machine.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-06-02 110439

### CODE REVIEW

**Comment by pandeyji711** [comment]
> https://deploy-preview-1179--calcdiverse.netlify.app/assets/contributors/contributor
> 
> Pls check the deploy preview, why all the contributors are taking time to load @pandeyji711

@Rakesh9100 becouse api token is fetch from google app scrip 
i added one loading animation after that

**Comment by Rakesh9100** [comment]
Have you added the loading animation or will add @pandeyji711

**Comment by pandeyji711** [comment]
> Have you added the loading animation or will add @pandeyji711

after merge i will add

**Comment by pandeyji711** [comment]
> Have you added the loading animation or will add @pandeyji711

becouse i have to cheak for it working on production or not

**Comment by Rakesh9100** [comment]
I can't merge as it is taking too much time to load, the previous one is only fine which loads all the contributors immediately @pandeyji711

**Comment by pandeyji711** [comment]
> I can't merge as it is taking too much time to load, the previous one is only fine which loads all the contributors immediately @pandeyji711

i will add loading animation it works fine then

**Pull request merged**
