### PR TITLE
GST Calculator

### PR DESCRIPTION
**Pull request by Harshil-Gupta21**
# Fixes Issue🛠️

#324 

Closes #

# Description👨‍💻 

Successfully added GST calculator

# Type of change📄

- [] New feature (non-breaking change which adds functionality)
- GST Calculator

# How this has been tested✅

Checked by putting different values.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Don't do any changes in main `index.html` file except just adding your calculator section at the end of the file @Harshil-Gupta21

**Comment by Harshil-Gupta21** [comment]
I have done that only and nothing else

**Comment by Rakesh9100** [comment]
image

Why these many changes are showing @Harshil-Gupta21

**Comment by Harshil-Gupta21** [comment]
Oh I guess prettier did this. I'll do the changes and update it soon.

**Pull request closed without merging**
