### PR TITLE
Added Vector Calculator

### LINKED ISSUE #362: [Feature] Addition of vector calculator
### Description

@Rakesh9100 I would like to add a vector calculator . plz assign it to me under swoc'24.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #362 

# Description👨‍💻 
Added Vector Calculator

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
Untitle123d

Untitled123

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100 plz check

**Comment by Rakesh9100** [comment]
1. Handle NaN values.
2. Remove the hover effect from the Result.
3. Resolve the conflicts pls @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 can u tell me the calculation for NaN values?
Is it like NaN vector added to another NaN vector would give NaN as resultant? And their dot product would be NaN too? And what about the angle would it be NaN as well?

**Comment by Rakesh9100** [comment]
No, Handle NaN means provide an alert to enter the valid angle or values when clicked on Calculate without entering any value @GhoshAditi 

image

**Comment by GhoshAditi** [comment]
@Rakesh9100 may i create another pr and close this? i see that u have merged some of the pr's some hours before and my code was written before that. so the codes are overlapping because they are in the same line. so shall i delete this one and give a ner pr based on the latest code of CalcDiverse?

**Comment by Rakesh9100** [comment]
You can resolve the merge conflicts without closing this PR by just pulling the latest changes from the main repository to your forked repo or to your local @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 i cannot do as i asked. i am sorry . so i am closing it and giving a new pr. sorry:(

**Pull request closed without merging**
