### PR TITLE
Added Nutritional Needs Calculator

### LINKED ISSUE #1351: [Feature] Add Nutritional Needs Calculator
### Description

**Purpose**: Determines the daily caloric and macronutrient needs based on an individual's age, sex, weight, height, activity level, and fitness goals.

**Input**:

- Age
- Sex
- Weight
- Height
- Activity level (sedentary, lightly active, moderately active, very active)
- Fitness goals (lose weight, maintain weight, gain weight)

**Output**:

- Daily caloric needs
- Recommended intake of carbohydrates, proteins, and fats

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by kosuri-indu**
# Fixes Issue🛠️

Closes #1351 

# Description👨‍💻

Determines the daily caloric and macronutrient needs based on an individual's age, sex, weight, height, activity level, and fitness goals.

- Enter your age.
- Select your sex (Male, Female).
- Enter your weight in kilograms.
- Enter your height in centimeters.
- Select your activity level (Sedentary, Lightly Active, Moderately Active, Very Active).
- Select your fitness goals (Lose Weight, Maintain Weight, Gain Weight).
- Perform the calculation and display the daily caloric needs and recommended intake of carbohydrates, proteins, and fats.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

image

### CODE REVIEW

**Comment by kosuri-indu** [comment]
@Rakesh9100 
Please review this PR :)
Thank you

**Comment by Nihal4777** [comment]
@kosuri-indu Please add empty field validations.

**Comment by kosuri-indu** [comment]
@Rakesh9100 @Nihal4777 
Made respective changes sir

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed and can be merged.

**Pull request merged**
