### PR TITLE
Scientific calc added 

### PR DESCRIPTION
**Pull request by DeepakGulati31**
# Description👨‍💻 

It helps us find the trigonometric and inverse trigonometric function, log values, sq root, cube root and many more.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Image 12-05-24 at 7 11 PM

### CODE REVIEW

**Comment by SakshiLingwal** [comment]
“Hey Deepak, I noticed you shared your code even though you weren’t assigned a specific task. Being an open source contributor could you please tell me like how can one's raised request got acknowledged ?”

**Comment by Rakesh9100** [comment]
Please do not create a PR until you have been assigned to an issue @DeepakGulati31

**Comment by Yuvraj960** [comment]
@Rakesh9100 Would you allow me to create a similar issue like this and add a scientific calculator. I would love working on this issue.

**Comment by Rakesh9100** [comment]
Okay, you can go and add @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 Thanks for assigning me the issue.
Rakesh, Actually I am ill so I will be developing the calculator for a slow pace for some time. I hope that you understand.

**Comment by Yuvraj960** [comment]
Should I create some issue first or directly a PR now?

**Pull request closed without merging**
