### PR TITLE
Added Thala for a Reason Calculator

### LINKED ISSUE #420: [Feature] Thala For a Reason Calculator
### Description

Hi, I'd like to create a calculator where the user will enter a 6 digit number, and after performing some calculations they will get the answer "7", please assign it to me under JWOC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by rishicds**
# Fixes Issue🛠️

Closes #420 

# Description👨‍💻 
Added Thala for a reason Calculator, regardless of what 6 digit number you give the result will always be 7

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Include Readme.md for your calculator in your folder @rishicds

**Comment by Rakesh9100** [comment]
Rename your folder to `Thala-For-A-Reason-Calculator` and make the necessary changes.

Include Readme.md for your calculator in your folder @rishicds

**Comment by rishicds** [comment]
I have made the necessary changes, please take a look @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged 🎉 @rishicds

**Pull request merged**
