### PR TITLE
Enhanced Navbar

### LINKED ISSUE #87: Enhance Navbar
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This issue is to enhance the nav bar and make it more responsive for the user.
- Good styling.
- Effective hover effects.
- Interactive color balance.

The changes can be seen in the below attached screenshots.

### Screenshots

**Present Navbar :**

Navbar 1 before

Nav before 1

Nav logo before 1

**Navbar after making improvements :**

Navbar 1

Nav after 1

Nav logo after 1

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by CodeByRajeev**
**Closes #87** 

**Enhancement of  Navbar**

**# Description👨‍💻** 

This issue is to enhances the navbar and make it more responsive for the user.
-Good styling.
-Effective hover effects.
-Interactive color balance.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

**The changes before and after can be seen below :** 

**The whole logo before :** 

Navbar 1 before

**The whole logo after :** 

Navbar 1

**The logo before :** 

Nav logo before 1

**The logo after :** 

Nav logo after 1

**The logo after on hovering :** 

Nav logo after hover 1

**Nav Items before :** 
Nav items before 1

**Nav Items after :** 

Nav items after 2

**Nav Items after on hovering  :** 

Nav items after after 2

**In detail, Navbar before :** 
Nav before 1

**In detail, Navbar after improving :** 
Nav after 1

### CODE REVIEW

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir, please look at this and let me know if any other improvements can be done. Hope this PR gets merged.

**Comment by Rakesh9100** [comment]
Good, Merged!! 🎉 @CodeByRajeev

**Comment by CodeByRajeev** [comment]
@Rakesh9100   Thank you sir. Sir in addition to this can I change the whole body color and the calculators colors with decent palette of colors in the following way as a **new issue** ( as I already raised but it was closed. Just have a look ) : 

ui home after 1

**Comment by CodeByRajeev** [comment]
Please give me some advice sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Issue is already open, I told you earlier as well.

If it's not done, then will assign you @CodeByRajeev

**Comment by CodeByRajeev** [comment]
Ok sir, got it . Thank you.

**Pull request merged**
