### PR TITLE
Added Atomic Composition Calculator

### LINKED ISSUE #712: [Feature] Number of moles of substance & number of electron , proton and neutron calculator.
### Description

1. Input: The user inputs the mass of the substance and its molar mass (in grams per mole).

2. Calculate Moles: The calculator calculates the number of moles of the substance.

3. Calculate Number of Electrons, Protons, and Neutrons: This part depends on the substance. If the substance is an atom (not an ion), you can determine the number of electrons, protons, and neutrons based on its atomic number (Z) and mass number (A).

   - Number of protons (Z) = atomic number (provided for each element)
   - Number of electrons (Z) = number of protons (for a neutral atom)
   - Number of neutrons (N) = mass number (A) - number of protons (Z)

4. Output : The calculator displays the number of moles of the substance, as well as the number of electrons, protons, and neutrons.

5. Optional Features:
   - Error Handling: Ensure the user inputs valid values and handle any potential errors gracefully.
   - Support for Ions: Extend the calculator to handle ions by allowing the user to input the charge, which would affect the number of electrons.
   - Interactive Interface: Develop a user-friendly interface that guides the user through the process step by step.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by bharat-c27**
# Fixes Issue🛠️

Closes #712 

# Description👨‍💻

The calculator determines the number of protons, neutrons, and electrons in an atom based on its atomic number, atomic mass, and charge. It supports both neutral atoms and ions.

I have also handled the error validation.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-07-18 002317

### CODE REVIEW

**Comment by bharat-c27** [comment]
Hello @Rakesh9100 can you please assign to me and add the necessary labels.

Thank you!!

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by bharat-c27** [comment]
Hello @Rakesh9100 , I have completed the issue can you please assign this PR to me.
There are only 5 days left for GSSOC to get over.

Thank you!!

**Comment by Nihal4777** [comment]
@bharat-c27 Thank you for your contribution. Don't worry your PR will be merged within deadline.

**Comment by bharat-c27** [comment]
> @bharat-c27 Thank you for your contribution. Don't worry your PR will be merged within deadline.

Okay, Thank you @Nihal4777.

I was having a doubt. I have opened an issue on 12 Jun. I have referenced it 2-3 times, but I think @Rakesh9100 is busy so he did not assigned me the issue. I have completed my implementation work. I worked on it and hope to get merged before the deadline.

So can I raise a PR ?

**Issue Link** : https://github.com/Rakesh9100/CalcDiverse/issues/1317

**Comment by bharat-c27** [comment]
Hello @Rakesh9100 please merge the PR as the deadline is tomorrow only.
And what should I do with the my issue #1317  which is been completed ?

**Pull request merged**
