### PR TITLE
Weight Converter Calculator

### LINKED ISSUE #17: Unit converion from kg to punds and vice versa.
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will implement an unit convertor of pound to weight and vice versa.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by maadi7**
# Fixes Issue🛠️

Closes #17

# Description👨‍💻 
Swiftly convert weight from kgs to pounds and vice-versa.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
jj

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @maadi7

**Comment by maadi7** [comment]
hii @Rakesh9100, its resloved now. Please check.

**Review by PARKER-X — APPROVED** [review]
Great Work Bro!

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉 @maadi7

**Pull request merged**
