### PR TITLE
Carbon footprint calculator

### LINKED ISSUE #297: [Feature] Carbon Footprint Calculator
### Description

I wish to add a Carbon Footprint Calculator that calculates an estimate of an individual's carbon footprint based on the miles driven per year. Kindly assign me the issue under SWOC @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by muskan42**
# Fixes Issue🛠️

Closes #297

# Description👨‍💻 

Calculates an estimate of an individual's carbon footprint based on the miles driven per year.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Locally

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-01-17 004344

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @muskan42

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls and don't make any changes to main `index.html` file except just adding your calculator at the end @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 I haven't made any changes to the main index.html except for adding my calculator

**Comment by muskan42** [comment]
@Rakesh9100 The PR was closed by mistake. I'm creating a new PR again.

**Pull request closed without merging**
