### PR TITLE
Added Marks Percentage Calculator

### LINKED ISSUE #967: [Feature] Add Marks Percentage Calculator
### Description

User Enter how many subject is there.
Then Enter marks of each 
In last click Submit and get Percentage of that marks.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by zalabhavy**
# Fixes Issue🛠️
Closes #967 

# Description👨‍💻 
A Marks to Percentage Calculator is a tool designed to convert the marks obtained in various subjects into a percentage. 
It allows users to input the number of subjects and the marks obtained in each subject. 
The calculator then sums up the total marks and computes the average percentage based on the number of subjects. 

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Self run after all changes in code.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@Rakesh9100 Please check it and merge !

**Comment by Rakesh9100** [comment]
Pls style and enhance the UI nicely and also remove the below header which is not needed, make the new commits in this same PR @zalabhavy 

image

**Comment by zalabhavy** [comment]
@Rakesh9100 Please check now and merge !

**Comment by Rakesh9100** [comment]
image

Will not merge if UI is this much dull and simple @zalabhavy

**Comment by zalabhavy** [comment]
@Rakesh9100 I try my best to add CSS and make it more attractive please check it now and please merge i give my lots of time to this.
image

**Comment by Rakesh9100** [comment]
I told you to remove this navbar, which is added unnecessarily @Rakesh9100 

image

**Comment by Rakesh9100** [comment]
I told you to remove this navbar, which is added unnecessarily @zalabhavy 

image

**Comment by zalabhavy** [comment]
@Rakesh9100 navbar removed please check it !

**Pull request merged**
