### PR TITLE
Added subject grade calculator

### LINKED ISSUE #33: Grade Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a grade calculator to the website. This is a basic one I have created for it. I will enhance it more.

Please assign me the issue.

### Screenshots

Screenshot 2023-12-30 191605
Screenshot 2023-12-30 192106

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by pankhuri92**
# Fixes Issue🛠️

Closes #33

# Description👨‍💻 
The user can enter as many subject marks as needed. The calculator will give the total points, points scored, percentage and grade.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-03 173344
Screenshot 2024-01-03 173408

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve  the conflict @pankhuri92

**Comment by Rakesh9100** [comment]
Pls resolve the conflict @pankhuri92

**Comment by pankhuri92** [comment]
@Rakesh9100 I have now resolved the conflicts.

**Comment by Rakesh9100** [comment]
@pankhuri92 The conflict is resolved but all the previous merged changes are getting deleted. Pls do fix it.

image

**Comment by pankhuri92** [comment]
@Rakesh9100, I am apologetic for all the inconvenience caused. Kindly check if there's still an issue. I've tried resolving it.

**Comment by Rakesh9100** [comment]
Good job, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @pankhuri92

**Comment by pankhuri92** [comment]
Thanks!

**Pull request merged**
