### PR TITLE
Enhanced 2D Shapes Calculator and Color Code Calculator

### LINKED ISSUE #458: [Style] Enhance 2D Shapes Calculator and Color Code Calculator
### What's the style idea?

All the pages of the calculators are very basic and are not at all visually appealing. So i suggest that i get assigned this issue and i will work on the styling of as many calculator pages as i can.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Hansawani**
# Fixes Issue🛠️

Closes #458

# Description👨‍💻 

The 2D Shapes and color code calculator have now got a new, improved and more visually attractive UI. The headings have animations, there are stylish buttons which have shadow effect on hovering and also have an outline border when they are in focus. The font family, font size, and font colors have also been changed accordingly.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/114403339/d358b330-ba42-4c82-9da9-6d96ae924b8b

https://github.com/Rakesh9100/CalcDiverse/assets/114403339/22cce3f5-aa88-486c-8adb-d883cdc2db97

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls delete your images from folder `assets/images` and keep those background images in the respective Calculator folder and then link and use it @Hansawani

**Comment by Hansawani** [comment]
Okay I will do the requested changes asap.

**Comment by Hansawani** [comment]
Please check now. I have done the changes that you requested.

**Comment by Rakesh9100** [comment]
Nice UI, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Hansawani

**Comment by Hansawani** [comment]
Please update the leaderboard🙏🏻😄
My name is Hansawani Saini.

**Pull request merged**
