### PR TITLE
Added Centripetal Force Calculator

### LINKED ISSUE #451: [Feature] Adding a centripetal force calculator
### Description

I want to add a centripetal force calculator.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by nirman2004**
# Fixes Issue🛠️

Closes #451

# Description👨‍💻 

I have added a new centripetal force calculating calculator.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (81)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Add a Readme of the calculator in your folder @nirman2004

**Comment by nirman2004** [comment]
Ok sir @Rakesh9100

**Comment by nirman2004** [comment]
I have added the readme file sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Centripetal-Force-Calculator` and make the necessary changes @nirman2004

**Comment by Rakesh9100** [comment]
Handle NaN values using an alert when clicking on Show Result without entering any value.

Show the units for force and acceleration both in the result!! @nirman2004

**Comment by nirman2004** [comment]
I have added an alert for NaN and added the units in result @Rakesh9100

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @nirman2004

**Pull request merged**
