### PR TITLE
Added Catalan Number Calculator

### LINKED ISSUE #1271: [Feature] Add Catalan Number Calculator
### Description

In combinatorial mathematics, the Catalan numbers are a sequence of natural numbers that occur in various counting problems, often involving recursively defined objects. They are named after the French-Belgian mathematician Eugène Charles Catalan.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Will2Jacks**
# Fixes Issue🛠️

Closes #1271 

# Description👨‍💻

Added the Catalan Calculator.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-23 203115

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Will2Jacks You should add calculator in main index.html file.

**Comment by Will2Jacks** [comment]
I have made the required changes in the main index.html file of my branch(Task)

**Comment by Rakesh9100** [comment]
Pls attach the screenshots of your work @Will2Jacks

**Comment by Will2Jacks** [comment]
@Rakesh9100 Added screenshot

**Pull request merged**
