### PR TITLE
Added Blood Sugar Calculator

### LINKED ISSUE #1583: [Feature] Add Blood Sugar Calculator
### Description

This will take the Random blood sugar test results and Fasting blood sugar rests and provide the user with the analysis whether it is normal, high or low and provide with useful links on how to control the range.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vidhiisaxena**
# Fixes Issue🛠️

Closes #1583 

# Description👨‍💻

I've added a new calculator, Blood Sugar Calculator, which inputs the age and medical test result. It then provides the range in which your test results lie. I've added 

- index.html
- style.css
- script.js
- README.md

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-07-16 223337

### CODE REVIEW

**Comment by Nihal4777** [comment]
@vidhiisaxena  You should add your calc in main index.html file of project in alphabetical order.

**Comment by vidhiisaxena** [comment]
@Nihal4777 Kindly review it once and if everything is fine, then please merge my PR.

**Comment by Nihal4777** [comment]
@vidhiisaxena Why background image is repeating on x axis; You can have `background-size: cover;` property added in body tag.
image

**Comment by vidhiisaxena** [comment]
I've already added the following tag.

**Comment by vidhiisaxena** [comment]
Removed the background as it was not responsive.

**Comment by vidhiisaxena** [comment]
@Nihal4777 @Rakesh9100 Kindly check and merge my PR.

**Comment by Nihal4777** [comment]
@vidhiisaxena Don't worry It will be reviewed & merged very soon.

**Comment by Nihal4777** [comment]
In the meantime if are facing difficulty in adjusting background then you can contact me on Discord @nihalrajpal

**Pull request merged**
