### PR TITLE
Added Debt-To-Income Ratio Calculator

### LINKED ISSUE #827: [Feature] Add Debt-To-Income Ratio Calculator
### Description

Debt-to-income ratio (DTI) is the ratio of total debt payments divided by gross income (before tax) expressed as a percentage, usually on either a monthly or annual basis.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #827 

# Description👨‍💻 

This calculator returns the ratio of debt taken by the user to its income. More the ratio more worse condition of the user is currently.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

- [x] Checked and cross verified all the results from an existing DTI Ratio Calculator. 
- [x] Done all the verifies on calculated results

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshot

image

### CODE REVIEW

**Comment by Yuvraj960** [comment]
@Rakesh9100 Kindly review this calculator pr, please mention if any mistakes done😊. Will submit another Calc PR tomorrow, with some more interesting issues opening up😉.

**Comment by Rakesh9100** [comment]
Pls attach the screenshot of your calculator in the PR template above @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 Done changing the UI and placing it in alphabetical order. Screenshot also updated😊

**Comment by Rakesh9100** [comment]
Merged 🎉 @Yuvraj960

**Pull request merged**
