### PR TITLE
Added Sum Of Digits Calculator

### LINKED ISSUE #1590: [Feature] Add Sum Of Digits Calculator
### Description

Sum of digits Calculator  is used to find sum of all digits in a given number

Input number: 1244

Output will be 1+2+4+4 = 11

Please assign me under GSSOC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sravyasaka**
# Fixes Issue🛠️

Closes #1590 

# Description👨‍💻

Added sum of digits calculator

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
For this also please add calc in main index file of project.

**Comment by Sravyasaka** [comment]
@Nihal4777 , done

> For this also please add calc in main index file of project.

**Comment by Rakesh9100** [comment]
Add a README.md file of your calculator and attach the screenshot of your work in the PR description @Sravyasaka

**Comment by Nihal4777** [comment]
> @Nihal4777 , done
> 
> > For this also please add calc in main index file of project.

There is no index.html file in your project directory instead there is sun.html please fix this.

**Comment by Sravyasaka** [comment]
@Nihal4777 , @Rakesh9100 done. Please verify

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Sravyasaka** [comment]
@Rakesh9100 , Please review my PR

**Pull request merged**
