### PR TITLE
Added Interplanetary Weight Calculator

### LINKED ISSUE #1186: [Feature] Add Interplanetary Weight Calculator
### Description

This feature helps user find their weights on different planets in our solar system. 
This issue can help users in multiple small scale project for knowing any object's weight on any other planet in our solar system.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by nandinipathak2005**
# Fixes Issue🛠️

Closes #1186 

# Description👨‍💻

Added Interplanetary Weight Calculator, an interactive web-based calculator that helps users determine their weight on different planets in our solar system. By entering their weight on Earth, users can instantly see their equivalent weight on other planets based on gravitational differences.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-07-14 222857
Screenshot 2024-07-14 222915

### CODE REVIEW

**Comment by Rakesh9100** [comment]
We already have [Astrological Age Calculator](https://calcdiverse.netlify.app/calculators/astrological-age-calculator/), is this calculator different @nandinipathak2005

**Comment by nandinipathak2005** [comment]
@Rakesh9100 yes ,this calculator can be used to find the weight of objects on different planets .It is different from Astrological Age Calculator.

**Comment by Rakesh9100** [comment]
Add your calculator part in the main `index.html` file to display it on the website @nandinipathak2005

**Comment by nandinipathak2005** [comment]
> Add your calculator part in the main `index.html` file to display it on the website @nandinipathak2005

@Rakesh9100 okay

**Comment by nandinipathak2005** [comment]
@Rakesh9100 I have updated the main index.html page

**Comment by nandinipathak2005** [comment]
@Rakesh9100 @Nihal4777 Pls review this PR

**Pull request merged**
