### PR TITLE
Added Random Word Generator Calculator

### LINKED ISSUE #832: [Feature] Add Random Word Generator Calculator
### Description

This feature involves adding a random word generator tool to GitHub issues, allowing users to generate unique and random words for use in issue titles or descriptions. The tool will help users who struggle with naming or describing issues by providing them with creative and diverse word choices, improving the clarity and specificity of issue communication.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Dhevamuthu**
# Fixes Issue🛠️

Closes #832 

# Description👨‍💻 

Implemented a feature to generate random words based on a specified starting letter and number of words. The feature uses the Random Word API to fetch words and displays them in a styled container. Additionally, input fields are cleared after each generation for improved user experience.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

1. **Manual Testing:**
   - Verified that the application correctly generates words starting with the specified letter.
   - Ensured that the number of words generated matches the user's input.
   - Checked that input fields are cleared after clicking the "Generate" button.
   - Confirmed that generated words are displayed in a styled container with 5 words per row.

2. **Functional Tests:**
   - Tested with different starting letters to ensure words generated start with the correct letter.
   - Tested with varying word counts (e.g., 5, 10, 15) to ensure the correct number of words are displayed.
   - Verified edge cases such as empty input fields and non-alphabetic characters.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

https://github.com/Rakesh9100/CalcDiverse/assets/123234572/0dca9368-1b07-4aeb-b61b-e91bbd4df08b

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Implement your website in normal HTML, CSS and JS, and not in React @Dhevamuthu

**Comment by Dhevamuthu** [comment]
I have used HTML and CSS only @Rakesh9100 

I have used api to fetch the words, other than that all are in html only. Here no need of javascript

**Comment by Rakesh9100** [comment]
image

Why these many files are present and package json files are also there, which we don't get with simple JS @Dhevamuthu

**Comment by Dhevamuthu** [comment]
image


please check through the code @Rakesh9100

**Comment by Rakesh9100** [comment]
image

Why Nutrition Calculator files are present, also separate your logic in `script.js` file and not in HTML file!

Also, do rename your folder to `Random-Word-Generator-Calculator` @Dhevamuthu

**Comment by Dhevamuthu** [comment]
done @Rakesh9100

**Pull request merged**
