### PR TITLE
Added Molality Calculator

### LINKED ISSUE #1786: [Feature] Add Molality Calculator
#### Description
A feature to calculate the molality of a solution would be beneficial for users who need to determine the concentration of solutes in their solutions. This calculator would take the mass of the solute (in grams) and the mass of the solvent (in kilograms) as input and return the molality of the solution.

#### Feature Details
- **Inputs**:
  - Mass of solute (g)
  - Mass of solvent (kg)
- **Output**:
  - Molality (moles of solute per kilogram of solvent)
- **Formula**:
  \[
  \text{Molality (m)} = \frac{\text{moles of solute}}{\text{mass of solvent in kg}}
  \]

#### Alternative Solutions
- Currently, users might need to use external tools or manual calculations to determine molality. Integrating this feature within our application would streamline their workflow.

#### Checklist
- [x] I have checked the existing issues to ensure this feature has not been requested before.

#### Additional Context
Adding this feature will enhance the application's functionality and provide more comprehensive tools for users working with solutions and concentrations.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Indrajeety993648**
# Fixes Issue🛠️

Closes #1786 

# Description📝

This pull request adds a feature to calculate the molality of a solution. The molality calculator takes the mass of the solute (in grams) and the mass of the solvent (in kilograms) as input and returns the molality of the solution.

### Feature Details
- **Inputs**:
  - Mass of solute (g)
  - Mass of solvent (kg)
- **Output**:
  - Molality (moles of solute per kilogram of solvent)
- **Formula**:
  \[\text{Molality (m)} = \frac{\text{moles of solute}}{\text{mass of solvent in kg}}\]

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Indrajeety993648** [comment]
@Rakesh9100  please review

**Comment by Indrajeety993648** [comment]
@Rakesh9100  Please review

**Comment by Indrajeety993648** [comment]
@Rakesh9100   please review

**Comment by Nihal4777** [comment]
@Indrajeety993648 Thank you for your contribution.

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Indrajeety993648** [comment]
@Rakesh9100    I think this is hard PR that i raised  Can u  add level 3 instead of level 2  , As in my College  marks only given for level 3 merged PR .

**Pull request merged**
