### PR TITLE
Linear equation Calculator

### LINKED ISSUE #124: Linear Equation in 2 Variables calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add a calculator that calculates the values of 2 variables from given linear equations in two variables.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by bhavya-anand19**
# Fixes Issue🛠️

Closes #124 

# Description👨‍💻 

Added a linear equation in two variables calculator.
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# This has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/133582773/2f5ebb0e-6c05-4064-97de-1bb2323acc3e

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls don't do any changes in main `index.html` file except just adding your calculator at the end @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Pls don't do any changes in main `index.html` file except just adding your calculator at the end @bhavya-anand19

ok

**Comment by bhavya-anand19** [comment]
Please have a look now. @Rakesh9100

**Comment by Rakesh9100** [comment]
No, its not fixed. Still too many changes are visible. [Check this](https://github.com/Rakesh9100/CalcDiverse/pull/218/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) @bhavya-anand19

**Comment by bhavya-anand19** [comment]
I have removed all the extra changes. @Rakesh9100

**Comment by Rakesh9100** [comment]
Good job and UI is really nice ✨ @bhavya-anand19 

Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @

**Comment by Rakesh9100** [comment]
Good job and UI is really nice ✨ @bhavya-anand19 

Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Good job and UI is really nice ✨ @bhavya-anand19
> 
> Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @bhavya-anand19

Thank you

**Pull request merged**
