### PR TITLE
Added a FAQ Page for the website

### LINKED ISSUE #514: [Feature] Adding a FAQ Page for the website
### Description

I want to create a FAQ page that answers a variety of questions regarding the project.

### Screenshots

image
image

I'll be referencing the above template for the FAQs

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Fixes Issue🛠️

- Closes #514 

# Description👨‍💻 

Adding a comprehensive FAQ page to the project. I've ensured that the page is complete, responsive, and adheres to the project's theme.
- [x] Responsive Design
- [x] Relevant FAQ Question
- [x] Themed Integration
- [x] Routing of FAQ Page
- [x] Feature Request

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested the project locally by Unit, Alpha & Beta Testing.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image
image
image
image
image

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100 The Pull Request is ready for a review and merge. Kindly review the Pull Request and provide your feedback.

**Comment by Rakesh9100** [comment]
Seems good, Pls work on these:

1. Keep the background, navbar and footer exactly same as home page.
2. The contributors and FAQ button link is broken of the footer of FAQ page.
3. Align the heading `Frequently Asked Questions` in center. @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Noted, I'll fix the above listed changes by today...

**Comment by antilneeraj** [comment]
@Rakesh9100, I kindly request that you review the PR again, as I have addressed the listed changes. If there are any remaining items or if you require additional modifications, Just let me know.

**Comment by Rakesh9100** [comment]
Check your [Page](https://deploy-preview-543--calcdiverse.netlify.app/assets/faq/faq) and the contact [Page](https://deploy-preview-543--calcdiverse.netlify.app/assets/faq/faq) navbar and footer, make it exactly same on hovering or without hovering @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Fixed the Difference kindly review it and provide your feedback.

**Comment by Rakesh9100** [comment]
Nice one, Merged 🎉✨ @antilneeraj

**Pull request merged**
