### PR TITLE
Added Electric Vehicle Savings Calculator

### LINKED ISSUE #1723: [Feature] Add Electric Vehicle Savings Calculator
### Description

Estimates savings from using an electric vehicle versus a gasoline vehicle.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sweta-singh28**
# Fixes Issue🛠️

Closes #1723 

# Description👨‍💻

Added a new calculator that calculates the cost of a gasoline vehicle per/km and a electric vehicle calculator.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)
 
# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

WhatsApp Image 2024-08-09 at 00 04 40_bbf832b6

### CODE REVIEW

**Comment by sweta-singh28** [comment]
@Rakesh9100 sir, done.

**Comment by sweta-singh28** [comment]
@Rakesh9100 sir,  Could you please merge this PR or provide any update on this? Today is the last day for GSSoC contributions.

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Nihal4777** [comment]
@sweta-singh28 Just change PR name to Electric Vehicle Savings Calculator added

**Comment by sweta-singh28** [comment]
> @sweta-singh28 Just change PR name to Electric Vehicle Savings Calculator added

@Nihal4777 sir, done.

**Pull request merged**
