### PR TITLE
Added Young's Double Slit Experiment Calculator

### LINKED ISSUE #1690: [Feature] Add Young's Double Slit Experiment Calculator
### Description

**Feature Description:**
Implement a web-based calculator for Young's Double Slit Experiment to allow users to compute the positions of bright and dark fringes as well as the fringe spacing. The calculator will take inputs for the distance between slits, the wavelength of light, the distance to the screen, and the order of the fringe. It will then output the calculated results in a user-friendly format.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by siddharthbaleja7**
# Fixes Issue🛠️

Closes #1690 

# Description👨‍💻

Implemented a calculator for Young's modulus and fringe spacing formulas. This calculator allows users to compute:

- **Position of Bright Fringe (ym)**: Calculates the position of the bright fringe based on provided parameters.
- **Position of Dark Fringe (ym)**: Computes the position of the dark fringe in the experiment.
- **Fringe Spacing**: Determines the spacing between fringes using the relevant formula.

The tool provides a user-friendly interface for inputting values and displaying results..

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-07-23 at 02 54 40

### CODE REVIEW

**Comment by siddharthbaleja7** [comment]
@Rakesh9100  please check this pr

**Comment by siddharthbaleja7** [comment]
@Rakesh9100 please check this pr

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed and can be merged.

**Comment by siddharthbaleja7** [comment]
@Rakesh9100 please check this pr

**Pull request merged**
