### PR TITLE
Added Love Calculator

### LINKED ISSUE #303: [Feature] Love Calculator
### Description

Love Calculator: Calculates a percentage score of love compatibility based on names or birthdates 

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #303 

# Description👨‍💻 

Calculates a percentage score of love compatibility based on names or birthdates (mostly for fun).
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
After clicking on OK of alert box "You can't leave fields empty", the score is showing but it should not @AbhineshJha

**Comment by AbhineshJha** [comment]
yes @Rakesh9100 ! i can see its a minor mistakes , lemme fix it

**Comment by Rakesh9100** [comment]
Merged ✨ @AbhineshJha

**Comment by AbhineshJha** [comment]
Thank you @Rakesh9100

**Comment by AbhineshJha** [comment]
thankyou @Rakesh9100

**Pull request merged**
