### PR TITLE
Added matrix calculator

### LINKED ISSUE #37: Addition of a Matrix calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to propose the addition of a new feature. Addition of a matrix calculator which can perform the following calculations

# Basic Operations: 
Multiplication, addition, subtraction of matrices and determinant. 
# Inverse and Transpose: 
Calculating the inverse or transpose of a matrix.
# Error Handling: 
Ensuring the calculator handles invalid inputs gracefully.
# Optimization: 
Implementing efficient algorithms for large matrices like 4x4.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by pankhuri92**
# Fixes Issue🛠️

Closes #37

# Description👨‍💻 
A web-based matrix calculator supporting basic operations (addition, subtraction, multiplication), determinant calculation, matrix inversion, and transpose, designed for square matrices of sizes 2x2, 3x3, and 4x4.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# This has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-11 023839

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts and add screenshot in Readme.md file @pankhuri92

**Comment by Rakesh9100** [comment]
1. Pls resolve the conflicts.
2. Add screenshot in Readme.md file.
3. Handle NaN values in the calculator.

@pankhuri92

**Comment by pankhuri92** [comment]
The conflicts have been resolved. And other necessary changes are done.
Screenshot 2024-01-11 234132

**Comment by Rakesh9100** [comment]
Merged!! 🎉✨ @pankhuri92

**Pull request merged**
