### PR TITLE
Added QR Code Calculator

### LINKED ISSUE #457: [Feature] Adding QR Code Calculator
### Description

i want to add a calculator that calculates the qr code for any text

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SohanRC**
# Fixes Issue🛠️

Closes #457

# Description👨‍💻 

 Added QR Code Calculator which generates QR Code according to the input provided by the user.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested in local system and it worked fine !

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !!

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !!

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !!!!

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !!

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @SohanRC

**Pull request merged**
