### PR TITLE
Added pagination to the website

### PR DESCRIPTION
**Pull request by Varsani2520**
# Fixes Issue🛠️

Closes #
#1127 
# Description👨‍💻

i added pagination in home screen ,per page 10 project card display 

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [x] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [x] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Rakesh9100 , i solve the issue #1127 ,review it and also merged it 

as well as add the level label and assigned

**Comment by Varsani2520** [comment]
if you want to any changes then tell me i will do it

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it also add the labels

**Comment by Nihal4777** [comment]
@Rakesh9100 Looks issue is solved.

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it

**Comment by Rakesh9100** [comment]
Why the hover effect and animations are changed, check the present website and your deploy preview and pls fix it @Varsani2520

**Comment by Varsani2520** [comment]
@Rakesh9100 

now you can merge this

image

**Comment by Varsani2520** [comment]
@Rakesh9100 ,i solved the style issue 

Now you ready to merged my pr

**Comment by Varsani2520** [comment]
@Rakesh9100 ,please merged it

**Comment by Rakesh9100** [comment]
When a keyword is searched and then cleared from the search bar, all the calculators are displayed on a single page @Varsani2520

**Pull request closed without merging**
