### PR TITLE
Added Short URL Calculator

### LINKED ISSUE #330: Short URL Calculator
### Description

The project need a calculator that calculate the short url of any link 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sakshamjain98**
# Fixes Issue🛠️

Closes #330 

# Description👨‍💻 

 I have a Short URL Calculator using rapid api of url shortening ... It is fully functioning 

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Short-URL-Calculator` and add a Readme file as well @Sakshamjain98

**Comment by Sakshamjain98** [comment]
OK sir

**Comment by Sakshamjain98** [comment]
Sir , I have ADDED the readme file and change the name

**Comment by Rakesh9100** [comment]
Add a screenshot in the Readme @Sakshamjain98

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Tqsm sir

**Pull request merged**
