### PR TITLE
Added Force Calculator

### LINKED ISSUE #1197: [Feature] Add Force Calculator
### Description

A simple calculator that calculates force by taking user input

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by samarsajad**
# Fixes Issue🛠️

Closes  #1197 

# Description👨‍💻

Added a newton's force calculator that takes an input of mass and acceleration to calculate newton's force.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Rakesh9100

**Comment by samarsajad** [comment]
Please review my pull request @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls work on these by making the new commits in this same PR @samarsajad 

1. Rename your folder to `Force-Calculator` and make the necessary changes.
2. Rename bg.jpg to background.jpg and place it inside your calculator folder by making the assets folder.

**Comment by samarsajad** [comment]
I made the requested changes. Please take a look @Rakesh9100

**Pull request merged**
