### PR TITLE
Added Ohms Law Calculator

### LINKED ISSUE #871: [Feature] Add Ohms Law Calculator
### Description

1.The calculator dynamically computes the missing values when at least two input values are provided.
2.The result section updates to display the calculated values in a clear and formatted manner.
3.The page includes basic styling to make it visually appealing and user-friendly.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by snigudkar**
# Fixes Issue🛠️

Closes #871 

# Description👨‍💻

An interactive web-based calculator for Ohm's Law, built using HTML, JavaScript, and CSS. This calculator allows users to compute the relationship between voltage, current, and resistance in an electrical circuit. It also allows user to find the power in watts.

- Added ohms law calculator feature along with an image and a link for the user to first understand what is Ohm's Law if they don't have prior knowledge.
- User can input any two fields and the program will calculate the third field and power in watts automatically.
- Implemented JavaScript functionality to dynamically calculate and update missing values based on user inputs..
- Applied basic CSS styling to make the interface more visually appealing and user-friendly.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

calc1

https://github.com/Rakesh9100/CalcDiverse/assets/146969559/7f3c796a-aaea-4e07-8654-4881640827dc

### CODE REVIEW

**Comment by snigudkar** [comment]
@Rakesh9100 please review my PR and let me know if any changes are to be made.

**Comment by Rakesh9100** [comment]
Pls add your calculator in the main `index.html` file to display it on the website by making the commit in the same PR @snigudkar

**Comment by snigudkar** [comment]
@Rakesh9100 Sorry i don't understand what is to be done as i am a complete beginner. My calculator's main html code is in index.html itself. What else is to be done?

**Comment by Rakesh9100** [comment]
As you are beginner, so I am adding this time, but you have to add your calculator part in this file from the next time https://github.com/snigudkar/CalcDiverse/blob/Ohms-Law-Calculator/index.html
This is the file of your forked repository, but main file is in my repository @snigudkar

**Comment by Rakesh9100** [comment]
As you are beginner, so I am adding this time, but you have to add your calculator part in this file from the next time https://github.com/snigudkar/CalcDiverse/blob/Ohms-Law-Calculator/index.html

This is the file of your forked repository, but main file is in my repository @snigudkar

**Pull request merged**
