### PR TITLE
Added Annulus Calculator

### LINKED ISSUE #1576: [Feature] Add Annulus Calculator
### Description

The Annulus Calculator is a tool designed to calculate the area of an annulus, which is the region between two concentric circles. This feature will help users quickly and accurately determine the area of an annulus given the radii of the two circles.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Damini2004**
# Fixes Issue🛠️

Closes #1576 

# Description👨‍💻
Added Annulus Calculator 

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Damini2004, You should add your calculator in alphabetical order in main index.html file of the project.

**Comment by Nihal4777** [comment]
@Damini2004 UI needs to be improved little bit. Also, you have specified that you will provide diagram?
https://github.com/Rakesh9100/CalcDiverse/issues/1576#issuecomment-2227200662,
image

**Comment by Damini2004** [comment]
@Nihal4777  Changes done 
Ohh i thought she was asking to give diagram of that particular formula, for diagram implemetation i need some time
KInldy review and merge it.

**Comment by Damini2004** [comment]
@Nihal4777 Added.

**Comment by Nihal4777** [comment]
@Damini2004 On small screens, there is overflow.
image

**Comment by Damini2004** [comment]
Yes it will overflow because the radius is increased then it not possible to visible the bigger circle. so we can provide diagram of inner circle rather than outer circle. Are you ok with it.

**Comment by Rakesh9100** [comment]
image

Where is the proper diagram, just white circle is visible. Also, that is hiding the result, pls fix @Damini2004

**Comment by Rakesh9100** [comment]
Are you working @Damini2004

**Comment by Rakesh9100** [comment]
Will close the PR if changes are not made today @Damini2004

**Pull request merged**
