### PR TITLE
CTC-Calculator

### LINKED ISSUE #312: [Feature] Adding Net Salary Calculator
### Description

Users can input salary details, bonuses, benefits, and deductions, receiving real-time updates on their CTC and also their salary structure.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pranjal12-web**
# Fixes Issue🛠️

Closes #312 

# Description👨‍💻 
Added CTC Calculator.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Tested on my local machine.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand area
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-18 002417

### CODE REVIEW

**Comment by Rakesh9100** [comment]
1. Handle NaN value in your calculator
2. Add a Readme file inside your folder
3. Add your calculator in main `index.html` file @pranjal12-web

**Comment by pranjal12-web** [comment]
@Rakesh9100 I have made changes,kindly review

**Comment by Rakesh9100** [comment]
No other changes to be done in main `index.html` file except just adding your calculator section at the end @pranjal12-web

**Comment by pranjal12-web** [comment]
I have already added my calculator to index.html
Screenshot 2024-01-19 200217

**Comment by Rakesh9100** [comment]
[Check this](https://github.com/Rakesh9100/CalcDiverse/pull/359/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051), Click on Load diff and scroll down to see what extra changes has been done @pranjal12-web

**Pull request closed without merging**
