### PR TITLE
Added Cooking Measurement Calculator

### LINKED ISSUE #1463: [Feature] Add Cooking Measurement Calculator
### Description

A calculator that pretty much converts between different cooking measurements (e.g., cups to grams, tablespoons to milliliters).

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by codercake**
# Fixes Issue🛠️

Closes #1463 

# Description👨‍💻

This tool is particularly useful for recipes that require precise measurements and for those who need to convert between different units of weight commonly used in cooking.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### HOME PAGE:
Screenshot 2024-07-15 173205

### WORKING DEMONSTRATION: 
image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@codercake Add you calc in main index.html file in alphabetical order. Also add empty field validations.
image

**Comment by codercake** [comment]
could you review the PR? @Nihal4777 @Rakesh9100

**Comment by Rakesh9100** [comment]
Attach the HOME PAGE: and WORKING DEMONSTRATION: in the PR description nicely @codercake

**Comment by codercake** [comment]
> Attach the HOME PAGE: and WORKING DEMONSTRATION: in the PR description nicely @codercake

done! @Rakesh9100

**Comment by codercake** [comment]
can you check the updated changes made to pr? @Rakesh9100

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Nihal4777** [comment]
@codercake You shouldn't add images from other sources. Instead you can download it and save in assets folder.
image

**Comment by codercake** [comment]
done! @Nihal4777

**Comment by Rakesh9100** [comment]
Are you assigned to the issue, no right? The mentor asked you a question there but you have still not answered that @codercake 

Also, in issue you have mentioned these (e.g., cups to grams, tablespoons to milliliters) but only Ounces and Pounds are there!

**Pull request closed without merging**
