### PR TITLE
Added Gauss-Jordan Elimination Calculator

### LINKED ISSUE #1421: [Feature] Add Gauss-Jordan Elimination Calculator
### Description

user can solve systems of simultaneous linear equations using Gauss-Jordan Elimination Calculator

### Screenshots

Screenshot 2024-06-24 172131

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by PDBharadwaj**
# Fixes Issue🛠️

Closes #1421 

# Description👨‍💻

I have added Gauss-Jordan Elimination Calculator. It is useful for calculating the system of simultaneous linear equations using Gauss-Jordan Elimination method.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-08-06 191401

Screenshot 2024-08-06 191549

@Rakesh9100 Please review and merge my PR.

### CODE REVIEW

**Comment by PDBharadwaj** [comment]
@Rakesh9100 Kindly review and merge my PR.

**Comment by Nihal4777** [comment]
@PDBharadwaj Add your calc in main index.html file of the project in order.

**Comment by PDBharadwaj** [comment]
@Nihal4777 @Rakesh9100 Added calculator to the main index.html file. Please review and merge my PR.

**Comment by PDBharadwaj** [comment]
@Nihal4777 @Rakesh9100 Please review and merge my PR before deadline.

**Pull request merged**
