### PR TITLE
Added Determinant Calculator

### LINKED ISSUE #1167: [Feature] Add Determinant Calculator
### Description

I would like to add a Determinat Calculator 
Kindly assign it to me under GSSoC'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by aasthakourav20**
# Fixes Issue🛠️

Closes #1167 

# Description👨‍💻

Added Determinant Calculator.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by aasthakourav20** [comment]
> Hey @aasthakourav20, Welcome to the project CalcDiverse! 🎊 Thanks for your contribution! Your effort makes this project better. Keep it up! 🙌 Please wait for the PR to be reviewed. Happy Coding!! ✨

Hey @Rakesh9100 , its been 4 days my PR isn't accepted yet . Can you please review it &  if there is any issue please let me know

**Comment by Rakesh9100** [comment]
Pls work on these @aasthakourav20 

1. Add your calculator part in the main `index.html` to display on the website by making the new commits in this same PR.
2. Enhance the UI.
3. Handle the NaN values.
4. Use only html, css and js file to include your images and not manifest.json file.

**Comment by Rakesh9100** [comment]
Are you working or not @aasthakourav20

**Comment by aasthakourav20** [comment]
> Are you working or not @aasthakourav20

Yes yes I'm working on this ....while I'm facing some issues in merging changes in the same PR .
But I will do this very soon

**Comment by Rakesh9100** [comment]
Any update @aasthakourav20

**Comment by aasthakourav20** [comment]
Hii @Rakesh9100 , I have changed the UI  , Kindly review the changes 

Screenshot (329)

**Comment by aasthakourav20** [comment]
Hii @Rakesh9100 , I hope you will like the new changes & UI too . I request you to please merge my PR

**Comment by Rakesh9100** [comment]
> Pls work on these @aasthakourav20
> 
> 1. Add your calculator part in the main `index.html` to display on the website by making the new commits in this same PR.
> 2. Enhance the UI.
> 3. Handle the NaN values.
> 4. Use only html, css and js file to include your images and not manifest.json file.

Work on all these changes properly @aasthakourav20

**Comment by Rakesh9100** [comment]
@Nihal4777 Guide her in detail to perform the changes about the points that I have mentioned!!

**Comment by aasthakourav20** [comment]
> @Nihal4777 Guide her in detail to perform the changes about the points that I have mentioned!!

Hey @Rakesh9100  , Changes are done

**Pull request merged**
