### PR TITLE
Navbar made sticky

### LINKED ISSUE #227: [Feature] : Make the NavBar sticky
### Description

I will fix the Navbar position so that after scrolling the nevbar will still visible

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️

Closes #227 

# Description👨‍💻 

Changed nevbar position to sticky by changing some css.

# How this has been tested✅

I had Checked the changes by running website and found the issue is fixed 😊

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls make the navbar of contact page sticky as well and make this navbar also full opaque with no blur effect @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
ok i will update

**Comment by Prince-kushwaha-2004** [comment]
kindly check,
and suggest if any modification required.

**Comment by Rakesh9100** [comment]
image

It should not overlap when scrolled, keep the navbar full opaque on top @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Screenshot 2024-01-13 020548
sir, check it now.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
thankyou sir😊

**Pull request merged**
