### PR TITLE
Added Restaurant Planning Calculator

### LINKED ISSUE #1788: [Feature] Add Restaurant Planning Calculator
### Description

The Restaurant Planning Calculator is a comprehensive tool designed to estimate and manage the expenses involved in setting up and running a restaurant. The calculator provides:

    Initial Setup Costs:
        One-time Equipment Costs: The total cost for purchasing necessary kitchen and restaurant equipment.

    Monthly Operating Costs:
        Rent: The monthly cost for leasing the restaurant space.
        Utilities: The monthly cost for essential services such as electricity, water, and gas.
        Staff Salaries: The total monthly salary expenditure based on the number of staff and their average salary.

    User Inputs:
        Available Space: The square footage of the restaurant space.
        Number of Staff: The total number of employees required.
        Monthly Rent: The cost of renting the space per month.
        Monthly Utilities: The cost of utilities per month.
        Equipment Costs: The one-time cost for equipment.
        Average Salary per Staff: The average monthly salary for each staff member.

    Expense Calculation:
        Total Initial Cost: Calculates the total one-time setup cost based on equipment expenses.
        Total Monthly Cost: Calculates the recurring monthly expenses, including rent, utilities, and staff salaries.

    Insights for Managing Expenses:
        Provides actionable insights based on the input data to help manage and optimize expenses effectively. For example:
            Suggestions for managing high monthly costs.
            Recommendations for making efficient use of smaller spaces.
            Advice on handling a large number of staff.

The calculator is presented within a visually appealing interface, making it easy to input data and receive detailed financial insights quickly. This tool is ideal for aspiring restaurateurs and existing business owners looking to optimize their financial planning and management.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
# Fixes Issue🛠️

Closes #1788 

# Description👨‍💻

This Restaurant Planning Calculator helps users efficiently plan their restaurant by calculating the initial and monthly costs based on various inputs such as available space, number of staff, rent, utilities, equipment costs, and salaries. It provides detailed insights on cost management, space optimization, and budget planning. The intuitive interface ensures easy input and clear results, aiding in effective financial planning and resource management for restaurant owners.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 i have added the restaurant planning calculator and this time i made sure that i did not make the same mistakes as last time

Please review and merge this pull request

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please merge this pull request

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 tommorrow is last day of gssoc please review and merge this pull request

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please merge this pull request only 9 hours are left for gssoc to get over

**Pull request merged**
