### PR TITLE
Added Stress and Strain Calculator

### LINKED ISSUE #550: [Feature] Adding Stress and Strain Calculator
### Description

I found out , this repo didn't contain stress and strain calculator, I would like to work on that and add that feature.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Imbiber**
Closes #550 

# Description👨‍💻 

This Stress and Strain Calculator is intended for engineers, students, or anyone interested in quickly assessing stress and strain values for a given material and set of conditions.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Results were same when calculated from different available calculated. Personally checked all parameter.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these changes and make the commits in this PR only of your changes.

1. Redesign and enhance the UI.
2. Include your calculator section in main index.html file as well @Imbiber

**Comment by Rakesh9100** [comment]
Pls work on these changes and make the commits in this PR only of your changes.

1. Redesign and enhance the UI.

2. Include your calculator section in main index.html file as well.

3. Handle the NaN values.

image

@Imbiber

**Comment by Rakesh9100** [comment]
Are you working @Imbiber

**Comment by Imbiber** [comment]
> Are you working @Imbiber
Yes  @Rakesh9100  I will work on this issue, I was having my GATE exam due to  which I couldn't give time to this , it got over today I will be working on it now.

**Comment by Imbiber** [comment]
Hey, @Rakesh9100 can you look at this once:
1. I have updated the index.html with my calculator
image

2. Enhanced the UI 
image

3. Handled the case when the input is NaN
image

If any further changes is to be made feel free to discuss and thank you for your patience.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Imbiber

**Pull request merged**
