### PR TITLE
Added Roots Equation Calculator

### LINKED ISSUE #1072: [Feature] Add Roots Equation Calculator
### Description

I want to add an equation generator calculator for given roots. First, it will ask for the number of roots and then the user has to enter the roots, after that, the equation would be generated.
Example 1: Number of roots = 2
                  root1= 2, root2= 2
                   equation =( x^2 - 4x +4 = 0)
Example2: number of roots = 3
                  root1=1, root2=1, root3=1
                  equation = (x^3 - 3x + 3x -1 =0)
Like this, it will work for any number of roots.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sharmi4590**
# Fixes Issue🛠️

Closes #1072 

# Description👨‍💻

Add an equation generator calculator for given roots. First, it will ask for the number of roots and then the user has to enter the roots, after that, the equation would be generated.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot (624)
Screenshot (622)
Screenshot (623)

### CODE REVIEW

**Comment by Nihal4777** [comment]
@sharmi4590 Just remove hyphens from title of the calculator in listing.

**Comment by sharmi4590** [comment]
@Nihal4777 done with the changes

**Comment by sharmi4590** [comment]
Hey @Nihal4777 Could u please look into my PR

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed and can be merged.

**Comment by sharmi4590** [comment]
@Rakesh9100 Could you please look into it

**Comment by sharmi4590** [comment]
Hey, @Rakesh9100 Please merge the PR, as after the 31st No PR will be counted.

**Comment by Nihal4777** [comment]
Hii @sharmi4590, Thank you so much for your contribution.
We really apologise for the delay caused. Don't worry your PR will get reviewed very soon within GSSoC period.

> Hey, @Rakesh9100 Please merge the PR, as after the 31st No PR will be counted.

**Pull request merged**
