### PR TITLE
Added TNEA Cut Off Calculator

### LINKED ISSUE #955: [Feature] Add TNEA Cut Off Calculator
### Description

Engineering admissions in Tamil Nadu are based on TNEA cut-offs. In this calculator, with the student's scores, the cut-off will be calculated. Please assign labels and assign me this issue under GSSOC 24.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by dharshini2022**
# Fixes Issue🛠️

Closes #955 

# Description👨‍💻

This PR consists of the addition of the Engineering Cut - Off Calculator. The Cut - Off calculation is done with respect to physics, chemistry and math marks.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-23 003722

### CODE REVIEW

**Comment by dharshini2022** [comment]
Sorry for posting the PR late. I had University exams. Please review my pull request and if any changes to be made, I'm happy to work on them. It was great working on your project! Thanks for providing me with this opportunity @Rakesh9100 .

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can be merged.

**Comment by Rakesh9100** [comment]
Is this Normal Cutoff Calculator or made based on TNEA cutoff @dharshini2022

**Comment by dharshini2022** [comment]
@Rakesh9100 It is made based on TNEA cut-off

**Comment by Rakesh9100** [comment]
Pls work on these and make the new commits in this same PR @dharshini2022 

1. Rename your calculator folder to `TNEA-Cut-Off-Calculator` and make the necessary changes.
2. Add your calculator part in the main `Ìndex.html` file to display it on the website.

**Comment by dharshini2022** [comment]
@Rakesh9100 I have made the changes, pls review it and is there any more changes to be made?

**Comment by Nihal4777** [comment]
@dharshini2022 It'd be great if there is limit on marks entered.
Also, there is no empty field validation.
image

**Comment by dharshini2022** [comment]
@Rakesh9100 I have worked on the above comments. Pls review it. Is there any more changes to be made?

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can be merged.

**Pull request merged**
