### PR TITLE
Added the favicon to each calculator's page

### LINKED ISSUE #786: [Feature] Add the favicon to each calculator's page
### Description

Favicon is not there in all the calculators , It is only there in the home page 
@Rakesh9100 assign this issue to me I will make it in all the pages

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Meetjain1**
# Fixes Issue🛠️

Closes #786 

# Description👨‍💻 

Added favicon to all pages.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Tested in my own local host.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/133582566/f75ce6e6-82db-4ba8-802d-5a56e2e21e5e

### CODE REVIEW

**Comment by Rakesh9100** [comment]
https://deploy-preview-1176--calcdiverse.netlify.app/

Check this deploy preview, I can see that favicon is just loading and buffering on the main website and not visible @Meetjain1

**Comment by Meetjain1** [comment]
> https://deploy-preview-1176--calcdiverse.netlify.app/
> 
> Check this deploy preview, I can see that favicon is just loading and buffering on the main website and not visible @Meetjain1

its working fine

**Comment by Meetjain1** [comment]
@Rakesh9100 it is working fine after a lot of hardwork , where is the issue let me know I checked the deploy link also , it is also working fine attached video of the same .

**Comment by Rakesh9100** [comment]
Yes, it is showing fine, maybe some issue on my network yesterday. But why the favicon is distorted. Make the favicon same as before or same as logo icon @Meetjain1

**Comment by Meetjain1** [comment]
> Yes, it is showing fine, maybe some issue on my network yesterday. But why the favicon is distorted. Make the favicon same as before or same as logo icon @Meetjain1

@Rakesh9100 it is not distorted it is the actual favicon created here https://www.favicon.cc/ , rather that just copy pasting of image .

**Comment by Rakesh9100** [comment]
You can just convert my favicon.png to favicon.ico, which will not distort the image, which I will do now @Meetjain1

**Pull request merged**
