### PR TITLE
Added Heart Rate Calculator

### LINKED ISSUE #272: [Feature] Heart Rate Calculator
### Description

A calculator which takes inputs as age and resting heart rate and gives the output as of heart rate of any person

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #272 

# Description👨‍💻 

Added Heart rate calculator

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Add a Readme file in your folder @AbhineshJha

**Comment by AbhineshJha** [comment]
have a check sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls add a screenshot in Readme file @AbhineshJha

**Comment by AbhineshJha** [comment]
done @Rakesh9100

**Comment by Rakesh9100** [comment]
Why in Overview, name of calculator is different, go through Readme and everything again and make the necessary changes @AbhineshJha

**Comment by AbhineshJha** [comment]
sorry for inconvenience sir @Rakesh9100 , i think everything now looks good !

**Comment by Rakesh9100** [comment]
Good, Merged 🎉 @AbhineshJha

**Pull request merged**
