### PR TITLE
Number System Calculator Added

### LINKED ISSUE #115: Add Number System Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100 !
Kindly assign me the issue to add the above calculator.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by muskan42**
Added a Number System Calculator

# Fixes Issue🛠️

Closes #115

# Description👨‍💻 

It converts: 
1. Binary to Hexadecimal and vice versa
2. Binary to octal and vice versa
3. Binary to Decimal and vice versa
# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

locally

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls update your forked repo witth the latest changes from the  original repo and then update the main `index.html` file as one div is missing.

Link the css and js file to your html file correctly.

Add a screenshot in your Readme file @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 I did as requested. Kindly check it.

**Comment by Rakesh9100** [comment]
Merged!! ✨ @muskan42

**Comment by muskan42** [comment]
Thank you! @Rakesh9100

**Pull request merged**
