### PR TITLE
Added Projectile Motion Calculator

### LINKED ISSUE #428: [Feature] Adding Projectile Motion Calculator
### Description

User can calculate max.height,Range,Time of Flight.

### Screenshots

swoc6

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Ishaparte**
**Fixes Issue🛠️**
closes #428 

**Description👨‍💻**
Added Projectile Motion Calculator.

**Type of change📄**

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)

**Checklist✅**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own cod
- [x] I have commented my code, particularly in hard-to-understand areas
- [x]  I have added demonstration in the form of screenshot
- [x] I am an Open Source Contributor

**Screenshots/GIF📷**
Screenshot 2024-01-26 201420

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls edit the PR description following the PR template @Ishaparte

**Comment by Ishaparte** [comment]
done! @Rakesh9100

**Comment by Rakesh9100** [comment]
Add a Readme of your calculator in your folder @Ishaparte

**Comment by Rakesh9100** [comment]
image

1. Handle the NaN values as when an user provides no inputs and click on Generate Result, it should give an alert.

2. Add a Readme of your calculator in your folder @Ishaparte

**Comment by Ishaparte** [comment]
Okay I will fix it

**Comment by Rakesh9100** [comment]
You will be unassigned if it is not fixed by today @Ishaparte

**Comment by Ishaparte** [comment]
Sorry for the delay @Rakesh9100 . I have commit the changes plz check.

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Ishaparte

**Comment by Ishaparte** [comment]
Thank you!

**Pull request merged**
