### PR TITLE
Enhanced Palindrome Calculator UI

### LINKED ISSUE #659: [Style] Enhance Palindrome Calculator UI
### Description

Hello @Rakesh9100 Sir,
Please assign me this issue.
I would like to change the design of the page for the palindrome checker, I will make changes to the background and the form that is currently being used to take input from the user.

This is for GSSoC'24 contribution.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by diyaaa19**
# Fixes Issue🛠️

Closes #659 

# Description👨‍💻 

Palindrome calculator UI enhanced along with calculate again button, and all items centrally aligned along with changes in form and background.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by diyaaa19** [comment]
@Rakesh9100 Please review and merge, completed all assigned issues

**Comment by Rakesh9100** [comment]
Pls attach the screenshots of your work @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 added the screenshots

**Comment by Rakesh9100** [comment]
When clicking on Calculate after entering an input, the result should show below only as it was before, it should not redirect to Calculate Again @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 made the required changes, please review, thanks

**Comment by Rakesh9100** [comment]
If an issue is open to enhance the UI, then pls make something good. You just did center some text and just changed some color @diyaaa19

**Comment by Rakesh9100** [comment]
https://calcdiverse.netlify.app/calculators/color-code-calculator/

You can take the reference of this and try to style a bit more by using some good background or gradient background, and also give effects to the text @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 Let me know if any more changes are required

**Pull request merged**
