### PR TITLE
Added Color Code calculator

### LINKED ISSUE #234: [Feature] Adding a Color Code Calculator
### Description

I would like to add a new calculator to the list of calculators, which shall allow inter-conversion between hex color codes and RGB values. Eg. #2CAAB1 (hex code) is equal to rgb(44, 170, 177) in rgb format. Please assign me this issue under IWOC 2.0

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #234 

# Description👨‍💻 

Added a new calculator that calculates the desired color code of a color in a given format. It can inter-convert color codes between RGB, RGBA, Hexadecimal, HSL, HSV and CMYK

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my local machine, after being hosted on localhost, looks and workd as intended.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-14 at 6 33 45 PM
Screenshot 2024-01-14 at 6 34 07 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls do add it after BMI Calculator in main `index.html` file to show it alphabetically if you want to add this calc on the top @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Pls do add it after BMI Calculator in main `index.html` file to show it alphabetically if you want to add this calc on the top @SoumyadevSaha

okay, on it.

**Comment by SoumyadevSaha** [comment]
updated the location @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls add a screenshot in Readme file @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Pls add a screenshot and Tech Stacks used in the Readme file @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Pls add a screenshot and Tech Stacks used in the Readme file @SoumyadevSaha

updated the readme: included the screenshots and the techstacks used.

**Comment by Rakesh9100** [comment]
Good job, Appreciated!! ✨

Merged, Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Good job, Appreciated!! ✨
> 
> Merged, Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @SoumyadevSaha

Thankyou so much 😁

**Comment by Rakesh9100** [comment]
Keep an eye on issues section if you want to take, opening some of them @SoumyadevSaha

**Pull request merged**
