### PR TITLE
Added Linear Regression Calculator

### LINKED ISSUE #1783: [Feature] Add Linear Regression Calculator
### Description

Linear Regression calculator will take a set of data points, compute the best-fit line using linear regression, and display the slope, intercept, and a plot of the data points with the regression line.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vivekvardhan2810**
# Fixes Issue🛠️

Closes #1783 

# Description👨‍💻

I have added Linear Regression Calculator. It is Useful for taking a set of data points, compute the best-fit line using linear regression, and display the slope, intercept, and a plot of the data points with the regression line.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-08-08 110926

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 Sir can you review and Merge the PR

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 sir

**Comment by Rakesh9100** [comment]
Don't comment again and again, your PR will be merged within the timeframe @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Okay @Rakesh9100 sir

**Comment by Nihal4777** [comment]
@vivekvardhan2810  Add your calc in main index.html file of the project.

**Comment by Nihal4777** [comment]
Also add some basic validations.
image

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 I have made the changes requested.

**Pull request merged**
