### PR TITLE
Added Keyboard Input for User Values in Basic Calculator

### LINKED ISSUE #258: Keyboard functioning in Basic Calculator
Describe a logic in Basic Calculator so that user can type the number on the calculator website using his/her PC keyboard!!

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #258

# Description👨‍💻 

Now user can use their keyboard to enter values, and also on pressing 'enter' the expression is evaluated.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my local machine, works and looks as intended

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Video Demo 📷

https://github.com/Rakesh9100/CalcDiverse/assets/86418216/d92bf357-123f-48c3-94e3-143e703f2226

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When user is clicking on that input box then only keyboard is working but again if user clicks on any button on the screen then again keyboard don't functions without focusing the cursor @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Restrict the alphabets @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Restrict the alphabets @SoumyadevSaha

Fixed @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged 🥳 @SoumyadevSaha

**Pull request merged**
