### PR TITLE
UI Enhanced for the Color Code Calculator 

### LINKED ISSUE #333: [Style] Design a better UI for the Color Code Calculator
### What's the style idea?

The current design is very plain and the background looks very dull. 
https://calcdiverse.netlify.app/calculators/color-code-calculator/

Solution:
The background color can be improved and the design of the calculator can also be improved.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by tarnibalgoher5**
# Fixes Issue🛠️

Closes #333

# Description👨‍💻 
The user interface should be simple yet catchy, which is what I have done by making the overall design minimal and user-appealing. The functionality and design of the buttons have been improved while keeping the user experience in mind.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I have manually tested using various possible combinations of input

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Follow the PR template and edit the PR description @tarnibalgoher5

**Comment by Rakesh9100** [comment]
Are you doing the edit @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
Yes i'm on it, actually wasn't able to access my pc today

**Comment by tarnibalgoher5** [comment]
how can I access the template again without opening a new pull request,since its not available in the readme file

**Comment by tarnibalgoher5** [comment]
Okay on it

**Comment by tarnibalgoher5** [comment]
updated!

**Comment by Rakesh9100** [comment]
image

Extend these dropdown box to make the word visible clear @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
Okay

**Comment by Rakesh9100** [comment]
Work on these:
1. Don't remove this showing example for entering input for every format.
image
2. Include emojis that was there in the buttons.
3. Hovering on buttons should be done smoothly, without expanding the box or dropdowns a little also @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
Okay

**Comment by tarnibalgoher5** [comment]
Made all the changes!

**Comment by Rakesh9100** [comment]
1. Enlarge the entire box to ensure that the text of Invalid input is fully visible.
2. Copy button emoji is disappearing when clicked a single time. Do fix.
3. Put a red cross or some emoji in Reset button as well @tarnibalgoher5

**Comment by Rakesh9100** [comment]
1. Enlarge the entire box to ensure that the text of Invalid input is fully visible.

2. Copy button emoji is disappearing when clicked a single time and hovering effect on Copy is also not working. Do fix.

3. Put a red cross or some emoji in Reset button as well @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
done

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @tarnibalgoher5

**Pull request merged**
