### PR TITLE
Added Water TDS Calculator

### LINKED ISSUE #985: [Feature] Add Water TDS Calculator
### Description

Water TDS  calculator would enable people to assess the quality of water and henceforth deciding it's drinkable or not. Almost everyday people fall ill due to consumption of contaminated water, so this calculator could help a lot of people. I would like to make this calculator, please assign this issue to me @Rakesh9100 .
thanks

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by diyaaa19**
# Fixes Issue🛠️

Closes #985 

# Description👨‍💻 

Water TDS calculator made successfully.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Water-TDS-Calculator` and make the necessary changes in this same PR by making the commits.

Also add your calculator in main `index.html` file to display it on the website @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 made the necessary changes, could you please confirm if I did it right?
also please add level label to #985 
Thanks

**Comment by Rakesh9100** [comment]
Pls check the folder name that I mentioned and rename again accordingly @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 sorry for the troubles, it's my first time contributing, I hope I met the requirements now. Please recheck and let me know, thanks for understanding.

**Comment by Rakesh9100** [comment]
Don't worry! Open Source is to learn, and I am always there to help you out!!

Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 can you please add the SWOC label as well, thanks

**Pull request merged**
