### PR TITLE
Added new results in Word Count Calculator

### LINKED ISSUE #522: [Feature] Add new results in Word Count Calculator
### Description

I would like to add new outputs result in the [Word Count Calculator](https://calcdiverse.netlify.app/calculators/word-count-calculator/). The outputs will be "the shortest word count" showing the shortest word count and, of course, the "longest word count". showing the longest word count. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SilviuPe**
# Fixes Issue🛠️

Closes #522 

# Description👨‍💻 

I implemented two new fields in Word-Count-Calculator. One for the shortest word count and one for the longest word count. Each of them has their own function that calculates which is shortest and which is longest. 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

This new feature was tested in my local and everything works well.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When we download or Export the result, your new results should be present @SilviuPe

**Comment by Rakesh9100** [comment]
When we download or Export the data, your new results should be present @SilviuPe

**Comment by SilviuPe** [comment]
> When we download or Export the data, your new results should be present @SilviuPe

Sorry! My bad. I'll solve it!

**Comment by Rakesh9100** [comment]
Make the changes in this PR only, don't create a new PR @SilviuPe

**Comment by Rakesh9100** [comment]
Are you working @SilviuPe

**Comment by SilviuPe** [comment]
> Are you working @SilviuPe

**Done!**  ✅✅✅

**Comment by Rakesh9100** [comment]
image

Make the color red @SilviuPe

**Comment by Rakesh9100** [comment]
Merged 🎉 @SilviuPe

**Pull request merged**
