### PR TITLE
Removed (00.00) on landing page of BMI Calculator

### LINKED ISSUE #306: [Bug] Visibility of Invalid BMI (00.00) on Landing Page
image

BMI (00.00) should not be visible when landing on BMI Calculator website!!

### PR DESCRIPTION
**Pull request by TanushreeBorase**
# Fixes Issue🛠️

Closes #306 

# Description👨‍💻 
Now I have made the close option align properly to the right-center.
# Type of change📄
- [☑️] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅
I have checked that on pressing Calculate BMI, the close option is aligned properly.

# Checklist✅ 

- [☑️] My code follows the style guidelines of this project
- [☑️] I have performed a self-review of my own code
- [☑️] I have commented my code, particularly in hard-to-understand areas
- [☑️] I have added demonstration in the form of GIF/video file
- [☑️] I am an Open Source Contributor

# Screenshots/GIF📷
image
image
image

### CODE REVIEW

**Comment by TanushreeBorase** [comment]
I have aligned close option now.

**Comment by Rakesh9100** [comment]
No need to open new second PR for aa small change or even big change. You can do any changes in opened PR only. Take care from the next time!!

Merged 🎉 @TanushreeBorase

**Comment by Rakesh9100** [comment]
No need to open new second PR for a small change or even big change. You can do any changes in opened PR only. Take care from the next time!!

Merged 🎉 @TanushreeBorase

**Comment by TanushreeBorase** [comment]
Thanks for guidance

**Pull request merged**
