### PR TITLE
Added Country names to Currency Calculator

### LINKED ISSUE #36: Adding Country names to Currency Calculator
### Prerequisites

- [x] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, @Rakesh9100, sir. I would like to make some changes to the currency converter. There are certain aspects that are missing and can be further modified. Kindly assign this task to me, sir.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by hemant933**
Now it shows the countries details for which you are converting the currency , when you give amount and specify currency and convert it , it will display countries.

# Fixes Issue🛠️

Closes #36 

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have added demonstration in the form of GIF/video file
- [*] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-13 114212

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @hemant933

**Comment by hemant933** [comment]
sir points are not assigned to me IWOC dashboard

**Comment by Rakesh9100** [comment]
It will take some time, get back to the discord moderator for the same @hemant933

**Comment by hemant933** [comment]
okay sir

**Pull request merged**
