### PR TITLE
Implemented Multilingual support

### LINKED ISSUE #873: [Feature] Add multilingual support to the website
### Description

On exploring the CalcDiverse, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.

### Screenshots

The below image of the website represents that it is only available in English language
WhatsApp Image 2024-05-25 at 16 06 32_c5244dce

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anjankumarkamalapur**
# Fixes Issue🛠️

Fixes #873 

# Description👨‍💻 

Implemented the Multilingual support.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (991)

Screenshot (992)

Screenshot (993)

### CODE REVIEW

**Comment by Anjankumarkamalapur** [comment]
@Rakesh9100 can you pls check it now

**Comment by Rakesh9100** [comment]
First of all, don't open PRs again and again. You can make your changes by pushing new commits in the same previous PR.

And second, your changes are still not visible @Anjankumarkamalapur

**Comment by Rakesh9100** [comment]
First of all, don't open PRs again and again. You can make your changes by pushing new commits in the same previous PR.

And second, your changes are still not visible @Anjankumarkamalapur

**Comment by Anjankumarkamalapur** [comment]
sorry for it can you pls.
I'm not able to commit change Im requesting you add below code after the
logo(CalcDiverse) section
<div id="google_element"></div>
                <script src="
http://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"
></script>
                <script>
                    function loadGoogleTranslate() {
                        new google.translate.TranslateElement({
                            pageLanguage: 'en'
                        }, 'google_element');
                    }
                </script>

**Comment by Anjankumarkamalapur** [comment]
can u pls add this after the logo section.
<div id="google_element"></div>
                <script src="
http://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"
></script>
                <script>
                    function loadGoogleTranslate() {
                        new google.translate.TranslateElement({
                            pageLanguage: 'en'
                        }, 'google_element');
                    }
                </script>

**Pull request closed without merging**
