### PR TITLE
Added Automorphic Number Calculator

### LINKED ISSUE #1148: [Feature] Add Automorphic Number Calculator
## Description
An automorphic number (also known as a circular number) is a number whose square ends in the same digits as the number itself. For example, 25 is an automorphic number because 25^2 = 625, and 76 is an automorphic number because 76^2 = 5776.

The Automorphic Number Calculator is a user-friendly tool designed to determine if a given number is an automorphic number. An automorphic number is one whose square ends with the number itself. This calculator takes a number input, computes its square, and checks if the square ends with the original number

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
# Fixes Issue🛠️

Fixes #1148 

# Description👨‍💻 

The Automorphic Number Calculator checks if a number is automorphic, meaning its square ends with the same digits as the number itself. It features input validation, result display, and buttons to reset, reload, and clear results, all within a modern, responsive interface

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested the feature in my local device and it is fully working.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image_2024-06-06_180738611

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@Rakesh9100 can you please check this pr and merge it .

**Comment by Pujan-sarkar** [comment]
@Rakesh9100 please merge it please

**Comment by Pujan-sarkar** [comment]
@Rakesh9100 please give a reply

**Comment by Rakesh9100** [comment]
Don't be impatient and comemnt again and again, your PR will be reviewed!

**Comment by Rakesh9100** [comment]
Don't be impatient and comment again and again, your PR will be reviewed!

**Pull request merged**
