### PR TITLE
Added Partial Derivative Calculator

### LINKED ISSUE #1330: [Feature] Add Partial Derivative Calculator
### Description

This calculator allows you to compute partial derivatives of multivariable functions.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Praneeth-2602**
# Fixes Issue🛠️

Closes #1330 

# Description👨‍💻

Added the partial derivative calculator.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Praneeth-2602** [comment]
@Rakesh9100 Please review the pr

**Comment by Nihal4777** [comment]
@Praneeth-2602 Handle empty fields 
image

**Comment by Praneeth-2602** [comment]
Oh ok👍
On it!!

**Comment by Praneeth-2602** [comment]
Done as directed!!

**Comment by Rakesh9100** [comment]
Rename your folder as `Partial-Derivative-Calculator` and make the necessary changes wherever required.

Add a Readme file of your calculator in your folder @Praneeth-2602

**Comment by Praneeth-2602** [comment]
@Rakesh9100 Please review the changes. Done as requested

**Pull request merged**
