### PR TITLE
Word Count Calculator Added

### LINKED ISSUE #291: [Feature] Word Count Calculator
### Description

I propose adding four new features to enhance the functionality of the word calculator:

1. **Total Word Count:** Include functionality to count and display the total number of words in the provided text.
2. **Unique Word Count:** Implement a feature to count and display the number of unique words in the text.
3. **Average Word Length:** Calculate and display the average length of words in the given text.
4. **Export Results:** Allow users to export the calculated results in different formats (e.g., CSV, JSON) for further analysis or documentation.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Tholkappiar**
# Fixes Issue🛠️

Closes #291 

# Description👨‍💻 

- Total Word Count: Include functionality to count and display the total number of words in the provided text.
- Unique Word Count: Implement a feature to count and display the number of unique words in the text.
- Average Word Length: Calculate and display the average length of words in the given text.
- Export Results: Allow users to export the calculated results in different formats (e.g., CSV, JSON) for further analysis or documentation.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested Completely in Local Environment

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot from 2024-01-16 10-02-36

### CODE REVIEW

**Comment by Rakesh9100** [comment]
The text should also be present with the results in the exported JSON file @Tholkappiar

**Comment by Rakesh9100** [comment]
Enhance the UI to certain extent as it is too simple for taking hard label else Medium label will be provided @Tholkappiar

**Comment by Tholkappiar** [comment]
okay , let me update the UI things !

**Comment by Tholkappiar** [comment]
#### Improved the Stylings as Referenced , Thank you.

[Screencast from 16-01-24 12:49:59 PM IST.webm](https://github.com/Rakesh9100/CalcDiverse/assets/114584730/11b77afc-4697-4f79-a498-031c4de3cf34)

**Comment by Rakesh9100** [comment]
I have noticed that on clicking Export Data without entering any text, it is downloading the file which should not. Provide an alert to handle this @Tholkappiar

**Comment by Tholkappiar** [comment]
Done , Handled the cases !

[Screencast from 16-01-24 01:02:36 PM IST.webm](https://github.com/Rakesh9100/CalcDiverse/assets/114584730/7d6ba48d-0c05-4728-8acc-d006d0724975)

**Comment by Rakesh9100** [comment]
Good job, Merged!! ✨🎉 @Tholkappiar

**Pull request merged**
