### PR TITLE
Added transition to all the homepage buttons

### LINKED ISSUE #44: CSS : Add transition to buttons
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The buttons the home page do not have any transitions and it looks a bit weird.

Please assign the issue to me, I have already solved it in my forked repository

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by SaranshBangar**
# Fixes Issue🛠️

Closes #44 

# Description👨‍💻 

I have added slight transition to all the buttons on the home page, moreover I have changed the cursor type to pointer when it is being hovered over any link

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

I have tested it on various different screen sizes and the website works flawlessly on all of them

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Edit the PR title and give similar to the work you have done @SaranshBangar

**Comment by Rakesh9100** [comment]
You should not give this long PR title from next time @SaranshBangar I am editing this time

**Comment by SaranshBangar** [comment]
Sorry sir, I will take care of it in the future

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @SaranshBangar

**Comment by SaranshBangar** [comment]
Understood sir, I am closing this PR and resolving the issue in a new PR

**Pull request closed without merging**
