### PR TITLE
Added Work unit conversion in Unit Calculator

### LINKED ISSUE #1632: [Feature] Add Work unit conversion in Unit Calculator
### Description

Convert the unit of work from Joules to ElectronVolt, Calorie, Kilocalorie, Foot-pound, Kilowatt-hour.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by techy4shri**
# Fixes Issue🛠️

Closes #1632 

# Description👨‍💻

- **HTML**
  - Added a new dropdown menu in the form for unit conversion with the following options: Joule (J), ElectronVolt (eV), Calorie (cal), Kilocalorie (kcal), Foot-pound (ft-lb), and Kilowatt-hour (kWh).
- **JS**
     - Added logic for conversion of unit for Work using International standards of conversion, with concise and efficient code.
### Reason for Changes
These changes were made to provide users with the ability to convert the work value into various units of energy. 

### Testing
- Verified that the dropdown menu appears correctly with the specified units.
- Ensured that the dropdown styling is applied correctly and the box size is increased.

Please review the changes and let me know if any adjustments are needed.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-08-04 002959

### CODE REVIEW

**Comment by Nihal4777** [comment]
@techy4shri  Thank you for your contribution.

**Comment by techy4shri** [comment]
> @techy4shri Thank you for your contribution.
> 
> Actually, User inputs like dropdown should be above the calculate button.
> 
> Also, there is some issue with result div height. You can remove height css property to fix this.
> 
> image

Okay,updating the code.

**Comment by techy4shri** [comment]
Here are the changes @Nihal4777 :
image
image

**Comment by Nihal4777** [comment]
This PR is reviewed & can be merged.

**Comment by Rakesh9100** [comment]
@techy4shri 

I said you in the issue to add the Work conversion feature in the [Unit Calculator](https://calcdiverse.netlify.app/calculators/unit-calculator/) and not the Work Calculator @techy4shri

**Comment by Rakesh9100** [comment]
I said you in the issue to add the Work conversion feature in the [Unit Calculator](https://calcdiverse.netlify.app/calculators/unit-calculator/) and not the Work Calculator @techy4shri

**Comment by techy4shri** [comment]
@Rakesh9100 @Nihal4777 done. Apologies for the error. 
image
Screenshot 2024-08-04 002959

**Pull request merged**
