### PR TITLE
Fixed the email validation in Contact form

### LINKED ISSUE #836: [Bug] Fix the email validation in Contact form
### Description

The user can submit the contact form with any email extensions , so that it would be an trouble. If we don't validate the mail it will leads to decrease in trust of the user about the website and it will lead to data leakage. So that I can do that validation and I request you to assign me this issue.

### Screenshots

WhatsApp Image 2024-05-24 at 12 43 20_b3638cf2

WhatsApp Image 2024-05-24 at 12 43 32_35d0ea5a

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by GnanariddhikaRavikumar**
# Fixes Issue🛠️

Closes #836 

# Description👨‍💻

The user can submit the contact form with any email extensions, so that it would be trouble. If we don't validate the mail, it will lead to decrease in trust of the user about the website, and it will lead to data leakage. Now this bug has been fixed and the email gets validated, only the valid mails are allowed.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

I have used different mail patterns to verify it, and it produces the expected output

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls check the deploy preview and try to Send the message, it is just giving the alert that Thanks for contacting but not sending the message @GnanariddhikaRavikumar 

https://deploy-preview-1272--calcdiverse.netlify.app/

**Comment by GnanariddhikaRavikumar** [comment]
Ok... @Rakesh9100 . I will check and let you know

**Comment by Rakesh9100** [comment]
Any update or should I close @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Give me 1 day time I'll look into it and update you.

**Comment by GnanariddhikaRavikumar** [comment]
It is showing the message near the text box field itself whether i need to change it as windows alert?? @Rakesh9100

**Pull request merged**
