### PR TITLE
Fixed card hover animation size

### LINKED ISSUE #632: [Bug] Fix card hover animation size
### Description

When you hover over the card the hover effect height is different for different cards. It must be same it is looking quite odd.
Please assign me this task under GSSoC'24 I will correct it.

### Screenshots

tg

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pankaj-bind**
# Fixes Issue🛠️

Closes #632 

# Description👨‍💻 

Card height and animation fixed.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Pls keep the gap between these two buttons as it was before @pankaj-bind

**Comment by pankaj-bind** [comment]
> image
> 
> Pls keep the gap between these two buttons as it was before @pankaj-bind

ok

**Comment by pankaj-bind** [comment]
image

**Comment by Rakesh9100** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/73993775/11811b49-2468-4ed0-893d-ee2a905c160e

Check and fix the hover issue coming, buttons are going out when hovered @pankaj-bind

**Comment by Rakesh9100** [comment]
Are you working @pankaj-bind

**Comment by pankaj-bind** [comment]
> Are you working @pankaj-bind

yes, soon I'll make a PR.

**Comment by Rakesh9100** [comment]
You can make the commits in this PR only, no need of new PR @pankaj-bind

**Comment by pankaj-bind** [comment]
raised a new PR card fixed #938

**Comment by jay3028** [comment]
change title name

**Comment by pankaj-bind** [comment]
> change title name

done

**Pull request closed without merging**
