### PR TITLE
Added Wedding Budget Calculator

### LINKED ISSUE #1160: [Feature] Add Wedding Budget Calculator
### Description

Wedding Budget Calculator: For planning and tracking wedding expenses.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by bharat-c27**
# Fixes Issue🛠️

Closes #1160 

# Description👨‍💻

A simple web application to calculate the total budget of a wedding, including a breakdown of various costs like venue, catering, decor, photography, entertainment, attire, and other expenses.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-07-31 160358

### CODE REVIEW

**Comment by bharat-c27** [comment]
Hello @Rakesh9100, I have completed the issue.
Can you please assign the PR to me ?

Thank you !!

**Comment by bharat-c27** [comment]
Hey @Rakesh9100 and @Nihal4777, this is my last PR.
I loved to contribute to the project. Thank you soo much

**Comment by Nihal4777** [comment]
> Hey @Rakesh9100 and @Nihal4777, this is my last PR. I loved to contribute to the project. Thank you soo much

We are also grateful for your contributions. Thank you very much.

**Comment by Nihal4777** [comment]
This PR is reviewed & can be merged.

**Comment by bharat-c27** [comment]
@Rakesh9100 can please merge the PR

**Pull request merged**
