### PR TITLE
Added Gratitude Journal Calculator

### LINKED ISSUE #1483: [Feature] Add Gratitude Journal Calculator
### Description

This calculator allows users to log daily gratitude points in a concise format.

User inputs their gratitude points for the day, separated by commas or semicolons.
The calculator processes the input and displays all logged points in a single, formatted line.

basically you can enter the gratitude words daily people said to you and accordingly it will calculate your gratitude points

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ananyag309**
# Fixes Issue🛠️

Closes #1483 

# Description👨‍💻

Added Gratitude Journal Calculator - This calculator allows users to log daily gratitude points in a concise format.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/145869907/a0916dbe-7362-441c-b98f-ca9b617595df

### CODE REVIEW

**Comment by Nihal4777** [comment]
@ananyag309 Can we include more positive and negative words.
You can easily ask any AI tool to generate large array of positive & negative words with points as well.

**Comment by ananyag309** [comment]
@Nihal4777 i will try to add more words, and if the positive word is not present in the list it will by default give it a count of 1

**Comment by Rakesh9100** [comment]
image

Pls handle the empty validation @ananyag309

**Comment by Rakesh9100** [comment]
### Pls handle the empty validation @ananyag309

image

**Comment by ananyag309** [comment]
@Rakesh9100 done

**Comment by Rakesh9100** [comment]
### If I input any random word, it is showing as positive gratitude which is not valid @ananyag309

image

**Comment by ananyag309** [comment]
@Rakesh9100 sir please check once i have made some changes 

https://github.com/user-attachments/assets/f6539f66-ca6f-4aba-8fcb-4b93562c337c

**Pull request merged**
