### PR TITLE
Added Days Until Deadline Calculator

### LINKED ISSUE #557: [Feature] Add Days Until Deadline Calculator
### Description

Count down days until project deadlines or due dates.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by kamalesh-og**
# Fixes Issue🛠️

Closes #557 

# Description👨‍💻 

This pull request adds a new feature to the website: a "Days Until Deadline Calculator." The calculator allows users to select a date and calculates the number of days remaining until that date. This includes the following changes:
- A user-friendly interface with a date input field and a calculate button.
- A visually appealing background gradient for the webpage.
- A semi-transparent container with a subtle pattern for better readability and aesthetics.

No additional dependencies are required for this change.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

This feature has been tested by:
- Manually selecting different dates and verifying that the correct number of days remaining is displayed.
- Ensuring the gradient background and patterned container render correctly on various screen sizes.
- Checking the readability of text within the container against the patterned background.
- Verifying that the site functions correctly across different browsers (Chrome, Edge).

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added a demonstration in the form of Screenshots.
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### After Clicking the Try Now,
image

### To check how the date is selected,
image

### Sample Output,
image

### CODE REVIEW

**Comment by kamalesh-og** [comment]
Hello Project Admin,
I've updated the new feature that was assigned to me, Can you merge my PR into yours @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls add `Readme.md` file of your calculator @kamalesh-og

**Comment by kamalesh-og** [comment]
Hello Project Admin,
I've updated the README.md file into my pull request, Can you merge my PR into yours @Rakesh9100
Also Can you please add Level 1, 2, or 3 to the Issue because then only the project will be considered for my points.
Thank you

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @kamalesh-og

**Comment by kamalesh-og** [comment]
Thank you @Rakesh9100 👍🏻

**Pull request merged**
