### PR TITLE
Enhanced social media icons

### LINKED ISSUE #895: [Style] Enhance social media icons
### What's the style idea?

**Highlight the user experience (UX) benefits**: "I'd like to propose adding hover effects to the social media icons. This would make the icons more interactive and engaging for users, and it would also provide a clearer visual cue that the icons are clickable links."

Screenshot (6897)
Screenshot (6900)
Screenshot (6901)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sakshi261203**
# Fixes Issue🛠️

Closes #895 

# Description👨‍💻

In the updated CSS, the primary change involves adding a glow effect to the icons when they are hovered over. This is achieved by applying a `box-shadow` property to the `.fa` elements within the list items on hover, creating a glowing effect with the current color of the icons. Additionally, a slight upward movement is introduced to the icons using the `transform: translateY(-5px)` property on hover. This replaces the previous individual hover color changes for each social link class, unifying the hover effects and ensuring the glow only affects the icons without altering the borders. The overall transition and positioning properties are maintained to ensure smooth animations.

# Type of Change📄

- [X] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot (7243)
Screenshot (7244)
Screenshot (7245)

### CODE REVIEW

**Comment by sakshi261203** [comment]
Sir,  please add the labels of level.

**Comment by Nihal4777** [comment]
@sakshi261203 You have enhanced them that's okay but why are they not working now?

**Comment by sakshi261203** [comment]
Sir, but it is working on my side. Could you please check again?

**Comment by Rakesh9100** [comment]
The hover effect is only working on the home page, and the lines above the icons do not look good. The hover effect is not consistent with the screenshot you provided in your opened issue, @sakshi261203

**Pull request closed without merging**
