### PR TITLE
Length Convertor Added

### LINKED ISSUE #24: Length Converter
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  I want to add Length converion from km to m, m to cm etc.Please assign issue to me

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by JrG-One**
# Fixes Issue🛠️

Closes #24 

# Description👨‍💻 

I have added a Length Calculator, which converts the length between two specified units.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested each unit and conducted manual conversions, and everything is functioning correctly.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls mention the issue number this PR closes in Closes #

Delete the .vscode folder and its files.
Add a Readme.md file as well in the calculators folder which includes descripton of the calc, tech stacks used and screenshot of the calculator @JrG-One

**Comment by JrG-One** [comment]
Ok i'll do that

**Comment by Rakesh9100** [comment]
Looks nice, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @JrG-One

**Comment by JrG-One** [comment]
Completed those specified changes

**Comment by Rakesh9100** [comment]
Looks nice, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @JrG-One

**Pull request merged**
