### PR TITLE
Added Spy Number Calculator

### LINKED ISSUE #1262: [Feature] Add Spy Number Calculator
### Description

A number is said to be a Spy number if the sum of all the digits is equal to the product of all digits.
Input : 1412
Output : Spy Number
Explanation : 
sum = (1 + 4 + 1 + 2) = 8
product = (1 * 4 * 1 * 2) = 8
since, sum == product == 8

### Screenshots

Capture

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by poseidonsanket**
# Fixes Issue🛠️

Closes #1262 

# Description👨‍💻

Added a Spy number calculator and checker
A number is said to be a Spy number if the sum of all the digits is equal to the product of all digits.
Input : 1412
Output : Spy Number
Explanation :
sum = (1 + 4 + 1 + 2) = 8
product = (1 * 4 * 1 * 2) = 8
since, sum == product == 8

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot (99)

### CODE REVIEW

**Comment by poseidonsanket** [comment]
@Rakesh9100 please check

**Comment by Rakesh9100** [comment]
1. Check all the spy numbers by entering 8 and then scroll the page to up, it is not going to the top. Pls fix.
2. Also, style and enhance the UI @poseidonsanket

**Comment by poseidonsanket** [comment]
@Rakesh9100 
Screenshot (101)
is this better or can you suggest me a design

**Comment by poseidonsanket** [comment]
@Rakesh9100 when calculating spy number above 5 it requires high computational task so the screen freezes so i have made changed that it can calculate spy numbers upto 5 digits

**Comment by poseidonsanket** [comment]
@Rakesh9100 please check

**Comment by Rakesh9100** [comment]
image

Below the text 1412 is a Spy Number, also add the explanation in short how it is Spy and for non-Spy also add respectively @poseidonsanket

**Comment by poseidonsanket** [comment]
@Rakesh9100 
Capture
it this okay

**Comment by Rakesh9100** [comment]
Yes fine, commit it @poseidonsanket

**Comment by poseidonsanket** [comment]
@Rakesh9100 done

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can be merged.

**Comment by poseidonsanket** [comment]
@Rakesh9100 can you add a gssoc level 1 or level 2 tag before merging

**Pull request merged**
