### PR TITLE
Added custom cursor to the website

### LINKED ISSUE #1051: [Feature] Add custom cursor to the website
### Description

Enhances of custom cursor pointer.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Fixes Issue🛠️

Closes #1051 

# Description👨‍💻

Added custom cursor to the website.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

https://github.com/Rakesh9100/CalcDiverse/assets/154777864/8f6b8cd9-a1d8-4a07-9cb0-9b45d1958064

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR.

**Comment by Nihal4777** [comment]
@Rakesh9100

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Rakesh9100** [comment]
Pls work on these @Anjaliavv51 

1. Implement some light color as background is blue, so purple is not visible properly but make sure to match the UI.
2. Add the same cursor on About, Contributors, FAQ and Contact page.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 sure

**Comment by Anjaliavv51** [comment]
image

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
Hold on, don't comment again and again, let me review, label will be added once PR is merged!

I cannot see the cursor on About and Contact page, pls check and also pure white don't look good, you can use multi colors as you used in project Beautiify but match the UI @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 sure

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the changes.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR.

**Comment by Rakesh9100** [comment]
Please check the About and Contact page in this [Deploy preview](https://deploy-preview-1474--calcdiverse.netlify.app/), the content is not showing, pls fix it properly, also keep the logic externally and not internally in .html file @Anjaliavv51

**Comment by Anjaliavv51** [comment]
image

image

@Rakesh9100 please check the deploy , it is added. above are the screenshoots.

**Comment by Rakesh9100** [comment]
This is only I am saying, after your custom cursor is added, the main content is not showing and the loader and your cursor is only showing @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 I think it can't be added to those two files , due to some conflicts between the js script

**Comment by Rakesh9100** [comment]
It's not about any conflict, but rather about the logic you need to consider and implement to ensure that no script causes delays or leads to content being overridden @Anjaliavv51

**Comment by Anjaliavv51** [comment]
> It's not about any conflict, but rather about the logic you need to consider and implement to ensure that no script causes delays or leads to content being overridden @Anjaliavv51

Okay I rewrite the code

**Comment by Rakesh9100** [comment]
If you are unable to do, then you can remove your custom cursor from those two pages and make the commits, I will fix that afterward @Anjaliavv51

**Comment by Anjaliavv51** [comment]
> If you are unable to do, then you can remove your custom cursor from those two pages and make the commits, I will fix that afterward @Anjaliavv51

I will give it a try and mention u

**Comment by Anjaliavv51** [comment]
@Rakesh9100 it is done u can merge the PR. 

https://github.com/user-attachments/assets/576e98a0-d5fd-4f8f-b552-c05278174a9c


https://github.com/user-attachments/assets/789f0a0a-4a79-4eda-aaea-f42b69c804f0

**Pull request merged**
