### PR TITLE
Added Plant Care Calculator

### LINKED ISSUE #1607: [Feature] Add Plant Care Calculator
### Description

The Plant care calculator will help plant owners create a schedule according to their specific plants needs. Users input details will be like plant type, size, location, season, watering frequency etc. The output will be a dedicated **schedule** for watering, fertilizing, and repotting. Please assign this issue under GSSOC'24 @Rakesh9100 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
# Fixes Issue🛠️

Closes #1607 

# Description👨‍💻

This calculator calculates schedule for aspects like watering, fertilizing and repotting plants based upon the plant size, season, location and water frequency.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

plant1

https://github.com/user-attachments/assets/ec857c9f-6006-48b5-86fa-dd9ecc1a8791

### CODE REVIEW

**Comment by Nihal4777** [comment]
Hi, @anagha-chaudhari What's use of plant type here?
image

**Comment by anagha-chaudhari** [comment]
@Nihal4777 here plant type intended to indicate what kind of plant it is, for eg: a rose plant, tulsi plant, snake plant etc

**Comment by anagha-chaudhari** [comment]
@Nihal4777 @Rakesh9100 Please review the pr

**Comment by Nihal4777** [comment]
> @Nihal4777 here plant type intended to indicate what kind of plant it is, for eg: a rose plant, tulsi plant, snake plant etc

Does it have any effect on result?

**Comment by anagha-chaudhari** [comment]
@Nihal4777 The calculator gives results based upon size, location, season and water-frequency. I have used the plant type field to know the type/name of the plant

**Comment by anagha-chaudhari** [comment]
Please review @Nihal4777 @Rakesh9100

**Comment by Nihal4777** [comment]
@anagha-chaudhari Don't worry, @Rakesh9100 will accept PR after reviewing it.

**Pull request merged**
