### PR TITLE
Added more functionalities in Typing Speed Calculator

### LINKED ISSUE #1493: [Feature] Add more functionalities in Typing Speed Calculator
### Description

ISSUES:-
1) The result of this calculator **disappears in 1.5 secs**, leading to **inconvenience in readability** to the users and thus, **failing the purpose of taking the test.**
2) The **parameter** of determining the speed by only one line is **insufficient.** 

MY IMPLEMENTATIONS:-
1) Introduce a **'Retake Test'  button.** After taking the test, the results will be shown for as long as the 'Retake Test' button  is not clicked.
2) Introduce:-
     a) **3 levels of difficulty**- easy, medium, hard. Introducing digits, special characters based on difficulty level.
     b) **Test duration** of 1min, 3mins, 5 mins- to analyze better
     c) Display the result in **standard units- wpm**(words per minute) .
I would like to fix this bug and add this feature for accuracy. Kindly assign this to me.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Nidhi-Satyapriya**
# Fixes Issue🛠️

Closes #1493 

# Description👨‍💻

I added the following functionalities:- 
1) 3 levels of difficulty-easy, medium, hard. Introducing digits, special characters based on difficulty level.
2) Test duration of 1 min, 3 mins, 5 mins.
3) Display the result in standard units-wpm (words per minute).
4) Display the level of accuracy and no. of corrections made while typing.
5) Introduce a 'Retake Test' button. After taking the test, the results will be shown for as long as the 'Retake Test' button is not clicked. Earlier, the result of this calculator disappeared in 1.5 secs, leading to inconvenience.
6) Introduce a 'Reset' button, which clears the input by users so they could retype the sentence as desired.
7) JS covers all edge cases. E.g. - "You did not type."

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-07-08 095313

Screenshot 2024-07-08 095424

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed and can be merged.

**Comment by Nidhi-Satyapriya** [comment]
Thanks @Nihal4777 .  Over to you, @Rakesh9100

**Comment by Rakesh9100** [comment]
### It will look good if you provide a dropdown to choose the option for both @Nidhi-Satyapriya 

image
image

**Comment by Rakesh9100** [comment]
### It will look good if you provide a dropdown to choose the option for both @Nidhi-Satyapriya 

image
image

### Also, we can Start the test without selecting difficulty and duration, so handle this as well!

**Comment by Rakesh9100** [comment]
### It will look good if you provide a dropdown to choose the option for both @Nidhi-Satyapriya 

image
image

### Also, ensure the user selects both the difficulty and duration before starting the test!

**Comment by Rakesh9100** [comment]
Are you working @Nidhi-Satyapriya

**Comment by Nidhi-Satyapriya** [comment]
Yes sir, I am. Will be present with the changes asap. @Rakesh9100

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 I made the recommended changes. kindly look over it.

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 Hi!  Do you approve of this now?!

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 It's been long. GSSoC end is nearing. How did you find it?

**Comment by Nidhi-Satyapriya** [comment]
@Nihal4777 @Rakesh9100 Can you review this once. It's been three weeks. There are only few days left for GSSOC to get over.

**Comment by Nihal4777** [comment]
Hii @Nidhi-Satyapriya, Thank you so much for your contribution.
We really apologise for the delay caused. Don't worry your PR will get reviewed very soon within GSSoC period.

**Pull request merged**
