### PR TITLE
feat: UI-main-page-changed

### LINKED ISSUE #28: Designing a good UI for the website
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I can make a good interface for the website, which is creative and add some effect to it to make it good looking and attractive, please assign this issue to me.

### Screenshots

image
It needs good color combination and some good effects to make it look attractive.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by rishita0205**
# Fixes Issue🛠️

Closes #28

# Description👨‍💻 
UI change

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/140805496/622de53b-2a32-4724-a5e3-33d96dddec4c

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls don't remove the logo from the main page.

image
Do the headings of the boxes in center and also increase the size of font.
Also put hover effect on the boxes and enhance it more.
Also Try Now button should be in left and github logos in right. @rishita0205

**Comment by Rakesh9100** [comment]
### Pls don't remove the logo from the main page.

image
### Do the headings of the boxes in center and also increase the size of font.
### Also put hover effect on the boxes and enhance it more.
### Also Try Now button should be in left and github logos in right. @rishita0205 

Resolve the conflicts as well.

**Comment by rishita0205** [comment]
will this work
image

**Comment by Rakesh9100** [comment]
Seems fine but work on all other changes as well.
Make sure the calculators section don't start on the landing page @rishita0205

**Comment by rishita0205** [comment]
hii @Rakesh9100  I made sure the calculator section doesn't start on the landing page but I  can't figure out some CSS properties of the box can you please provide a guide on it? How do I place the "try now" and GitHub buttons? here's how it is looking right now
image

**Comment by rishita0205** [comment]
Also I tried the heading to be centre aligned but it is not looking that good I suggest it should be kept left aligned

**Comment by Rakesh9100** [comment]
image

It should be like this. You can achieve this by using `float:left` and `float:right` CSS property for Try Now buttons and github logo respectively.

And those headings are the names of calculators so center it @rishita0205

**Comment by rishita0205** [comment]
ok! I will try to make these changes

**Comment by rishita0205** [comment]
@Rakesh9100 will this work?
image

**Comment by Rakesh9100** [comment]
Just go top and read the suggested changes again and work accordingly @rishita0205

**Comment by Rakesh9100** [comment]
Are you working on the changes @rishita0205

**Comment by rishita0205** [comment]
image
these are the changes I have made on the boxes does it look good now? @Rakesh9100

**Comment by Rakesh9100** [comment]
image

Why there are uneven spaces above and below the Try Now button @rishita0205 
Give some spaces above those buttons and increase the size of those both buttons.
Also, have you provided some good hover effect to the box and buttons @rishita0205

**Pull request closed without merging**
