### PR TITLE
Added Air Fuel Ratio (AFR) Calculator

### LINKED ISSUE #1872: [Feature] Add Air Fuel Ratio (AFR) Calculator
### Description

An Air-Fuel Ratio (AFR) Calculator is a tool used to calculate the ratio of air to fuel used in an internal combustion engine. The ratio of air to fuel is critical in determining the efficiency and emissions of the engine. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by abhirajadhikary06**
# Fixes Issue🛠️

Closes #1872 

# Description👨‍💻

**AFR Calculator Functionality Overview:**

1. Mass Input
   - Multi-unit conversion (grams, kg, pounds)
   - Dynamic unit selection
   - Precise mass input for air and fuel

2. Calculation Engine
   - Air-fuel ratio calculation
   - Two-decimal precision result
   - Input validation mechanism

3. Fuel Intelligence
   - 30-fuel comprehensive database
   - Predefined standard AFR values
   - Searchable fuel dropdown

4. Search Dynamics
   - Real-time fuel filtering
   - Instant dropdown navigation
   - Responsive search interface

5. AFR Reference
   - Instant fuel-specific AFR display
   - Quick standard ratio lookup

6. UI/UX Design
   - Responsive modern layout
   - Interactive green color scheme
   - Smooth transition effects
   - Mobile-friendly interface

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 I have raised a pull request kindly look into it.

**Comment by Rakesh9100** [comment]
Please add a Readme for your calculator in your folder and also add your calculator in the main `index.html` file, make the new commits in this same PR @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 please look after the changes made. Hope now it is in mergeable state

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 please check the issue has not yet been resolved, contributions are not yet being counted

image

**Comment by Rakesh9100** [comment]
The cron jobs has not yet run by KWOC team to update the contributions, so wait for few days to get updated @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
> The cron jobs has not yet run by KWOC team to update the contributions, so wait for few days to get updated @abhirajadhikary06 

Thanks for the update

**Pull request merged**
