### PR TITLE
Added Special Number-2 Calculator

### LINKED ISSUE #1282: [Feature] Add Special Number-2 Calculator
### Description

Addition of Special Number Calculator. This will show whether the input number is a special number or not.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shreya-paul-17**
# Fixes Issue🛠️

Closes #1282 

# Description👨‍💻

Special Number-2 Calculator added.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

ss-5

### CODE REVIEW

**Comment by Nihal4777** [comment]
@shreya-paul-17  Please fix main index file .
image

**Comment by shreya-paul-17** [comment]
@Nihal4777 please check

**Comment by Nihal4777** [comment]
@shreya-paul-17 Yes the issue is resolved.
You and briefly explain why the number is special or not.
image

**Comment by shreya-paul-17** [comment]
@Nihal4777 Done. Kindly review my PR

**Comment by shreya-paul-17** [comment]
@Rakesh9100 , @Nihal4777 please review my PR

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by shreya-paul-17** [comment]
@Rakesh9100 please merge my PR and add necessary labels to it

**Comment by shreya-paul-17** [comment]
@Nihal4777 please tell @Rakesh9100 to merge my PR because after 31st July, no PRs will be further counted

**Comment by Nihal4777** [comment]
Hii @shreya-paul-17 , Thank you so much for your contribution.
Don't worry your PR will get reviewed very soon within GSSoC period.

**Comment by shreya-paul-17** [comment]
Thank you @Nihal4777 . But my PR has already been reviewed by you. Only thing is left by @Rakesh9100 to merge this PR

**Pull request merged**
