### PR TITLE
Added Search Bar for searching calculators

### LINKED ISSUE #287: [Feature] Search Bar/Tab for searching calculator
### Description

Search feature using keyword searching for finding user required calculator. 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️

#287 Search Bar/Tab for searching calculator.

Closes #287 

# Description👨‍💻 

Added **search bar** to search calculator.
This feature **filters** the **calculator** based on input.
For creating this I have used **HTML, CSS** and **JavaScript.**

I have taken care to **not disturb** the **original UI of website** and make it **responsive.**

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

This have been tested by me by running the website, no error found!!

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/149922307/a04f8ecd-3b84-4e45-ae58-7f6aea1b213f

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly check 😊

**Comment by Rakesh9100** [comment]
Place it above this #calculators section page @Prince-kushwaha-2004 

image

**Comment by Rakesh9100** [comment]
Pls place it above this #calculators section page @Prince-kushwaha-2004 

image

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Done👍

**Comment by Rakesh9100** [comment]
Not done, you have to place this search bar at the top in the calculators section. When we click on `Explore Calculators` button, then calculators section comes but search bar should come and below that the calculators!! @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
now I understand  I will do it in 10 min just wait

**Comment by Prince-kushwaha-2004** [comment]
Now working perfectly👍

**Comment by Rakesh9100** [comment]
Good job, Merged 🥳🎉 @Prince-kushwaha-2004

**Comment by Rakesh9100** [comment]
Good job, Merged 🥳🎉 @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Thankyou sir but i was accepting it in hard section as a first year student😔

**Comment by Rakesh9100** [comment]
I don't think it goes for hard but increasing the level seeing your activeness and dedication ✨ @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Thank you sir soon I will add a voice command search for this calculators😊

**Pull request merged**
