### PR TITLE
Added Frequency Calculator

### LINKED ISSUE #1288: [Feature] Add Frequency Calculator
### Description

A Frequency Calculator is designed to compute the frequency of a periodic event or waveform. Frequency is a fundamental concept in physics, particularly in the study of waves, oscillations, and alternating current (AC) circuits. It refers to the number of cycles or oscillations that occur in a unit of time, typically measured in hertz (Hz), where 1 Hz equals one cycle per second.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
# Fixes Issue🛠️

Closes #1288 

# Description👨‍💻

A Frequency Calculator is designed to compute the frequency of a periodic event or waveform. Frequency is a fundamental concept in physics, particularly in the study of waves, oscillations, and alternating current (AC) circuits. It refers to the number of cycles or oscillations that occur in a unit of time, typically measured in hertz (Hz), where 1 Hz equals one cycle per second.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your calculator part in the main `index.html` file to display it on the website by making the new commits in this same PR @Maheshwari-Love

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 added the changes

**Comment by Rakesh9100** [comment]
Style and enhance the UI @Maheshwari-Love

**Comment by Rakesh9100** [comment]
Are you working @Maheshwari-Love

**Comment by Maheshwari-Love** [comment]
> Are you working @Maheshwari-Love

Yes of course, till tomorrow I wil commit...

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 enhanced the UI

> Style and enhance the UI @Maheshwari-Love

Enhanced the UI and Styles

**Pull request merged**
