### PR TITLE
Added Sugar Intake Calculator

### LINKED ISSUE #1354: [Feature] Add Sugar Intake Calculator
### Description

This sugar intake calculator provides a simple way for users to calculate their total sugar consumption over a specified period based on their daily intake.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Fixes Issue🛠️

Closes #1354 

# Description👨‍💻

Added Sugar Intake Calculator to know the amount of intake of sugar.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Sugar-Intake-Calculator

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Please review it soon

**Comment by Saipradyumnagoud** [comment]
image

**Comment by Saipradyumnagoud** [comment]
Made The changes @Rakesh9100

**Comment by Rakesh9100** [comment]
Style and enhance the UI @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Yes i have updated the file
you can check now

**Comment by Rakesh9100** [comment]
Enhance the UI with some good gradient background color, font color and so on @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> Enhance the UI with some good gradient background color, font color and so on @Saipradyumnagoud

Yes sir i will do it in a while

**Review by Saipradyumnagoud — COMMENTED** [review]
Made the chages and improved the UI @Rakesh9100

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by Saipradyumnagoud** [comment]
Yes @Rakesh9100 please Review is soon sir..

**Pull request merged**
