### PR TITLE
UI enhanced of every calculator

### LINKED ISSUE #369: [Style] UI appearance of every calculator
### What's the style idea?

We need to improve the user interface of the appearance of the each calculator. You can check it out.

https://github.com/Rakesh9100/CalcDiverse/assets/117648930/b9ea1e41-f1f2-4c77-9fe4-471f349fb1a6

Hey @Rakesh9100 , I hope this will catch you fine, let me know if any improvement is required, or I am ready to commit.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Shantanu-Meta**
# Fixes Issue🛠️

Closes #369 

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor
Screenshot 2024-01-21 112536

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Shantanu-Meta** [comment]
Hey @Rakesh9100 , I have made this pr plz review once and suggest if changes is needed

**Comment by Shantanu-Meta** [comment]
Hey @Rakesh9100 , is the PR ok or not ?

**Comment by Rakesh9100** [comment]
Pls work on these!! @Shantanu-Meta 
1. Why many last rows calcs has the same color, do fix
2. Can you design Try now and Github icon as well similar to UI and provide some good animation and hover effects.
3. Put the heading names of the calculators in center.
4. Scroll to Top button is disturbed.
image

**Comment by Rakesh9100** [comment]
### Looks good, Pls work on these!! @Shantanu-Meta 

1. Why many last rows calcs has the same color, do fix
2. Can you design Try now and Github icon as well similar to UI and provide some good animation and hover effects.
3. Put the heading names of the calculators in center.
4. Scroll to Top button is disturbed.
image

**Comment by Shantanu-Meta** [comment]
Okay i am on it.

**Pull request closed without merging**
