### PR TITLE
Added Trigonometric Function Graphing Calculator

### LINKED ISSUE #470: [Feature] Trigonometric Function Graphing Calculator
### Description

**I want to add a Trigonometric Function graphing calculator which gives the solution with a  graph as per the given function**

**For example -**
**sin, cos, tan, etc.**

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Fixes Issue🛠️

Closes #470 

# Description👨‍💻 

I have added the Trigonometric Function graphing calculator which gives the solution with a graph as per the given function

For example -
sin, cos, tan, etc.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally and worked as expected

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/140608790/e7747a2b-70b7-4578-b560-103f6f9253bc

image

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please have a look into this PR

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 ?

**Comment by Rakesh9100** [comment]
Add a Readme file of your calculator in your folder @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Why did you do so sir?

**Comment by Rakesh9100** [comment]
Pls avoid creating new PR for just making a small change or even a big change!!

You should learn to make changes to the opened PR only @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please check now

**Comment by Rakesh9100** [comment]
Merged 🎉 @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
Thank you @Rakesh9100 
Could you please change the label to "hard"
It consumed a lot of time to add graphs to the website

**Comment by JiyaGupta-cs** [comment]
Thank you @Rakesh9100

**Comment by Rakesh9100** [comment]
This issue is being considered as Hard Level only, Medium was added by mistake @JiyaGupta-cs

**Comment by Rakesh9100** [comment]
This issue is intended to be classified as a Hard Level only, Medium was added by mistake @JiyaGupta-cs

**Pull request merged**
