### PR TITLE
Added Loan Repayment Date Calculator

### LINKED ISSUE #438: [Feature] Addition of a loan repayment date calculator
### Description

I want to contribute in this project through JWOC'24 by adding a feature of loan repayment date calculator.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SuvayuN**
Closes #438 

# Description👨‍💻 

This is a new loan repayment year calculator which can calculate the year by which the loan would be cleared. This calculator requires type of interest(Simple or Compound), interest of loan, amount of loan, return amount per year and the loan approval year as input and can give the year by which the loan would be cleared.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested the code by giving multiple values as input and got precise output for each test case.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (1)
Screenshot (2)
Screenshot (3)
Screenshot (4)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these changes:

1. Remove the favicon or use some different one.
2. Change and use different background than the main UI.
3. Enhance and design your UI buttons and everything.
4. Rename your folder to `Loan-Repayment-Date-Calculator` and make the necessary changes.
5. Handle the NaN values by providing an alert when clicked on Calculate without entering any value.

@SuvayuN

**Comment by Rakesh9100** [comment]
You will be unassigned if changes are not made by today @SuvayuN

**Comment by SuvayuN** [comment]
> Pls work on these changes:
> 
> 1. Remove the favicon or use some different one.
> 2. Change and use different background than the main UI.
> 3. Enhance and design your UI buttons and everything.
> 4. Rename your folder to `Loan-Repayment-Date-Calculator` and make the necessary changes.
> 5. Handle the NaN values by providing an alert when clicked on Calculate without entering any value.
> 
> @SuvayuN

Worked on it✅

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @SuvayuN

**Pull request merged**
