### PR TITLE
Added Neon Number Calculator

### LINKED ISSUE #520: [Feature] Adding Neon Number Calculator
### Description

A neon number is a number where the sum of digits of the square of the number is equal to the number. The task is to check and print neon numbers in a range.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️

Closes #520 

# Description👨‍💻 

Added new calculator to check and find neon number in range.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Neon

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Rakesh9100** [comment]
Let suppose I entered number 100 and clicked on Check, it is displaying `100 is not a Neon number. The square of 100 is 10000. The sum of its digits is 1.`

But for 9, it is just showing `9 is a Neon number.` It should display how it is neon @AftabMankapure

**Comment by AftabMankapure** [comment]
check now

**Comment by AftabMankapure** [comment]
ne

**Comment by Rakesh9100** [comment]
0 is also Neon, fix it @AftabMankapure

**Comment by Rakesh9100** [comment]
0 is also Neon but it is showing to enter a valid positive integer, fix it @AftabMankapure

**Comment by AftabMankapure** [comment]
n1

**Comment by Rakesh9100** [comment]
Merged 🎉 @AftabMankapure

**Pull request merged**
