### PR TITLE
Modified Basic and Multiplication Table Calculator

### LINKED ISSUE #498: [Style] Enhance Basic Calculator and Multiplication Table Calculator
### What's the style idea?

Hello @Rakesh9100, I want to redesign the Basic Calculator and the multiplication table calculator as it has very basic UI

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #498 

# Description👨‍💻 

Basic Calculator:
-> Refreshed with all new design
-> Added Dark and Light Modes

Multiplication Table Calculator:
-> Some changes in the basic design of calculator
-> All new way to display table without cropping the content -> Responsiveness added

# Type of change📄

- [X] Bug fix (In both calculators)
- [X] New feature (Dark light mode in Basic Calculator)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of image file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

image
image

### CODE REVIEW

**Comment by Yuvraj960** [comment]
Rakesh removing the comma isn't possible as some functions like power(^) don't work without a comma. 
For the file name thing, I will do it

**Comment by Rakesh9100** [comment]
Ohkk, but we need a backspace button @Yuvraj960

**Comment by Rakesh9100** [comment]
Ohkk, but we need a backspace button as well @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, I understand, but how do I introduce the backspace button. There's no space left to introduce the all new button in the UI.

**Comment by Yuvraj960** [comment]
@Rakesh9100, please review the code again, necessary changes done in the calculator.

**Comment by Rakesh9100** [comment]
Pls check the Log function as it is not giving the correct result.

And previously, calculator was working with the keyboard numpad or buttons as well but I suppose you have deleted script.js file, so fix it!!

**Comment by Yuvraj960** [comment]
@Rakesh9100, I didn't understand why you are not getting accurate results in log. 
I have compared and verified atleast 20-30 times and I am having accurate results each time. 
Here's live demonstration of what my calculator gives vs google results:

https://github.com/Rakesh9100/CalcDiverse/assets/146326636/859b853c-f8a7-408a-a404-7f402ff39ddd

image

And secondly I have removed the functionality of keypress events record because in many browsers like firefox, every keypress on page is toggling the "find" feature. Here you can see the example:
image

But if it the bug from my browser settings, please let me know.
And if you want the keypress event record anyway please let me know that also.

**Comment by Rakesh9100** [comment]
You have implemented ln(e) and has written log, which means log base 10 but calculating log base e. So prefer to change the calculation to base 10!!

And about the keypress events, I have checked the previous calculator on chrome and Edge browsers where it is working fine as expected. So prefer keeping this functionality @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, added keypress event also, Please check for any other bug if there. Otherwise it is ready to be merged!

**Comment by Rakesh9100** [comment]
Pls fix the log one @Yuvraj960

**Comment by Yuvraj960** [comment]
Done @Rakesh9100

**Comment by Yuvraj960** [comment]
Should we proceed merging this PR? @Rakesh9100

**Comment by Rakesh9100** [comment]
Looks nice, Merged!! 🥳🎉 @Yuvraj960

**Pull request merged**
