### PR TITLE
Enhance the Contributors Section

### LINKED ISSUE #172: Enhance the Contributors Section
Create a seperate page for the contributors section. Design it by enclosing in a box or some good UI design, add anmations and hover effects as well. Do share your ideas.

### PR DESCRIPTION
**Pull request by Parth4git**
# Fixes Issue🛠️

Closes #172 

# Description👨‍💻 
I have created a separate page for the contributors section, where contributor profile photo of github is present and also uses hover effect and added impressive heading

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-13 143435

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Why this is coming like this, do fix and make the commit in this same PR @Parth4git

**Comment by Parth4git** [comment]
@Rakesh9100 What issue you face pls explain me with this PR .So,I can update it

**Comment by Rakesh9100** [comment]
image

## Why the sentence is coming like this, do fix, enhance and make the commit in this same PR @Parth4git 

image

## Also, why extra files changes are visible, I have fixed it but take care from next time.

## Put screenshot in the PR description.

**Comment by Parth4git** [comment]
Corrected the issue 
Screenshot 2024-01-13 143435

**Comment by Rakesh9100** [comment]
Attch the screenshot in the PR description @Parth4git

**Comment by Rakesh9100** [comment]
Good, Merged!! ✨ @Parth4git

**Pull request merged**
