### PR TITLE
Added more features in number of days calculator

### LINKED ISSUE #129: Number-of-Days-Calculator: Add more features
### Description

Compute and show the gap in days, hours, minutes and seconds. Handy for planning and tracking.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kom-senapati**
# Fixes Issue🛠️

Closes #129 

# Description👨‍💻 
Added other units as told in the issue.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
checked with dummy dates

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
I can see it is not including the start date as well in the result if I am ryt @kom-senapati 

Align the results in the center pls
image

**Comment by kom-senapati** [comment]
Ok will correct it and center it

**Comment by Rakesh9100** [comment]
Just center it @kom-senapati 

We don't have to include the start date as we want to calculate between two dates, just `It is ${dayDifference.toFixed(0)} days from the start date to the end date, but not including the end date.<br><br>` add `not including the start date` in this line in js file  @kom-senapati

**Comment by Rakesh9100** [comment]
Are you working @kom-senapati

**Comment by kom-senapati** [comment]
> Are you working @kom-senapati

I will do now

**Comment by kom-senapati** [comment]
I can work on this.

**Comment by Rakesh9100** [comment]
image

image

Pls do these two in center as well @kom-senapati

**Comment by Rakesh9100** [comment]
Good, Merged!! 🎉 @kom-senapati

**Pull request merged**
