### PR TITLE
Add a harmonic progression calculator

### PR DESCRIPTION
**Pull request by hemant933**
# Fixes Issue🛠️

#270 

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have added demonstration in the form of GIF/video file
- [*] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-15 185415

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add Tech Stacks used and screenshot in Readme file @hemant933

**Comment by hemant933** [comment]
i added screenshot and tech stack

**Comment by Rakesh9100** [comment]
Rename your folder to `Harmonic-Progression-Calculator` and make the necessary changes wherever required @hemant933

**Comment by hemant933** [comment]
I did it

**Pull request closed without merging**
