### PR TITLE
Added point functionality to Basic Calculator

### LINKED ISSUE #634: [Feature] Add point functionality to Basic Calculator
### Description

If the innerText of the result field is blank and the user clicks . then result's innerText should be displayed as 0. 
Please assign me this task under GSSoC'24. 

### Screenshots

Before this feature the result innerText is this 
image

After adding the feature if point is at the zero index  0 will be displayed before . (point) so the resultant innerText of the result will become **0.** 
image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivangi-singhjha**
# Fixes Issue🛠️

Closes #634

# Description👨‍💻 

Added additional functionalities in the basic calculator for the point "."

# Type of change📄
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
Tested on various test cases manually.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

WhatsApp Image 2024-05-23 at 01 04 22_004cc9f6

WhatsApp Image 2024-05-23 at 02 27 01_b2ba3854

WhatsApp Image 2024-05-23 at 02 33 13_38e724cd

### CODE REVIEW

**Comment by shivangi-singhjha** [comment]
Sir kindly label this PR with GSSOC.

**Comment by Rakesh9100** [comment]
It is working in the UI only, pls do the same when user type point from the keyboard @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
> It is working in the UI only, pls do the same when user type point from the keyboard @shivangi-singhjha

Sir I have updated it. Kindly look into it. 
Please label it under gssoc

**Comment by Rakesh9100** [comment]
Good, Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @shivangi-singhjha

**Comment by Rakesh9100** [comment]
Good, Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉  @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
> Good, Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @shivangi-singhjha

Thank You! So much sir🙏

**Pull request merged**
