### PR TITLE
Fixed currency converter issue (solves #31)

### PR DESCRIPTION
**Pull request by SaranshBangar**
# Fixes Issue🛠️

Closes #31 

# Description👨‍💻 

I have added a small "if" statement that checks if the user input is valid or not, if it is not valid, the code shows an error to the user

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have ran multiple tests including alphabets, decimals, symbols and the code passes every test case

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the merge conflicts @SaranshBangar

**Comment by SaranshBangar** [comment]
Ok sir

**Comment by SaranshBangar** [comment]
> Pls resolve the merge conflicts @SaranshBangar

image
I am unable to see any merge conflicts sir

**Comment by Rakesh9100** [comment]
You dont have the fork of the updated repo. Pull the latest changes done to the repo and then make your changes to avoid merge conflicts @SaranshBangar

**Comment by SaranshBangar** [comment]
Understood sir, I am closing this PR and adding a new updated PR

**Pull request closed without merging**
