### PR TITLE
Added GCD Calculator

### LINKED ISSUE #155: GCD (Greatest Common Divisor) Calculator
Create a calculator that finds the greatest common divisor of two or more integers, aiding in simplifying fractions and mathematical operations.

### PR DESCRIPTION
**Pull request by rishiiiidha**
# Adds Calculator🛠️

fixes #155 

# Description👨‍💻 

GCD Calculator calculates greatest common divisor of two values or multiple values

# Type of change📄

- ✅ Adds calculator 

# Screenshots📷
Screenshot 2024-01-12 000615

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add a Readme.md in your calculator folder @rishiiiidha

**Comment by rishiiiidha** [comment]
@Rakesh9100 I have a doubt do I have to create another pull request or I can add here itself,
If that's possible please do let me know.

**Comment by Rakesh9100** [comment]
You can do commit in this PR only, no need to open another PR @rishiiiidha 

Just add Readme file in your fork local and then commit and push the changes.

**Comment by Rakesh9100** [comment]
Nice work, Merged!! ✨

Congrats on getting your PR merged to this repo under SWOC S4 🥳🎉 @rishiiiidha

**Pull request merged**
