### PR TITLE
Added Cube Root Calculator

### LINKED ISSUE #493: [Feature] Adding Cube Root Calculator
### Description

# Prerequisites

-  I am an Open Source Contributor.
- I follow the Contributing Guidelines.

# Description📃

Adding **Cube Root Calculator** to the Website.

# Screenshots📸

Screenshots and screen recording is mentioned below

### Screenshots

# Screenshots
imageSS

# Screen Recording
[!vidSS](https://github.com/Rakesh9100/CalcDiverse/assets/98605616/517f2b5e-f378-473f-9b76-412f2a0101da)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivamm-verma**
# Fixes Issue🛠️ #493 

Closes #493 

# Description👨‍💻 

Added a cube root calculator that returns Cube Root of any Given number.

# Type of change📄

- [x] New feature (added a Calculator)

# How this has been tested✅

Latest and the last calculator added to the website is the Cube Root Calculator.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Attach the screenshot in the PR description @shivamm-verma

**Comment by shivamm-verma** [comment]
updated @Rakesh9100

**Comment by Rakesh9100** [comment]
Make the content visible in the center of the box and make R capital in result.

image

Add a Readme of your calculator in your folder @shivamm-verma

**Comment by shivamm-verma** [comment]
#screenshots now:

### Preview Screenshot
image

### Working Screenshot
Screenshot 2024-02-03 195129

**Comment by Rakesh9100** [comment]
Make input box, Result button, and everything in the center of the box @shivamm-verma

**Comment by shivamm-verma** [comment]
## screenshots:

image

**Comment by shivamm-verma** [comment]
please check @Rakesh9100

**Comment by Rakesh9100** [comment]
Good, Merged 🎉 @shivamm-verma

**Pull request merged**
