### PR TITLE
Added PPM (Parts Per Million) Calculator

### LINKED ISSUE #1314: [Feature] Add PPM (Parts Per Million) Calculator
### Description

PPM Calculator :
The Parts Per Million (PPM) Calculator is a versatile and essential tool for accurately determining the concentration of substances in various solutions. Whether you are working in a laboratory, an industrial setting, or conducting environmental testing, this calculator simplifies the process of calculating PPM values, providing precise results quickly and efficiently.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Dark-S8uL**
# Fixes Issue🛠️

Closes #1314 

# Description👨‍💻

PPM Calculator :
The Parts Per Million (PPM) Calculator is a versatile and essential tool for accurately determining the concentration of substances in various solutions. Whether you are working in a laboratory, an industrial setting, or conducting environmental testing, this calculator simplifies the process of calculating PPM values, providing precise results quickly and efficiently.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-22 153929

Screenshot 2024-06-22 154127

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR can me merged.

**Comment by Rakesh9100** [comment]
Pls rename your folder to `PPM-Calculator` and make the necessary changes by making new commits in this same PR @Dark-S8uL

**Comment by Dark-S8uL** [comment]
@Rakesh9100 I have changed the folder name to PPM-Calculator, Please Review the Changes.

**Comment by Dark-S8uL** [comment]
@Rakesh9100 OK

**Comment by Dark-S8uL** [comment]
@Rakesh9100 Please Review

**Pull request merged**
