### PR TITLE
Added permutation and combination calculator

### PR DESCRIPTION
**Pull request by JATIN0926**
# Fixes Issue🛠️

 closes:#94

# Description👨‍💻 
Added permutation and combination calculator which can calculate nCr and nPr after taking inputs as n and r

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your calculator section in main `index.html` file  @JATIN0926 

Also, why there are two png files present? @JATIN0926

**Comment by JATIN0926** [comment]
I have added just the screenshot in readme file and these 2 png file came , and my calculator section is there in the main index.html file , please can you specify the issue where I have to add my calculator

**Comment by Rakesh9100** [comment]
You have to add your calculator section in main `index.html` file of the website so that calculator gets added to the website for users @JATIN0926

**Comment by Rakesh9100** [comment]
You have to add your calculator section in main `index.html` file of the website. Do add it [here](https://github.com/JATIN0926/CalcDiverse/blob/main/index.html) @JATIN0926

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @JATIN0926

**Comment by JATIN0926** [comment]
Please check i have fixed all issues @Rakesh9100

**Comment by Rakesh9100** [comment]
Nice work, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @JATIN0926

**Pull request merged**
