### PR TITLE
Added Sudoku Calculator

### LINKED ISSUE #1675: [Feature] Add Sudoku Calculator
### Description

Sudoku is a old game which is very hard to play. This calculator would give answers to the sudoku problem in real time with user inputs. Its calculator works on complex algorith. Assign under GSSoC'24

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vansh-codes**
# Fixes Issue🛠️

Closes #1675 

# Description👨‍💻

Sudoku calculator which can calculate user given sudoku, generate new sudoku

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image
image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@vansh-codes Please add your calculator in main index file of project.

**Comment by vansh-codes** [comment]
> @vansh-codes Please add your calculator in main index file of project.

@Nihal4777 Sorry, I didnt get your point. Index file is already in the root folder
Heres the folder structure
image

**Comment by Nihal4777** [comment]
Actually you should add your calculator in index file of project.

**Comment by Nihal4777** [comment]
So that it appears on homepage.

**Comment by vansh-codes** [comment]
Hii @Nihal4777 
Actually I did some issues with branchs so now I am not able to add in this branch
I have one more PR, I have added this calculator to index.html in that PR
You can refer and merge that PR also: #1840 
Thank you

**Pull request merged**
