### PR TITLE
Added Isogram Calculator

### LINKED ISSUE #1599: [Feature] Add Isogram Calculator
### Description

I want to add a new isogram calculator that is used to calculate whether a string entered by the user is isogram or not. A string is said to be an isogram if no letter of the alphabet occurs more than once. 
I will use HTML,CSS and JavaScript for this .
Kindly assign this task to me.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by meetarora10**
# Fixes Issue🛠️

Closes #1599 

# Description👨‍💻

I have added an Isogram calculator that calculates whether a string entered by the user is isogram or not.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100 This PR is reviewed & can be merged.

**Comment by meetarora10** [comment]
@Rakesh9100 when this will be merged ?

**Comment by meetarora10** [comment]
@Nihal4777 @Rakesh9100 when will this be merged ?

**Comment by Nihal4777** [comment]
I have let PA know. He will review and merge as soon as possible.

**Comment by meetarora10** [comment]
@Rakesh9100 please review and merge this today .

**Pull request merged**
