### PR TITLE
Enhanced the footer UI

### LINKED ISSUE #1896: [Style] Enhance the footer UI
### What's the style idea?

  in your website i want to implement some featurees:
1. added logo to footer
2. added underline animation and hover effect to all nav items
3. justified their aligned give them a proper space
4. make all heading tag more engagging by adding some colorful animation

### Screenshot:

WhatsApp Image 2024-12-10 at 01 22 57_70016bde

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by biswajit-sarkar-007**
# Fixes Issue🛠️

Closes #1896 

# Description👨‍💻

In this PR, I have updated the footer UI of all the pages.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot (632)

Screenshot (631)

Screenshot (630)

Screenshot (629)

Screenshot (628)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You don't need to create a new PR, you have to make the new commits in previous PR itself if any changes are suggested @biswajit-sarkar-007

**Comment by biswajit-sarkar-007** [comment]
@Rakesh9100  hey in first pr all pages are not included but  in this pr all pages are included. If u want u can merged this pr , I am closed the first one .

**Comment by Rakesh9100** [comment]
I will review this PR, but in the future, do update the original PR only by making the new commits if changes are suggested @biswajit-sarkar-007

**Comment by biswajit-sarkar-007** [comment]
@Rakesh9100  okay

**Pull request merged**
