### PR TITLE
Added Polynomial Roots Calculator

### LINKED ISSUE #1046: [Feature] Add Polynomial Roots Calculator
### Description

This Calculator is used to calculate the real and imaginary roots of a given polynomial in more effective and in easy way. It is designed to calculate the roots for degree 2,3, and 4 of polynomial .

### Screenshots

Screenshot 2024-06-01 at 4 02 07 PM
//You can preview the screenshot

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by DiwareNamrata23**
# Fixes Issue🛠️

Closes #1046 

# Description 👨‍💻

Added Polynomial Roots Calculator. This Calculator is used to calculate the real and imaginary roots of a given polynomial in more effective and in easy way. It is designed to calculate the roots for degree 2,3, and 4 of a polynomial.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-06-04 at 5 37 53 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your calculator in the main `index.html` file as well to display on the website @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Updated index.html please check @Rakesh9100

**Comment by Rakesh9100** [comment]
Rename your folder to `Polynomial-Roots-Calculator` only @DiwareNamrata23

**Comment by Rakesh9100** [comment]
Rename your folder to `Polynomial-Roots-Calculator` only and make the necessary changes @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Added changes to name of the folder to polynomial roots calculator .Please check @Rakesh9100

**Comment by DiwareNamrata23** [comment]
@Rakesh9100 , there are any  new changes to do now , can you please tell me the required changes ? so that I can do changes asap , or is it ok for merging ???

**Pull request merged**
