### PR TITLE
Added more functionality in Vector Calculator

### LINKED ISSUE #706: [Feature] Add more functionality in Vector Calculator
### Description

I just checked the vector calculator. The vector calculator is only calculating the dot product between 2 vectors. But operations like cross product between the 2 vectors, addition and subtraction can be done on it. 
I request to assign this task to me.

### Screenshots

image
here it is showing only the dot product and angle between it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by MohiniMehta**
# Fixes Issue🛠️

Closes #706 

# Description👨‍💻 
User needs to enter value of x and y component of both vectors.
I added the option where user can select from the dropdown list various operations like add, subtract and dot product. I added the operation add, subtract and dot product.
Depending upon the selected option the operation is performed.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I tested by inputting different values for vector.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
1) Addition:
image
2)Subtraction:
image
3)Dot product and the angle between two vecors:
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls give some space below and above the Operation box, and also style that box same as that of X or Y @MohiniMehta

**Comment by Rakesh9100** [comment]
Are you working on the suggested changes @MohiniMehta

**Comment by MohiniMehta** [comment]
Yes, I worked on it and I have updated the branch. Please check it once.

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @MohiniMehta

**Pull request merged**
