### PR TITLE
Added About Us Page

### LINKED ISSUE #488: [Feature] Add About Us Page
### Description

while going across the website ,I saw that the "About Us" page was missing . So I would like to add it into the navigation bar rather than the content which is written on the homepage which makes it look ugly.

### Screenshots

Screenshot (822)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### LINKED ISSUE #607: Redesign the About Us page !
### Description

Redesign the About Us page ! Please assign me under JWOC 2024 !

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SohanRC**
# Fixes Issue🛠️

Closes #607 

# Description👨‍💻 

Added About Us Page to the website ! Also I have added some animations to make this page more attractive and beautiful ! Moreover , I have made the whole page RESPONSIVE for mobile also.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on local system and it worked perfectly !

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-02-20 033929

### CODE REVIEW

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !!

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR !

**Comment by Rakesh9100** [comment]
Pls mention the correct issue number for this PR @SohanRC

**Comment by SohanRC** [comment]
@Rakesh9100 I think the one who had opened this issue has closed the issue ! It is not showing !

**Comment by SohanRC** [comment]
@Rakesh9100 Should i open a issue ? Please reply !

**Comment by SohanRC** [comment]
@Rakesh9100 You had assigned me this issue but its not showing !! What should i do ? Should i open an issue ?

**Comment by Rakesh9100** [comment]
I am also thinking where that issue went as closing the issue by the contributor will show the issue closed but it is not showing only!!

No matters, just open a new issue and link it to this PR @SohanRC

**Comment by SohanRC** [comment]
> I am also thinking where that issue went as closing the issue by the contributor will show the issue closed but it is not showing only!!
> 
> No matters, just open a new issue and link it to this PR @SohanRC

OK i am doing it now !

**Comment by SohanRC** [comment]
@Rakesh9100 I have opened the Issue #607

**Comment by SohanRC** [comment]
> @Rakesh9100 I have opened the Issue #607

I have opened the issue ! Please check it !

**Comment by SohanRC** [comment]
> > @Rakesh9100 I have opened the Issue #607
> 
> I have opened the issue ! Please check it !

Please check it !

**Comment by Rakesh9100** [comment]
Pls work on these: @SohanRC 

1. Pls add the About button between Home and Calculators.
2. Add an appropriate fa-icon as well.
3. Add About menu button in every page navbar such as Contributors, FAQ and Contact pages.
4. Remove all the animations from the About Page.

**Comment by SohanRC** [comment]
@Rakesh9100 I have done all the changes ! Please review this PR now !

**Comment by Rakesh9100** [comment]
Good, Merged ✨ @SohanRC

**Pull request merged**
