### PR TITLE
Added Instagram and Discord links in the footer

### LINKED ISSUE #1257: [Feature] Add Instagram and Discord links in the footer
### Description

Adding an Instagram link in the footer in place of the Facebook link so that the site looks more modern and aligned with current social media trends. 

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Kcode15**
# Fixes Issue🛠️

Closes #1257 

# Description👨‍💻
I have added Instagram and discord link in the footer section

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add in the About, Contributors, FAQ and Contact page as well @Kcode15

**Comment by Kcode15** [comment]
Okk sir

**Comment by Rakesh9100** [comment]
Do add by making the new commits in this same PR @Kcode15

**Comment by Kcode15** [comment]
@Rakesh9100 I have made changes in all the files

**Pull request merged**
