### PR TITLE
Enhanced buttons in 5 Band Resistance Calculator

### LINKED ISSUE #1473: [Style] Enhance buttons in 5 Band Resistance Calculator
### What's the style idea?

I intend to fix the :
* Primitive UI styling -  As the UI doesn't look appealing since it uses primitive HTML Styling.
* Need for scrolling and fitting the whole into the viewport -  Currently the users will have to Scroll down in order to view the full 
  features / options.  I intend to remove this by fixing the alignment and thereby ensuring a user friendly experience

Screenshot 2024-06-28 114557

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AnandK-pm**
# Fixes Issue🛠️

Closes #1473 

# Description👨‍💻

Changes include :
* Fixed the necessity of scrolling in order to see the full viewport.
* Added hover effect and styles to the calculate button.
* Added hover effect and styles to the close button in popup.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

https://github.com/Rakesh9100/CalcDiverse/assets/142206618/336eb55e-7e94-4fbf-95bd-7b2d6f3be9ae

### CODE REVIEW

**Comment by Nihal4777** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
It is not looking good, as you have just overlapped the Calculate button @AnandK-pm

**Comment by AnandK-pm** [comment]
will request a new pull request to avoid conflicts ?

**Comment by AnandK-pm** [comment]
> There is no conflict, you have only made it overlap as you can check in the screen recording you provided above, so the existing UI is only good @AnandK-pm 

No. I have removed the scrolling and the webpage fit into it without any need for scrolling. Please look at it.

**Pull request merged**
