### PR TITLE
Added Depth Of Field Calculator

### LINKED ISSUE #676: [Feature] Add Depth Of Field Calculator
### Description

This calculator helps photographers determine the depth of field (the range of distance that appears acceptably sharp in a photograph) based on factors such as aperture, focal length, subject distance, and sensor size.

@Rakesh9100 Can you please assign me this issue under GSSoC'24. 
I would love to work on this addition.

Thank You!

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by diyaaa19**
# Fixes Issue🛠️

Closes #676 

# Description👨‍💻 

Depth Of Field Calculator successfully added.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF

image

### CODE REVIEW

**Comment by diyaaa19** [comment]
@Rakesh9100 please review my PR and merge if everything is in place, thanks.
#676 #677 proposed PR for both

**Comment by Rakesh9100** [comment]
Merged 🎉 @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 can you please add the SWOC label as well, thanks

**Comment by Rakesh9100** [comment]
No, this project is currently taking contributions for GSSOC and not SWOC @diyaaa19

**Pull request merged**
