### PR TITLE
Enhancement of Footer 

### LINKED ISSUE #38: Enhancement Of Footer
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

**Enhancement Of Footer** 

This issue is to make the footer of the website much more responsive and interactive.
The following features will be updated in this issue:
- Interactive
- Responsive
- Social Media Links
- Social Media Icons
- Hover Effects 
- 
The changes before and after the improvements can be seen below in the **Screenshots** section.

#SWOC 

### Screenshots

**Original Footer :** 

CalcDiverse Before

**Footer after making Improvements:**

CalcDiverse After 1

**Footer with Hover Effects :**

CalcDiverse After 2 logo hover
CalcDiverse After 3 text hover

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by CodeByRajeev**
# Fixes Issue : #38 - Enhancement of Footer.
Closes #38 

**# Description👨‍💻 & Type Of Change :**   

This issue is to make the footer of the website much more responsive and interactive.
The following features will be updated in this issue:

-Interactive
-Responsive
-Social Media Links
-Social Media Icons
-Hover Effects

**# Checklist✅** 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Improvements:

The following screenshots shows the changes implemented :
**Before :** 

CalcDiverse Before

**After making the improvements :**  
CalcDiverse After 1

**Footer with Hover Effects :**    

CalcDiverse After 2 logo hover

CalcDiverse After 3 text hover

### CODE REVIEW

**Comment by CodeByRajeev** [comment]
Hi @Rakesh9100 @Mannxxx I have done the enhancement and please let me know if any other improvements can be done. 

If everything has been good, please do MERGE the PULL REQUEST.

**Comment by Rakesh9100** [comment]
Pls resolve the merge conflict @CodeByRajeev

**Review by CodeByRajeev — COMMENTED** [review]
@Rakesh9100 The conflicts has been resolved and if still there are any do let me know. As I am not so good with contributing, I might miss few things.

**Comment by Rakesh9100** [comment]
Just add the items present in the navbar in your list-inline-items i.e. Home, Calculators, and Contact and link the ids @CodeByRajeev

**Comment by CodeByRajeev** [comment]
@Rakesh9100 The changes have been made accordingly. Please have a look.



**Enhanced Footer :**   
Footer Required 1


**Footer with hover effects :** 
Footer Required 2 hover

Footer Required 3 hover

**Comment by Rakesh9100** [comment]
You have removed the previous footer css due to which contact page footer is disturbed. Pls do add your same footer in contact.html as  well @CodeByRajeev

**Comment by CodeByRajeev** [comment]
@Rakesh9100 Would love to inform that unknowingly making mistakes and resolving them for an hour, successfully updated the footer of the contact page.

The result is as below:

Contact-CalcDiverse Footer 1after


Please let me know if any more changes are required.

**Comment by Rakesh9100** [comment]
You will learn by making mistakes only, so don't worry. Open Source programs are for these kind of learnings only.

Looks good, Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @CodeByRajeev

**Pull request merged**
