### PR TITLE
Added Probability Calculator

### LINKED ISSUE #546: [Feature] Probability Calculator
### Description

@Rakesh9100  I can add probability calculator, in which different probability such as chances of event to occur , chances of event not to occur, chances of one event occur and one event does not occur,etc. can be calculated.
Please assign me this under SWOC.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by NirbhayTiwari15**
# Fixes Issue🛠️

Closes #546 

# Description👨‍💻 

This Calculator calculates the probability of different events to occur based on user input.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my device and it worked properly.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these changes and make the commits in this PR only of your changes.

1. Pls edit the PR description as per the PR template.
2. Mention the issue number this PR closes.
3. Include your calculator section in main `index.html` file as well.
4. Add a Readme of your calculator in your folder @NirbhayTiwari15

**Comment by NirbhayTiwari15** [comment]
I have commited the changes @Rakesh9100 , please review it.

**Comment by Rakesh9100** [comment]
1. Add your calculator section in [this](https://github.com/NirbhayTiwari15/CalcDiverse/blob/main/index.html) file.
2. Enhance your calculator UI.
3. Add the screenshot in the Readme file @NirbhayTiwari15

**Comment by NirbhayTiwari15** [comment]
@Rakesh9100 ,I have completed the changes, please review it.

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @NirbhayTiwari15

**Pull request merged**
