### PR TITLE
Added ROI Calculator

### LINKED ISSUE #859: [Feature] Add ROI Calculator
### Description

In finance, Return on Investment, usually abbreviated as ROI, is a common, widespread metric used to evaluate the forecasted profitability on different investments.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #859 

# Description👨‍💻 

Gives the amount gained on your investment.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

- [x] Tested all the results from an already existing ROI calculator on web
- [x] Verified all the results from the manual formulae. 

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls style and enhance the UI to little extent and always add your calculator in index.html file in alphabetical order @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have Updated the styles.css, I am sure you will like it. 
image

**Comment by Yuvraj960** [comment]
@Rakesh9100  Some unusual conflict was happening in the merging so one calculator named salary estimation calculator was removed, I have added that back again in new commit so please verify if everything is all right in merging activity now.

**Comment by Rakesh9100** [comment]
Merged 🎉 @Yuvraj960 

Pls check these and keep in mind on priority basis from the next time contribution:-
1. CSS file name should be `style.css` and not `styles.css`.
2. Add the Readme according to the template, you can check the Readme of existing calculators. You can add your extra things as well but maintain the structure.
3. Add your calculator in `index.html` file in alphabetical order!!

**Pull request merged**
