### PR TITLE
Added Zodiac Sign Calculator

### LINKED ISSUE #1512: [Feature] Add Zodiac Sign Calculator
### Description

The Zodiac Calculator allows users to input their birthdate and receive their corresponding zodiac sign. This tool is perfect for those interested in astrology and looking to discover their astrological sign based on their date of birth.

Tech Stack:
HTML: For the structure of the web page.
CSS: For styling the calculator interface.
JavaScript: For calculating the zodiac sign based on the birthdate input.

### Screenshots

zodiac calc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by nadarmega**
# Fixes Issue🛠️

Closes #1512 

# Description👨‍💻

The Zodiac Sign Calculator, takes your birthdate as input and calculates your zodiac sign and also gives you a little trivia about your personality!

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Zodiac Calculator

### CODE REVIEW

**Comment by Nihal4777** [comment]
@nadarmega  Please fix the issues.


image


image

**Comment by nadarmega** [comment]
@Rakesh9100 @Nihal4777 I have made the changes!

**Comment by Rakesh9100** [comment]
Rename your calculator folder to `Zodiac-Sign-Calculator` and make the necessary changes by making the new commits in this same PR @nadarmega

**Comment by nadarmega** [comment]
@Rakesh9100 I have made the changes

**Comment by nadarmega** [comment]
@Rakesh9100 Please review!

**Comment by Nihal4777** [comment]
@nadarmega  Still URL is broken. Just remove extra `.`
image
image

**Comment by nadarmega** [comment]
@Rakesh9100 @Nihal4777 Thank you for pointing out my error...i have changed this, please review

**Comment by Nihal4777** [comment]
@nadarmega Just try adding any date >=22 December .
image

**Comment by nadarmega** [comment]
@Nihal4777 I have corrected the error!

**Comment by Nihal4777** [comment]
@nadarmega Yes, The issue is now resolved.
Can you please fix overflow on mobile screens.
 
image

**Comment by nadarmega** [comment]
@Nihal4777 I have made it responsive for mobile phones!

**Comment by nadarmega** [comment]
@Nihal4777 kindly, review it

**Comment by Nihal4777** [comment]
@nadarmega Still overflow exists.
Screenshot_20240725-231240

**Comment by nadarmega** [comment]
@Nihal4777 I have made the changes, I tried deploying my forked repository on netlify, it works properly.
I dont know where the fault is.
Screenshot 2024-07-26 134248

**Comment by Nihal4777** [comment]
Okay, Looks like netlify preview is not updated here
.

**Comment by nadarmega** [comment]
okay, so from my side, it's all good? do I need to do anything?

**Comment by Nihal4777** [comment]
> okay, so from my side, it's all good? do I need to do anything?

I don't think so. Looks good.

**Comment by Nihal4777** [comment]
This PR is reviewed & can be merged.

**Comment by Rakesh9100** [comment]
https://github.com/Rakesh9100/CalcDiverse/pull/1596/files

Pls check this, why number of file changes are 115, keep only your files in this PR and no other changes @nadarmega

**Pull request merged**
