### PR TITLE
Added Gauss-Jordan Elimination Calculator

### LINKED ISSUE #1421: [Feature] Add Gauss-Jordan Elimination Calculator
### Description

user can solve systems of simultaneous linear equations using Gauss-Jordan Elimination Calculator

### Screenshots

Screenshot 2024-06-24 172131

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Vipullakum007**
# Fixes Issue🛠️

Closes #1421

# Description👨‍💻

```
hey @Rakesh9100 , i created file

./Calculators
  /Gauss-Jordan-Calculator
    /index.html
    /style.css
    /script.js
```

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [ ] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please review it.

**Comment by Rakesh9100** [comment]
Pls work on these by making the new commits in this same PR @Vipullakum007 

1. Rename your calculator folder to `Gauss-Jordan-Elimination-Calculator` and make the necessary changes.
2. Add a README.md file of your calculator in your folder.
3. Style and enhance the UI to some extent.

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , updated as per your suggestion you can merge it.

**Comment by Nihal4777** [comment]
@Vipullakum007 Please fix the issue, link is broken.
image

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , now check.

**Comment by Rakesh9100** [comment]
1. Enter Rows as 5 and Columns as 2, then Calculate and check why values are NaN.
2. Also, the page is not fully scrollable when more rows are added.
3. Handle the NaN values @Vipullakum007

**Comment by Rakesh9100** [comment]
Are you working or not @Vipullakum007

**Comment by Nihal4777** [comment]
@Vipullakum007 It appears you are not active.

**Comment by Nihal4777** [comment]
@Rakesh9100 We can close the PR.

**Pull request closed without merging**
