### PR TITLE
Added Hexadecimal Calculator

### LINKED ISSUE #923: [Feature] Add Hexadecimal Calculator
### Description

propose the addition of a hexadecimal calculator feature to our application. The hexadecimal calculator will enable users to perform arithmetic operations, conversions, and manipulations specifically with hexadecimal numbers.

### Screenshots

Screenshot (138)
Screenshot (139)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yashgabani845**
# Fixes Issue🛠️

Closes #923 

# Description👨‍💻 

I have added Hexadecimal calculator with required html, js and bootstrap code.
Also made readme.md file.
And added box in index.html and set links.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested my calculator with each operation with normal values and edge cases as well.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (287)
Screenshot (288)

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@Rakesh9100  
please reivew this PR an if all works well
merge and give required labels so that no conflict occure in future
also please assign this issue from stand by
[Feature] Add Amortization Calculator #928
Thank you for this Opportunity

**Comment by Rakesh9100** [comment]
Pls style and enhance the UI @Yashgabani845

**Comment by Yashgabani845** [comment]
@Rakesh9100 ok i am enhacing UI

**Comment by Yashgabani845** [comment]
Screenshot (300)

this is the Enhanced UI of my calculator
@Rakesh9100 please check it

**Comment by Rakesh9100** [comment]
`Hexadecimal Calculator` heading is not visible properly, change its text color. Also center the Calculate and Clear buttons.

Rename the folder to `Hexadecimal-Calculator` and make the necessary changes @Yashgabani845

**Comment by Yashgabani845** [comment]
@Rakesh9100  i done required chnages
sorry for this mistakes,

**Comment by Rakesh9100** [comment]
Instead of using a URL for the background, download the image, rename it to background.jpg, create an assets folder inside your calculator folder, and place the image there. Then link and use it from the assets folder @Yashgabani845

**Comment by Yashgabani845** [comment]
@Rakesh9100 done the changes
thanks for reviewing this many times and sorry about inconvenience

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @Yashgabani845

**Pull request merged**
