### PR TITLE
Navbar elements readability fixed in mobile devices

### LINKED ISSUE #581: [Bug] Navbar elements not readable in mobile devices
### What's the style idea?

The navbar elements are not readable.The background's CSS must be adjusted. I want to work on this issue. Kindly assign me.

Screenshot_20240212_003932_Chrome

Under JWOC.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Abhishek-465**
# Fixes Issue🛠️
#581 

Closes #581 

# Description👨‍💻 
I have adjusted the CSS and HTML files to make the content visible.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of image
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (11)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Just keep your changes without making any indentation or other changes @Abhishek-465

**Comment by Abhishek-465** [comment]
> image
> 
> Just keep your changes without making any indentation or other changes @Abhishek-465

Okay then correcting the indentation.

**Comment by Abhishek-465** [comment]
@Rakesh9100 Kindly look the change

**Comment by Rakesh9100** [comment]
Fix `style.css` indentation as well @Abhishek-465

**Comment by Rakesh9100** [comment]
Pls fix `style.css` indentation as well @Abhishek-465

**Comment by Abhishek-465** [comment]
@Rakesh9100  I cannot understand what is the point of the indentation changes which you are  referring.The code is working fine, the indentation also looks normal. I think there shouldn't be any problem with this PR.

**Comment by Rakesh9100** [comment]
image

Code is working fine, but the changes in any PR should be done only of your work and not any other unnecessary changes @Abhishek-465

**Comment by Rakesh9100** [comment]
image

Code is working fine, but the changes in any PR should be done only of your work and not any other unnecessary changes @Abhishek-465 

Example:
image

Dont reduce 2 spaces, keep indentation of 4 spaces only as per the project!!

**Comment by Rakesh9100** [comment]
image

Code is working fine, but the changes in any PR should be done only of your work and not any other unnecessary changes!!
Example:
image

Don't reduce 2 spaces, keep indentation of 4 spaces only as per the project @Abhishek-465

**Comment by Rakesh9100** [comment]
image

Code is working fine, but the changes in any PR should be done only of your work and not any other unnecessary changes!!

### Example:
image

Don't reduce 2 spaces, keep indentation of 4 spaces only as per the project @Abhishek-465

**Comment by Abhishek-465** [comment]
@Rakesh9100 I have corrected all the indentations. 
Kindly check it.
Thank you.

**Comment by Rakesh9100** [comment]
1. Background should appear to the full down of the screen.

2. Use any background color instead of any image or it's URL.

4. Make the hamburger appearance same in Contributor, FAQ and contact page as well @Abhishek-465

**Pull request closed without merging**
