### PR TITLE
Added square root calculator

### LINKED ISSUE #16: Square Root Calculator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculate the square root of a given number.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by sidharth2829**
# Fixes Issue🛠️

Closes #16 

# Description👨‍💻 

I have added a square root calculator, which calculates the SQRT upto provided precision.

# Type of change📄

I have added square root calculator Div in index.html
And created necessary files for the calculator.

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-01-02 at 10 07 34 PM

Screenshot 2024-01-02 at 10 08 02 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉 @sidharth2829

**Comment by Rakesh9100** [comment]
Pls add a README.md inside that folder as well which should include description, tech stacks used and screenshot @sidharth2829

**Comment by JrG-One** [comment]
@sidharth2829 could you please tell me the process of push my changes

**Comment by Rakesh9100** [comment]
Pls go through this properly [Check](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) @JrG-One

**Comment by Rakesh9100** [comment]
> @sidharth2829 could you please tell me the process of push my changes

Pls don't mention any other contributor as I am the Project Admin @JrG-One

**Comment by JrG-One** [comment]
I apologize for any inconvenience caused. @Rakesh9100

**Comment by Rakesh9100** [comment]
Are you working @sidharth2829

**Comment by sidharth2829** [comment]
Yes @Rakesh9100, i will push my commit till tomorrow morning.

**Comment by Rakesh9100** [comment]
Should I close the PR and unassign you the issue @sidharth2829

**Comment by sidharth2829** [comment]
Oh sorry @Rakesh9100 , i have already made the PR on a new branch , because this one was causing too much conflicts.

**Comment by sidharth2829** [comment]
See pull request #112

**Comment by Rakesh9100** [comment]
Okay @sidharth2829

**Pull request closed without merging**
