### PR TITLE
Added Angle Between Two Lines Calculator

### PR DESCRIPTION
**Pull request by AMS003010**
# Fixes Issue🛠️
Closes [#1123](https://github.com/Rakesh9100/CalcDiverse/issues/1123)

Closes #

# Description👨‍💻
I have added Angle between two lines Calculator which calculates the angle between two lines. he line equations are given as input and the angle between them is returned as output in degrees.

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [ ] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Nihal4777** [comment]
@AMS003010  Fix the issue in main index.html file.
image

**Comment by Rakesh9100** [comment]
Why the files of `Frames-Timecode-Calculator` is showing, fix the conflict in this same PR @AMS003010

**Comment by AMS003010** [comment]
Sorry got caught up, I'll fix it by today

**Comment by AMS003010** [comment]
@Rakesh9100  Sorry for the delay 😅

I have fixed all changes and fixed all issues. I have reviewed and made sure that there are no issues.

**Comment by Nihal4777** [comment]
@AMS003010 The page is not responsive. Are you going to do that?
image

**Comment by AMS003010** [comment]
I'll look into it...

**Comment by AMS003010** [comment]
@Rakesh9100 I have made it responsive

**Comment by Rakesh9100** [comment]
> Why the files of `Frames-Timecode-Calculator` is showing, fix the conflict in this same PR @AMS003010

This is still not fixed, I tried to delete by making commit but it deleted the files originally @AMS003010

**Comment by AMS003010** [comment]
I'll look into it....

**Comment by AMS003010** [comment]
@Rakesh9100 
I have done the necessary
It should be fine now

**Comment by Rakesh9100** [comment]
https://github.com/Rakesh9100/CalcDiverse/pull/1435/files

Check here, number of files changed are 13 which should not be @AMS003010

**Comment by AMS003010** [comment]
Yes it does say 13 files but that is because I had made a lot of commits to this issue (which included both addition and deletion). I have only made made changes in my `frames-timecode-calculator` folder and I have added that calculator in the main `index.html`

**Comment by Rakesh9100** [comment]
The file changes of `Frames-Timecode-Calculator` should not show up in this PR by any chance @AMS003010

**Comment by AMS003010** [comment]
Sure I will look  into it....

**Comment by Rakesh9100** [comment]
Any update, fix this ASAP @AMS003010

**Comment by AMS003010** [comment]
I'll try to call a new PR only on those changes...
I close this one as I am not able to revert to previous changes

**Pull request closed without merging**
