### PR TITLE
Added Pet Care Cost Calculator

### LINKED ISSUE #1650: [Feature] Add Pet Care Cost Calculator
### Description

Calculates the lifetime cost of owning different types of pets, including food, healthcare, and other expenses, based on current market prices.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ANKeshri**
# Fixes Issue🛠️

Closes #1650 

# Description👨‍💻

Added a new calculator pet care calculator 

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Rakesh9100 PLEASE REVIEW ANSD MERGE MY PR

**Comment by Nihal4777** [comment]
Hi @ANKeshri Please add empty field validations wherever required.

**Comment by ANKeshri** [comment]
> Hi @ANKeshri Please add empty field validations wherever required.

done

**Comment by Rakesh9100** [comment]
Rename your calculator folder to `Pet-Care-Cost-Calculator` and make the necessary changes @ANKeshri

**Comment by ANKeshri** [comment]
@Rakesh9100 done

**Pull request merged**
