### PR TITLE
Added Binomial Distribution Calculator

### LINKED ISSUE #773: [Feature] Add Binomial Distribution Calculator
### Description

I made a calculator on values of probability distribution function of a random binomial variable. It was a new kind of calculator from the existing ones. Please review my request.

### Screenshots

calc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sara1428**
# Fixes Issue🛠️ 

Closes #773 

# Description👨‍💻 

Added Binomial Distribution Calculator.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

calc

### CODE REVIEW

**Comment by Rakesh9100** [comment]
For which issue have you created this PR @Sara1428

**Comment by Sara1428** [comment]
> For which issue have you created this PR @Sara1428
It is issue #773

**Comment by Sara1428** [comment]
Actually you assigned this issue to me yesterday

**Comment by Rakesh9100** [comment]
Please do not create a PR until you have been assigned to an issue from the next time!!

Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @Sara1428

**Comment by Sara1428** [comment]
> Please do not create a PR until you have been assigned to an issue from the next time!!
> 
> Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳 @Sara1428

Thank you sir !
I'll surely follow your guideline from next time.

**Pull request merged**
